In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("actions_taken_1-2-3_state_TX.csv")

C:\Users\LENOVO GAMING\AppData\Local\Temp\ipykernel_24896\3153693736.py:1: DtypeWarning: Columns (0: loan_to_value_ratio, 1: interest_rate, 2: rate_spread, 3: total_loan_costs, 4: total_points_and_fees, 5: origination_charges, 6: discount_points, 7: lender_credits, 8: loan_term, 9: prepayment_penalty_term, 10: intro_rate_period, 11: property_value, 12: total_units, 13: multifamily_affordable_units) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("actions_taken_1-2-3_state_TX.csv")

In [3]:
df

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2024,549300LYRWPSYPK6S325,19124,TX,48397.0,4.839704e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2091,27.50,110300,173,885,914,13
1,2024,549300LYRWPSYPK6S325,41700,TX,48493.0,4.849300e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2582,31.91,89300,169,773,804,21
2,2024,549300LYRWPSYPK6S325,18580,TX,48355.0,4.835501e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,7502,66.34,81100,160,1784,2263,16
3,2024,549300LYRWPSYPK6S325,41700,TX,48091.0,4.809131e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,5451,25.32,89300,112,1502,1669,16
4,2024,549300LYRWPSYPK6S325,19124,TX,48085.0,4.808503e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,7554,42.65,110300,112,1498,2020,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
710201,2024,549300LYRWPSYPK6S325,99999,TX,48089.0,4.808975e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,4773,34.19,75500,120,1644,2989,33
710202,2024,549300LYRWPSYPK6S325,18580,TX,48355.0,4.835501e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,2654,66.31,81100,101,386,796,33
710203,2024,549300LYRWPSYPK6S325,26420,TX,48201.0,4.820153e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,3050,53.84,97400,93,835,1046,48
710204,2024,549300LYRWPSYPK6S325,99999,TX,48217.0,4.821796e+10,C,VA:First Lien,Single Family (1-4 Units):Manufactured,Not Hispanic or Latino,...,NaN,NaN,NaN,4674,13.82,75500,126,1526,2424,24
710205,2024,549300LYRWPSYPK6S325,99999,TX,48279.0,4.827995e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2179,57.00,75500,98,705,1129,60

In [11]:
df.shape

(710206, 99)

In [4]:
df = pd.read_csv("actions_taken_1-2-3_state_TX.csv")

C:\Users\LENOVO GAMING\AppData\Local\Temp\ipykernel_24896\3153693736.py:1: DtypeWarning: Columns (0: loan_to_value_ratio, 1: interest_rate, 2: rate_spread, 3: total_loan_costs, 4: total_points_and_fees, 5: origination_charges, 6: discount_points, 7: lender_credits, 8: loan_term, 9: prepayment_penalty_term, 10: intro_rate_period, 11: property_value, 12: total_units, 13: multifamily_affordable_units) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("actions_taken_1-2-3_state_TX.csv")

In [13]:
df.shape

(710206, 99)

In [5]:
df.isna().sum()

activity_year                           0
lei                                     0
derived_msa-md                          0
state_code                              0
county_code                          4971
                                     ...
ffiec_msa_md_median_family_income       0
tract_to_msa_income_percentage          0
tract_owner_occupied_units              0
tract_one_to_four_family_homes          0
tract_median_age_of_housing_units       0
Length: 99, dtype: int64

In [15]:
missing_values = df.isna().sum()

missing_values[missing_values > 0]

county_code                       4971
census_tract                     13760
conforming_loan_limit             1984
loan_to_value_ratio              81468
interest_rate                   183431
rate_spread                     229201
total_loan_costs                288541
total_points_and_fees           679709
origination_charges             285353
discount_points                 450074
lender_credits                  559137
loan_term                        12464
prepayment_penalty_term         692297
intro_rate_period               618770
property_value                   27186
multifamily_affordable_units    692100
income                           43696
debt_to_income_ratio             53332
applicant_ethnicity-1              347
applicant_ethnicity-2           606557
applicant_ethnicity-3           708499
applicant_ethnicity-4           710156
applicant_ethnicity-5           710194
co-applicant_ethnicity-1           110
co-applicant_ethnicity-2        669185
co-applicant_ethnicity-3        709612
co-applicant_ethnicity-4        710195
co-applicant_ethnicity-5        710203
applicant_race-1                   306
applicant_race-2                655471
applicant_race-3                706956
applicant_race-4                709767
applicant_race-5                710069
co-applicant_race-1                 96
co-applicant_race-2             689747
co-applicant_race-3             709079
co-applicant_race-4             710057
co-applicant_race-5             710150
applicant_age_above_62           15836
co-applicant_age_above_62       412468
aus-2                           658369
aus-3                           694619
aus-4                           703727
aus-5                           704434
denial_reason-2                 665915
denial_reason-3                 701428
denial_reason-4                 707833
dtype: int64

In [6]:
missing_percent = (df.isna().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": missing_percent
})

missing_summary[missing_summary["Missing_Count"] > 0].sort_values(
    by="Missing_Percent",
    ascending=False
)

                              Missing_Count  Missing_Percent
co-applicant_ethnicity-5             710203        99.999578
co-applicant_ethnicity-4             710195        99.998451
applicant_ethnicity-5                710194        99.998310
applicant_ethnicity-4                710156        99.992960
co-applicant_race-5                  710150        99.992115
applicant_race-5                     710069        99.980710
co-applicant_race-4                  710057        99.979020
applicant_race-4                     709767        99.938187
co-applicant_ethnicity-3             709612        99.916362
co-applicant_race-3                  709079        99.841314
applicant_ethnicity-3                708499        99.759647
denial_reason-4                      707833        99.665872
applicant_race-3                     706956        99.542386
aus-5                                704434        99.187278
aus-4                                703727        99.087729
denial_reason-3                      701428        98.764021
aus-3                                694619        97.805285
prepayment_penalty_term              692297        97.478337
multifamily_affordable_units         692100        97.450599
co-applicant_race-2                  689747        97.119287
total_points_and_fees                679709        95.705894
co-applicant_ethnicity-2             669185        94.224070
denial_reason-2                      665915        93.763640
aus-2                                658369        92.701132
applicant_race-2                     655471        92.293081
intro_rate_period                    618770        87.125426
applicant_ethnicity-2                606557        85.405784
lender_credits                       559137        78.728848
discount_points                      450074        63.372317
co-applicant_age_above_62            412468        58.077234
total_loan_costs                     288541        40.627790
origination_charges                  285353        40.178906
rate_spread                          229201        32.272467
interest_rate                        183431        25.827858
loan_to_value_ratio                   81468        11.471038
debt_to_income_ratio                  53332         7.509371
income                                43696         6.152581
property_value                        27186         3.827903
applicant_age_above_62                15836         2.229776
census_tract                          13760         1.937466
loan_term                             12464         1.754984
county_code                            4971         0.699938
conforming_loan_limit                  1984         0.279356
applicant_ethnicity-1                   347         0.048859
applicant_race-1                        306         0.043086
co-applicant_ethnicity-1                110         0.015488
co-applicant_race-1                      96         0.013517

In [17]:
missing_values.sort_values().head(20)

activity_year                     0
lei                               0
derived_msa-md                    0
state_code                        0
derived_loan_product_type         0
derived_race                      0
derived_ethnicity                 0
derived_dwelling_category         0
action_taken                      0
purchaser_type                    0
preapproval                       0
derived_sex                       0
loan_type                         0
reverse_mortgage                  0
lien_status                       0
loan_purpose                      0
business_or_commercial_purpose    0
loan_amount                       0
hoepa_status                      0
open-end_line_of_credit           0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(1087)

In [8]:
df[df.duplicated(keep=False)].head(10)

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
4432,2024,549300T94GSH3C4U5M59,26420,TX,48201.0,4.820156e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4101,36.11,97400,85,558,963,34
4434,2024,549300T94GSH3C4U5M59,26420,TX,48201.0,4.820156e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4101,36.11,97400,85,558,963,34
8571,2024,549300U3721PJGQZYY68,41700,TX,48091.0,4.809131e+10,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,9528,31.48,89300,200,2368,2617,14
8585,2024,549300U3721PJGQZYY68,41700,TX,48091.0,4.809131e+10,C,Conventional:Subordinate Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,9528,31.48,89300,200,2368,2617,14
8646,2024,549300VYK2WBD7SST478,23104,TX,48439.0,4.843911e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4720,88.90,101800,64,365,877,28
8648,2024,549300VYK2WBD7SST478,23104,TX,48439.0,4.843911e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4720,88.90,101800,64,365,877,28
8676,2024,549300VYK2WBD7SST478,19124,TX,48257.0,4.825705e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,2839,45.23,110300,84,896,1044,25
8677,2024,549300VYK2WBD7SST478,19124,TX,48257.0,4.825705e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,2839,45.23,110300,84,896,1044,25
8688,2024,549300VYK2WBD7SST478,19124,TX,48397.0,4.839704e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,3882,46.01,110300,85,779,892,21
8689,2024,549300VYK2WBD7SST478,19124,TX,48397.0,4.839704e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,3882,46.01,110300,85,779,892,21

In [9]:
df.dtypes

activity_year                          int64
lei                                      str
derived_msa-md                         int64
state_code                               str
county_code                          float64
                                      ...
ffiec_msa_md_median_family_income      int64
tract_to_msa_income_percentage         int64
tract_owner_occupied_units             int64
tract_one_to_four_family_homes         int64
tract_median_age_of_housing_units      int64
Length: 99, dtype: object

In [21]:
df.dtypes.value_counts()

int64      40
float64    32
object     14
str        13
Name: count, dtype: int64

In [10]:
df[['loan_amount', 'property_value', 'income', 'loan_to_value_ratio', 'debt_to_income_ratio']].describe()

        loan_amount        income
count  7.102060e+05  6.665100e+05
mean   3.135370e+05  1.569819e+02
std    2.111020e+06  2.872468e+03
min    5.000000e+03 -1.020900e+04
25%    1.250000e+05  7.100000e+01
50%    2.450000e+05  1.090000e+02
75%    3.550000e+05  1.680000e+02
max    6.450000e+08  1.620000e+06

In [23]:
df[['loan_amount', 'property_value', 'income',
    'loan_to_value_ratio', 'debt_to_income_ratio']].dtypes

loan_amount             float64
property_value           object
income                  float64
loan_to_value_ratio      object
debt_to_income_ratio        str
dtype: object

In [11]:
df[['loan_amount', 'property_value', 'income',
    'loan_to_value_ratio', 'debt_to_income_ratio']].describe(include='all')

,loan_amount,property_value,income,loan_to_value_ratio,debt_to_income_ratio
count,7.102060e+05,683020,6.665100e+05,628738,656874
unique,NaN,1715,NaN,99735,20
top,NaN,Exempt,NaN,80,50%-60%
freq,NaN,16710,NaN,38014,83713
mean,3.135370e+05,NaN,1.569819e+02,NaN,NaN
std,2.111020e+06,NaN,2.872468e+03,NaN,NaN
min,5.000000e+03,NaN,-1.020900e+04,NaN,NaN
25%,1.250000e+05,NaN,7.100000e+01,NaN,NaN
50%,2.450000e+05,NaN,1.090000e+02,NaN,NaN
75%,3.550000e+05,NaN,1.680000e+02,NaN,NaN
max,6.450000e+08,NaN,1.620000e+06,NaN,NaN

In [12]:
print("PROPERTY VALUE")
print(df['property_value'].dropna().unique()[:20])

print("\nLOAN TO VALUE RATIO")
print(df['loan_to_value_ratio'].dropna().unique()[:20])

print("\nDEBT TO INCOME RATIO")
print(df['debt_to_income_ratio'].dropna().unique())

PROPERTY VALUE
['335000' '705000' '635000' '505000' '305000' '385000' '285000' '345000'
 '215000' '555000' '275000' '85000' '535000' '245000' '195000' '695000'
 '365000' '575000' '595000' '515000']

LOAN TO VALUE RATIO
['39.394' '101.607' '95' '96.5' '83.282' '69' '100' '89' '91.532' '84.407'
 '96.226' '80' '85.714' '95.5' '85' '47' '94.86' '93.62' '60' '66.368']

DEBT TO INCOME RATIO
<StringArray>
['20%-<30%',       '43',       '49',       '44',       '47',       '48',
       '37', '30%-<36%',       '38',  '50%-60%',       '46',     '>60%',
       '42',       '41',       '40',       '36',       '39',     '<20%',
       '45',   'Exempt']
Length: 20, dtype: str

In [13]:
print("PROPERTY VALUE")
print(df['property_value'].value_counts(dropna=False).head(20))

print("\nLOAN TO VALUE RATIO")
print(df['loan_to_value_ratio'].value_counts(dropna=False).head(20))

print("\nDEBT TO INCOME RATIO")
print(df['debt_to_income_ratio'].value_counts(dropna=False))

PROPERTY VALUE
property_value
NaN         27186
Exempt      16710
285000      10451
305000      10440
255000      10306
295000      10137
275000      10074
265000      10045
325000       9566
315000       9496
355000       8826
245000       8792
305000.0     8713
235000       8590
335000       8493
255000.0     8309
225000       8220
275000.0     8217
345000       8182
285000.0     8055
Name: count, dtype: int64

LOAN TO VALUE RATIO
loan_to_value_ratio
NaN       81468
80        38014
96.5      37780
96.5      30758
80.0      29607
100       22208
95        21051
95.0      17401
Exempt    16714
100.0     16308
75        13802
90        12896
75.0      10237
90.0       9456
97.0       7023
70         6638
97         5484
70.0       5471
85         4027
60         3047
Name: count, dtype: int64

DEBT TO INCOME RATIO
debt_to_income_ratio
50%-60%     83713
30%-<36%    83270
20%-<30%    76278
>60%        54057
NaN         53332
<20%        33308
49          31453
44          25959
42          24575
43          23358
48          22480
41          22236
47          22077
45          21436
40          20807
46          20735
39          20353
38          18942
37          17910
36          17117
Exempt      16810
Name: count, dtype: int64

In [14]:
df['property_value_clean'] = pd.to_numeric(
    df['property_value'],
    errors='coerce'
)

df['loan_to_value_ratio_clean'] = pd.to_numeric(
    df['loan_to_value_ratio'],
    errors='coerce'
)

df[['property_value', 'property_value_clean',
    'loan_to_value_ratio', 'loan_to_value_ratio_clean']].head(20)

,property_value,property_value_clean,loan_to_value_ratio,loan_to_value_ratio_clean
0,335000,335000.0,39.394,39.394
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,705000,705000.0,101.607,101.607
4,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN
9,635000,635000.0,95,95.000
10,NaN,NaN,NaN,NaN
11,505000,505000.0,96.5,96.500
12,305000,305000.0,83.282,83.282
13,385000,385000.0,96.5,96.500
14,705000,705000.0,69,69.000
15,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN

In [15]:
df['property_value_clean'] = pd.to_numeric(
    df['property_value'].replace('Exempt', pd.NA),
    errors='coerce'
)

df['loan_to_value_ratio_clean'] = pd.to_numeric(
    df['loan_to_value_ratio'].replace('Exempt', pd.NA),
    errors='coerce'
)

In [16]:
pd.to_numeric(..., errors='coerce')

ValueError: Buffer has wrong number of dimensions (expected 1, got 0)

In [17]:
df['property_value_clean'] = pd.to_numeric(
    df['property_value'],
    errors='coerce'
)

In [18]:
df[['property_value', 'property_value_clean']].head(20)

   property_value  property_value_clean
0          335000              335000.0
1             NaN                   NaN
2             NaN                   NaN
3          705000              705000.0
4             NaN                   NaN
5             NaN                   NaN
6             NaN                   NaN
7             NaN                   NaN
8             NaN                   NaN
9          635000              635000.0
10            NaN                   NaN
11         505000              505000.0
12         305000              305000.0
13         385000              385000.0
14         705000              705000.0
15            NaN                   NaN
16            NaN                   NaN
17            NaN                   NaN
18            NaN                   NaN
19            NaN                   NaN

In [19]:
df['loan_to_value_ratio_clean'] = pd.to_numeric(
    df['loan_to_value_ratio'],
    errors='coerce'
)

In [20]:
df[['loan_to_value_ratio', 'loan_to_value_ratio_clean']].head(20)

   loan_to_value_ratio  loan_to_value_ratio_clean
0               39.394                     39.394
1                  NaN                        NaN
2                  NaN                        NaN
3              101.607                    101.607
4                  NaN                        NaN
5                  NaN                        NaN
6                  NaN                        NaN
7                  NaN                        NaN
8                  NaN                        NaN
9                   95                     95.000
10                 NaN                        NaN
11                96.5                     96.500
12              83.282                     83.282
13                96.5                     96.500
14                  69                     69.000
15                 NaN                        NaN
16                 NaN                        NaN
17                 NaN                        NaN
18                 NaN                        NaN
19                 NaN                        NaN

In [21]:
df['property_value_clean'] = pd.to_numeric(
    df['property_value'],
    errors='coerce'
)

In [22]:
df['loan_to_value_ratio_clean'] = pd.to_numeric(
    df['loan_to_value_ratio'],
    errors='coerce'
)

In [23]:
df[['property_value', 'property_value_clean',
    'loan_to_value_ratio', 'loan_to_value_ratio_clean']].head(20)

,property_value,property_value_clean,loan_to_value_ratio,loan_to_value_ratio_clean
0,335000,335000.0,39.394,39.394
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,705000,705000.0,101.607,101.607
4,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN
9,635000,635000.0,95,95.000
10,NaN,NaN,NaN,NaN
11,505000,505000.0,96.5,96.500
12,305000,305000.0,83.282,83.282
13,385000,385000.0,96.5,96.500
14,705000,705000.0,69,69.000
15,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN

In [24]:
# ==========================================
# CLEAN FINANCIAL / NUMERIC COLUMNS
# ==========================================

# 1. Property Value
# Convert "Exempt" and other non-numeric values to NaN
df['property_value_clean'] = pd.to_numeric(
    df['property_value'].replace('Exempt', pd.NA),
    errors='coerce'
)


# 2. Loan-to-Value Ratio
# Convert "Exempt" and other non-numeric values to NaN
df['loan_to_value_ratio_clean'] = pd.to_numeric(
    df['loan_to_value_ratio'].replace('Exempt', pd.NA),
    errors='coerce'
)


# 3. Debt-to-Income Ratio
# Keep the original DTI categories/ranges.
# Convert exact numeric DTI values to numbers.
df['debt_to_income_ratio_clean'] = pd.to_numeric(
    df['debt_to_income_ratio'].replace('Exempt', pd.NA),
    errors='coerce'
)


# ==========================================
# CHECK THE RESULT
# ==========================================

print("PROPERTY VALUE")
print(df[['property_value', 'property_value_clean']].head(20))

print("\nLOAN TO VALUE RATIO")
print(df[['loan_to_value_ratio', 'loan_to_value_ratio_clean']].head(20))

print("\nDEBT TO INCOME RATIO")
print(df[['debt_to_income_ratio', 'debt_to_income_ratio_clean']].head(20))


# ==========================================
# CHECK DATA TYPES
# ==========================================

print("\nDATA TYPES")
print(
    df[
        [
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'debt_to_income_ratio_clean'
        ]
    ].dtypes
)

PROPERTY VALUE
   property_value  property_value_clean
0          335000              335000.0
1             NaN                   NaN
2             NaN                   NaN
3          705000              705000.0
4             NaN                   NaN
5             NaN                   NaN
6             NaN                   NaN
7             NaN                   NaN
8             NaN                   NaN
9          635000              635000.0
10            NaN                   NaN
11         505000              505000.0
12         305000              305000.0
13         385000              385000.0
14         705000              705000.0
15            NaN                   NaN
16            NaN                   NaN
17            NaN                   NaN
18            NaN                   NaN
19            NaN                   NaN

LOAN TO VALUE RATIO
   loan_to_value_ratio  loan_to_value_ratio_clean
0               39.394                     39.394
1                  NaN                        NaN
2                  NaN                        NaN
3              101.607                    101.607
4                  NaN                        NaN
5                  NaN                        NaN
6                  NaN                        NaN
7                  NaN                        NaN
8                  NaN                        NaN
9                   95                     95.000
10                 NaN                        NaN
11                96.5                     96.500
12              83.282                     83.282
13                96.5                     96.500
14                  69                     69.000
15                 NaN                        NaN
16                 NaN                        NaN
17                 NaN                        NaN
18                 NaN                        NaN
19                 NaN                        NaN

DEBT TO INCOME RATIO
   debt_to_income_ratio  debt_to_income_ratio_clean
0              20%-<30%                         NaN
1                   NaN                         NaN
2                   NaN                         NaN
3                    43                        43.0
4                   NaN                         NaN
5                   NaN                         NaN
6                   NaN                         NaN
7                   NaN                         NaN
8                   NaN                         NaN
9                    49                        49.0
10                  NaN                         NaN
11                   44                        44.0
12                   47                        47.0
13                   48                        48.0
14                   43                        43.0
15                  NaN                         NaN
16                  NaN                         NaN
17                  NaN                         NaN
18                  NaN                         NaN
19                  NaN                         NaN

DATA TYPES
property_value_clean          float64
loan_to_value_ratio_clean     float64
debt_to_income_ratio_clean    float64
dtype: object

In [25]:
# ==========================================
# INVALID VALUE CHECK
# ==========================================

print("PROPERTY VALUE")
print("Negative values:", (df['property_value_clean'] < 0).sum())
print("Zero values:", (df['property_value_clean'] == 0).sum())

print("\nLOAN AMOUNT")
print("Negative values:", (df['loan_amount'] < 0).sum())
print("Zero values:", (df['loan_amount'] == 0).sum())

print("\nINCOME")
print("Negative values:", (df['income'] < 0).sum())
print("Zero values:", (df['income'] == 0).sum())

print("\nLOAN TO VALUE RATIO")
print("Below 0:", (df['loan_to_value_ratio_clean'] < 0).sum())
print("Above 100:", (df['loan_to_value_ratio_clean'] > 100).sum())

print("\nDEBT TO INCOME RATIO")
print("Negative values:", (df['debt_to_income_ratio_clean'] < 0).sum())
print("Above 100:", (df['debt_to_income_ratio_clean'] > 100).sum())

PROPERTY VALUE
Negative values: 0
Zero values: 0

LOAN AMOUNT
Negative values: 0
Zero values: 0

INCOME
Negative values: 648
Zero values: 10424

LOAN TO VALUE RATIO
Below 0: 0
Above 100: 22241

DEBT TO INCOME RATIO
Negative values: 0
Above 100: 0

In [26]:
# CATEGORICAL DATA QUALITY CHECK

categorical_columns = [
    'state_code',
    'derived_loan_product_type',
    'derived_dwelling_category',
    'derived_ethnicity',
    'derived_race',
    'derived_sex',
    'action_taken',
    'purchaser_type',
    'preapproval',
    'loan_type',
    'loan_purpose',
    'lien_status',
    'reverse_mortgage',
    'open_end_line_of_credit',
    'business_or_commercial_purpose',
    'construction_method',
    'occupancy_type',
    'manufactured_home_secured_property_type',
    'manufactured_home_land_property_interest',
    'total_units',
    'applicant_credit_score_type',
    'co_applicant_credit_score_type',
    'applicant_sex',
    'co_applicant_sex',
    'applicant_age',
    'co_applicant_age',
    'applicant_age_above_62',
    'co_applicant_age_above_62',
    'submission_of_application',
    'initially_payable_to_institution',
    'aus-1',
    'denial_reason-1'
]

for column in categorical_columns:
    print("\n" + "=" * 60)
    print(column)
    print("=" * 60)
    print(df[column].value_counts(dropna=False).head(20))

============================================================
state_code
============================================================
state_code
TX    710206
Name: count, dtype: int64

============================================================
derived_loan_product_type
============================================================
derived_loan_product_type
Conventional:First Lien          427265
FHA:First Lien                   117720
Conventional:Subordinate Lien    100952
VA:First Lien                     61513
FSA/RHS:First Lien                 1835
FSA/RHS:Subordinate Lien            886
FHA:Subordinate Lien                 35
Name: count, dtype: int64

============================================================
derived_dwelling_category
============================================================
derived_dwelling_category
Single Family (1-4 Units):Site-Built      637551
Single Family (1-4 Units):Manufactured     70671
Multifamily:Site-Built                      1906
Multifamily:Manufactured                      78
Name: count, dtype: int64

============================================================
derived_ethnicity
============================================================
derived_ethnicity
Not Hispanic or Latino     377771
Hispanic or Latino         192671
Ethnicity Not Available    107622
Joint                       31795
Free Form Text Only           347
Name: count, dtype: int64

============================================================
derived_race
============================================================
derived_race
White                                        421278
Race Not Available                           132375
Black or African American                     64014
Asian                                         63954
Joint                                         17428
American Indian or Alaska Native               7040
2 or more minority races                       2117
Native Hawaiian or Other Pacific Islander      1694
Free Form Text Only                             306
Name: count, dtype: int64

============================================================
derived_sex
============================================================
derived_sex
Joint                254465
Male                 252759
Female               147274
Sex Not Available     55708
Name: count, dtype: int64

============================================================
action_taken
============================================================
action_taken
1    494656
3    184473
2     31077
Name: count, dtype: int64

============================================================
purchaser_type
============================================================
purchaser_type
0     363954
71     89371
1      64982
2      61872
3      54036
9      21777
6      21161
8      17091
5      10715
72      5243
4          4
Name: count, dtype: int64

============================================================
preapproval
============================================================
preapproval
2    694141
1     16065
Name: count, dtype: int64

============================================================
loan_type
============================================================
loan_type
1    528217
2    117755
3     61513
4      2721
Name: count, dtype: int64

============================================================
loan_purpose
============================================================
loan_purpose
1     464738
32     79079
31     62967
4      60246
2      42841
5        335
Name: count, dtype: int64

============================================================
lien_status
============================================================
lien_status
1    608333
2    101873
Name: count, dtype: int64

============================================================
reverse_mortgage
============================================================
reverse_mortgage
2       690898
1111     16796
1         2512
Name: count, dtype: int64

============================================================
open_end_line_of_credit
============================================================

KeyError: 'open_end_line_of_credit'

In [27]:
[column for column in df.columns if 'open' in column.lower()]

['open-end_line_of_credit']

In [28]:
# Get all categorical/text columns automatically
categorical_columns = df.select_dtypes(include=['object', 'string']).columns

print("Number of categorical/text columns:", len(categorical_columns))

for column in categorical_columns:
    print("\n" + "=" * 60)
    print(column)
    print("=" * 60)
    print(df[column].value_counts(dropna=False).head(20))

Number of categorical/text columns: 27

============================================================
lei
============================================================
lei
549300HW662MN1WU8550    40503
549300FGXN1K3HLB1R50    31476
549300XQVJ1XBNFA5536    24542
5493001SXWZ4OFP8Z903    21137
549300H3IZO24NSOO931    18457
B4TYDEB6GKMZO031MB27    15735
X05BVSK68TQ7YTOSNR22    14839
549300AG64NHILB7ZP05    13656
G5AHTAP80NWA3Q8RDC78    13087
549300CB67L6KPJLHE19    12530
7H6GLXDRUGQFU57RNE97    12061
549300GKFNPRWNS0GF29    11201
5493000YNV8IX4VD3X12    11026
549300LU6Y2TXG48QY48    10011
549300DD5QQUHO6PCH70     8369
549300MGPZBLQDIL7538     7901
5493003GQDUH26DNNH17     7872
549300AQ3T62GXDU7D76     7582
549300121SF0K2LN2804     7550
RVDPPPGHCGZ40J4VQ731     6794
Name: count, dtype: int64

============================================================
state_code
============================================================
state_code
TX    710206
Name: count, dtype: int64

============================================================
conforming_loan_limit
============================================================
conforming_loan_limit
C      690133
NC      18089
NaN      1984
Name: count, dtype: int64

============================================================
derived_loan_product_type
============================================================
derived_loan_product_type
Conventional:First Lien          427265
FHA:First Lien                   117720
Conventional:Subordinate Lien    100952
VA:First Lien                     61513
FSA/RHS:First Lien                 1835
FSA/RHS:Subordinate Lien            886
FHA:Subordinate Lien                 35
Name: count, dtype: int64

============================================================
derived_dwelling_category
============================================================
derived_dwelling_category
Single Family (1-4 Units):Site-Built      637551
Single Family (1-4 Units):Manufactured     70671
Multifamily:Site-Built                      1906
Multifamily:Manufactured                      78
Name: count, dtype: int64

============================================================
derived_ethnicity
============================================================
derived_ethnicity
Not Hispanic or Latino     377771
Hispanic or Latino         192671
Ethnicity Not Available    107622
Joint                       31795
Free Form Text Only           347
Name: count, dtype: int64

============================================================
derived_race
============================================================
derived_race
White                                        421278
Race Not Available                           132375
Black or African American                     64014
Asian                                         63954
Joint                                         17428
American Indian or Alaska Native               7040
2 or more minority races                       2117
Native Hawaiian or Other Pacific Islander      1694
Free Form Text Only                             306
Name: count, dtype: int64

============================================================
derived_sex
============================================================
derived_sex
Joint                254465
Male                 252759
Female               147274
Sex Not Available     55708
Name: count, dtype: int64

============================================================
loan_to_value_ratio
============================================================
loan_to_value_ratio
NaN       81468
80        38014
96.5      37780
96.5      30758
80.0      29607
100       22208
95        21051
95.0      17401
Exempt    16714
100.0     16308
75        13802
90        12896
75.0      10237
90.0       9456
97.0       7023
70         6638
97         5484
70.0       5471
85         4027
60         3047
Name: count, dtype: int64

============================================================
interest_rate
============================================================
interest_rate
NaN       183431
6.625      19230
Exempt     16812
6.5        13665
6.25       13275
6.625      13230
6.125      12081
7.125      12034
6.875      12021
6.75       11638
5.75       10207
6.99       10115
6.99        9953
6.5         9587
6.375       9044
6.125       8326
6.875       7913
6.75        7523
7.125       7507
6.25        7474
Name: count, dtype: int64

============================================================
rate_spread
============================================================
rate_spread
NaN       229201
Exempt     16346
0           2853
0.954        327
0.956        314
0.955        299
-0.18        284
-0.14        271
-0.15        268
0.36         259
0.32         249
-1.19        248
0.35         243
-0.26        242
0.22         240
0.1          235
0.34         232
0.15         231
-0.16        223
-0.11        223
Name: count, dtype: int64

============================================================
total_loan_costs
============================================================
total_loan_costs
NaN       288541
Exempt     16759
0           9762
0.0         8018
34           763
158.4        588
500          456
795          305
500.0        265
5915         232
307          222
158.4        208
311.5        190
300          186
695.0        154
635          144
90           136
180          120
275          113
800          109
Name: count, dtype: int64

============================================================
total_points_and_fees
============================================================
total_points_and_fees
NaN       679709
Exempt     16759
0           3151
3914.0      1479
4500.0       461
3914         389
3730         221
4500         202
2400         191
499          157
799           93
3730.0        89
97            80
1350          54
400           35
2240          32
1096          30
113.75        28
1500          25
1191          22
Name: count, dtype: int64

============================================================
origination_charges
============================================================
origination_charges
NaN       285353
0          46872
0.0        36777
Exempt     16811
1775.0      2008
1195.0      1769
1550.0      1653
925         1499
1125        1372
500         1327
1515        1305
1550        1201
1395        1167
1775        1151
395         1150
1445.0      1059
1380         981
1095.0       910
1495         848
300          843
Name: count, dtype: int64

============================================================
discount_points
============================================================
discount_points
NaN       450074
Exempt     16811
1500.0       131
1000.0       124
750.0        116
1500         112
3000.0       104
1000          96
2000.0        96
2000          95
3000          93
500           90
2500          89
750           87
2250.0        87
4500          86
2250          79
1250.0        79
3750          74
4000          70
Name: count, dtype: int64

============================================================
lender_credits
============================================================
lender_credits
NaN       559137
Exempt     16811
50          1273
25          1070
1000.0      1023
500          904
50.0         878
150          837
100          823
500.0        823
3000         768
1000         763
100.0        755
25.0         645
200          596
150.0        596
75           537
125          508
10           501
6000         492
Name: count, dtype: int64

============================================================
loan_term
============================================================
loan_term
360       276035
360.0     213371
240        29496
300        27447
180        24693
300.0      22084
Exempt     16578
180.0      15601
240.0      14136
NaN        12464
120         9941
120.0       5634
480         4026
1           3954
480.0       3329
276.0       2940
60          2553
372         2313
36          2291
12.0        2164
Name: count, dtype: int64

============================================================
prepayment_penalty_term
============================================================
prepayment_penalty_term
NaN       692297
Exempt     16812
2            226
12           195
36           188
36.0         103
60            93
0             78
24            63
12.0          57
24.0          31
60.0          27
360           15
1              7
48             7
48.0           2
6              1
84.0           1
180            1
240            1
Name: count, dtype: int64

============================================================
intro_rate_period
============================================================
intro_rate_period
NaN       618770
1          21152
1.0        19008
Exempt     16812
60          4745
12.0        3898
12          3721
84          3002
6.0         2976
3           2582
6           2263
60.0        1684
120         1622
84.0        1430
2           1173
36          1080
180          616
36.0         575
120.0        463
72           417
Name: count, dtype: int64

============================================================
property_value
============================================================
property_value
NaN         27186
Exempt      16710
285000      10451
305000      10440
255000      10306
295000      10137
275000      10074
265000      10045
325000       9566
315000       9496
355000       8826
245000       8792
305000.0     8713
235000       8590
335000       8493
255000.0     8309
225000       8220
275000.0     8217
345000       8182
285000.0     8055
Name: count, dtype: int64

============================================================
total_units
============================================================
total_units
1          553187
1          146371
2            5190
4            1665
May-24        863
2             784
3             724
>149          565
4             228
50-99         215
25-49         187
100-149       154
3              73
Name: count, dtype: int64

============================================================
multifamily_affordable_units
============================================================
multifamily_affordable_units
NaN       692100
Exempt     16810
0            740
0.0          365
100          111
100.0         24
50.0           5
50             5
90             4
51             3
10.0           2
75.0           2
35.0           2
43.0           2
8.0            2
63             2
96             1
85             1
4              1
54.0           1
Name: count, dtype: int64

============================================================
debt_to_income_ratio
============================================================
debt_to_income_ratio
50%-60%     83713
30%-<36%    83270
20%-<30%    76278
>60%        54057
NaN         53332
<20%        33308
49          31453
44          25959
42          24575
43          23358
48          22480
41          22236
47          22077
45          21436
40          20807
46          20735
39          20353
38          18942
37          17910
36          17117
Name: count, dtype: int64

============================================================
applicant_age
============================================================
applicant_age
35-44    189717
25-34    168089
45-54    146177
55-64     94572
65-74     47807
<25       30643
>74       17365
8888      15836
Name: count, dtype: int64

============================================================
co-applicant_age
============================================================
co-applicant_age
9999     407318
35-44     77994
25-34     77090
45-54     58709
55-64     40056
65-74     22090
<25       14684
>74        7115
8888       5150
Name: count, dtype: int64

============================================================
applicant_age_above_62
============================================================
applicant_age_above_62
No     605984
Yes     88386
NaN     15836
Name: count, dtype: int64

============================================================
co-applicant_age_above_62
============================================================
co-applicant_age_above_62
NaN    412468
No     258094
Yes     39644
Name: count, dtype: int64

In [29]:
# Inspect the actual values and Python data types in total_units

print("Unique values:")
print(df['total_units'].unique())

print("\nUnderlying Python data types:")
print(df['total_units'].map(type).value_counts())

print("\nValues containing 'May':")
print(df.loc[df['total_units'].astype(str).str.contains('May', case=False, na=False),
            'total_units'].value_counts(dropna=False))

Unique values:
['1' '2' '4' '>149' '3' 'May-24' '50-99' '100-149' '25-49' 1 2 4 3]

Underlying Python data types:
total_units
<class 'str'>    562750
<class 'int'>    147456
Name: count, dtype: int64

Values containing 'May':
total_units
May-24    863
Name: count, dtype: int64

In [30]:
df[df['total_units'] == 'May-24'][[
    'total_units',
    'derived_dwelling_category',
    'derived_loan_product_type',
    'loan_amount',
    'property_value'
]].head(20)

,total_units,derived_dwelling_category,derived_loan_product_type,loan_amount,property_value
3371,May-24,Multifamily:Site-Built,Conventional:First Lien,755000.0,1765000
3372,May-24,Multifamily:Site-Built,Conventional:First Lien,50000000.0,100005000
8619,May-24,Multifamily:Site-Built,Conventional:First Lien,3255000.0,5005000.0
8625,May-24,Multifamily:Site-Built,Conventional:First Lien,1905000.0,2505000.0
8627,May-24,Multifamily:Site-Built,Conventional:First Lien,425000.0,1285000.0
8659,May-24,Multifamily:Site-Built,Conventional:First Lien,1305000.0,3845000.0
8665,May-24,Multifamily:Site-Built,Conventional:First Lien,1205000.0,1705000.0
8672,May-24,Multifamily:Site-Built,Conventional:First Lien,205000.0,465000.0
8719,May-24,Multifamily:Site-Built,Conventional:First Lien,7605000.0,9305000.0
20693,May-24,Multifamily:Site-Built,Conventional:First Lien,7195000.0,1255000
20696,May-24,Multifamily:Site-Built,Conventional:First Lien,955000.0,1205000
22943,May-24,Multifamily:Site-Built,Conventional:First Lien,1735000.0,2485000
23148,May-24,Multifamily:Site-Built,Conventional:Subordinate Lien,105000.0,Exempt
23170,May-24,Multifamily:Manufactured,Conventional:First Lien,1005000.0,Exempt
23193,May-24,Multifamily:Site-Built,Conventional:First Lien,455000.0,Exempt
23412,May-24,Multifamily:Site-Built,Conventional:First Lien,505000.0,Exempt
23426,May-24,Multifamily:Site-Built,Conventional:First Lien,845000.0,Exempt
23428,May-24,Multifamily:Site-Built,Conventional:First Lien,1125000.0,Exempt
23431,May-24,Multifamily:Site-Built,Conventional:First Lien,225000.0,Exempt
23433,May-24,Multifamily:Site-Built,Conventional:First Lien,1805000.0,Exempt

In [31]:
# Create a cleaned copy of total_units
df['total_units_clean'] = df['total_units'].astype(str).str.strip()

# Standardize the Excel-converted value
df['total_units_clean'] = df['total_units_clean'].replace({
    'May-24': '5-24'
})

# Check the cleaned categories
print("Unique values after cleaning:")
print(df['total_units_clean'].unique())

# Check for any unexpected categories
valid_total_units = {
    '1', '2', '3', '4',
    '5-24',
    '25-49',
    '50-99',
    '100-149',
    '>149'
}

unexpected_values = sorted(
    set(df['total_units_clean'].dropna()) - valid_total_units
)

print("\nUnexpected values:")
print(unexpected_values)

# Compare counts before and after
print("\nOriginal total_units counts:")
print(df['total_units'].value_counts(dropna=False))

print("\nCleaned total_units counts:")
print(df['total_units_clean'].value_counts(dropna=False))

Unique values after cleaning:
<StringArray>
['1', '2', '4', '>149', '3', '5-24', '50-99', '100-149', '25-49']
Length: 9, dtype: str

Unexpected values:
[]

Original total_units counts:
total_units
1          553187
1          146371
2            5190
4            1665
May-24        863
2             784
3             724
>149          565
4             228
50-99         215
25-49         187
100-149       154
3              73
Name: count, dtype: int64

Cleaned total_units counts:
total_units_clean
1          699558
2            5974
4            1893
5-24          863
3             797
>149          565
50-99         215
25-49         187
100-149       154
Name: count, dtype: int64

In [32]:
# Get all text/categorical columns
categorical_columns = df.select_dtypes(include=['object', 'string']).columns

print("Number of categorical/text columns:", len(categorical_columns))
print("\nCategorical/Text columns:")
print(list(categorical_columns))


# Inspect unique values and their counts
for column in categorical_columns:

    # Skip identifier column for category-quality inspection
    if column == 'lei':
        continue

    print("\n" + "=" * 70)
    print(column)
    print("=" * 70)

    print("Number of unique values:", df[column].nunique(dropna=True))

    print("\nTop values:")
    print(df[column].value_counts(dropna=False).head(15))

Number of categorical/text columns: 28

Categorical/Text columns:
['lei', 'state_code', 'conforming_loan_limit', 'derived_loan_product_type', 'derived_dwelling_category', 'derived_ethnicity', 'derived_race', 'derived_sex', 'loan_to_value_ratio', 'interest_rate', 'rate_spread', 'total_loan_costs', 'total_points_and_fees', 'origination_charges', 'discount_points', 'lender_credits', 'loan_term', 'prepayment_penalty_term', 'intro_rate_period', 'property_value', 'total_units', 'multifamily_affordable_units', 'debt_to_income_ratio', 'applicant_age', 'co-applicant_age', 'applicant_age_above_62', 'co-applicant_age_above_62', 'total_units_clean']

======================================================================
state_code
======================================================================
Number of unique values: 1

Top values:
state_code
TX    710206
Name: count, dtype: int64

======================================================================
conforming_loan_limit
======================================================================
Number of unique values: 2

Top values:
conforming_loan_limit
C      690133
NC      18089
NaN      1984
Name: count, dtype: int64

======================================================================
derived_loan_product_type
======================================================================
Number of unique values: 7

Top values:
derived_loan_product_type
Conventional:First Lien          427265
FHA:First Lien                   117720
Conventional:Subordinate Lien    100952
VA:First Lien                     61513
FSA/RHS:First Lien                 1835
FSA/RHS:Subordinate Lien            886
FHA:Subordinate Lien                 35
Name: count, dtype: int64

======================================================================
derived_dwelling_category
======================================================================
Number of unique values: 4

Top values:
derived_dwelling_category
Single Family (1-4 Units):Site-Built      637551
Single Family (1-4 Units):Manufactured     70671
Multifamily:Site-Built                      1906
Multifamily:Manufactured                      78
Name: count, dtype: int64

======================================================================
derived_ethnicity
======================================================================
Number of unique values: 5

Top values:
derived_ethnicity
Not Hispanic or Latino     377771
Hispanic or Latino         192671
Ethnicity Not Available    107622
Joint                       31795
Free Form Text Only           347
Name: count, dtype: int64

======================================================================
derived_race
======================================================================
Number of unique values: 9

Top values:
derived_race
White                                        421278
Race Not Available                           132375
Black or African American                     64014
Asian                                         63954
Joint                                         17428
American Indian or Alaska Native               7040
2 or more minority races                       2117
Native Hawaiian or Other Pacific Islander      1694
Free Form Text Only                             306
Name: count, dtype: int64

======================================================================
derived_sex
======================================================================
Number of unique values: 4

Top values:
derived_sex
Joint                254465
Male                 252759
Female               147274
Sex Not Available     55708
Name: count, dtype: int64

======================================================================
loan_to_value_ratio
======================================================================
Number of unique values: 99735

Top values:
loan_to_value_ratio
NaN       81468
80        38014
96.5      37780
96.5      30758
80.0      29607
100       22208
95        21051
95.0      17401
Exempt    16714
100.0     16308
75        13802
90        12896
75.0      10237
90.0       9456
97.0       7023
Name: count, dtype: int64

======================================================================
interest_rate
======================================================================
Number of unique values: 4832

Top values:
interest_rate
NaN       183431
6.625      19230
Exempt     16812
6.5        13665
6.25       13275
6.625      13230
6.125      12081
7.125      12034
6.875      12021
6.75       11638
5.75       10207
6.99       10115
6.99        9953
6.5         9587
6.375       9044
Name: count, dtype: int64

======================================================================
rate_spread
======================================================================
Number of unique values: 28377

Top values:
rate_spread
NaN       229201
Exempt     16346
0           2853
0.954        327
0.956        314
0.955        299
-0.18        284
-0.14        271
-0.15        268
0.36         259
0.32         249
-1.19        248
0.35         243
-0.26        242
0.22         240
Name: count, dtype: int64

======================================================================
total_loan_costs
======================================================================
Number of unique values: 345740

Top values:
total_loan_costs
NaN       288541
Exempt     16759
0           9762
0.0         8018
34           763
158.4        588
500          456
795          305
500.0        265
5915         232
307          222
158.4        208
311.5        190
300          186
695.0        154
Name: count, dtype: int64

======================================================================
total_points_and_fees
======================================================================
Number of unique values: 5976

Top values:
total_points_and_fees
NaN       679709
Exempt     16759
0           3151
3914.0      1479
4500.0       461
3914         389
3730         221
4500         202
2400         191
499          157
799           93
3730.0        89
97            80
1350          54
400           35
Name: count, dtype: int64

======================================================================
origination_charges
======================================================================
Number of unique values: 187567

Top values:
origination_charges
NaN       285353
0          46872
0.0        36777
Exempt     16811
1775.0      2008
1195.0      1769
1550.0      1653
925         1499
1125        1372
500         1327
1515        1305
1550        1201
1395        1167
1775        1151
395         1150
Name: count, dtype: int64

======================================================================
discount_points
======================================================================
Number of unique values: 185584

Top values:
discount_points
NaN       450074
Exempt     16811
1500.0       131
1000.0       124
750.0        116
1500         112
3000.0       104
1000          96
2000.0        96
2000          95
3000          93
500           90
2500          89
750           87
2250.0        87
Name: count, dtype: int64

======================================================================
lender_credits
======================================================================
Number of unique values: 64654

Top values:
lender_credits
NaN       559137
Exempt     16811
50          1273
25          1070
1000.0      1023
500          904
50.0         878
150          837
100          823
500.0        823
3000         768
1000         763
100.0        755
25.0         645
200          596
Name: count, dtype: int64

======================================================================
loan_term
======================================================================
Number of unique values: 652

Top values:
loan_term
360       276035
360.0     213371
240        29496
300        27447
180        24693
300.0      22084
Exempt     16578
180.0      15601
240.0      14136
NaN        12464
120         9941
120.0       5634
480         4026
1           3954
480.0       3329
Name: count, dtype: int64

======================================================================
prepayment_penalty_term
======================================================================
Number of unique values: 20

Top values:
prepayment_penalty_term
NaN       692297
Exempt     16812
2            226
12           195
36           188
36.0         103
60            93
0             78
24            63
12.0          57
24.0          31
60.0          27
360           15
1              7
48             7
Name: count, dtype: int64

======================================================================
intro_rate_period
======================================================================
Number of unique values: 114

Top values:
intro_rate_period
NaN       618770
1          21152
1.0        19008
Exempt     16812
60          4745
12.0        3898
12          3721
84          3002
6.0         2976
3           2582
6           2263
60.0        1684
120         1622
84.0        1430
2           1173
Name: count, dtype: int64

======================================================================
property_value
======================================================================
Number of unique values: 1715

Top values:
property_value
NaN         27186
Exempt      16710
285000      10451
305000      10440
255000      10306
295000      10137
275000      10074
265000      10045
325000       9566
315000       9496
355000       8826
245000       8792
305000.0     8713
235000       8590
335000       8493
Name: count, dtype: int64

======================================================================
total_units
======================================================================
Number of unique values: 13

Top values:
total_units
1          553187
1          146371
2            5190
4            1665
May-24        863
2             784
3             724
>149          565
4             228
50-99         215
25-49         187
100-149       154
3              73
Name: count, dtype: int64

======================================================================
multifamily_affordable_units
======================================================================
Number of unique values: 42

Top values:
multifamily_affordable_units
NaN       692100
Exempt     16810
0            740
0.0          365
100          111
100.0         24
50.0           5
50             5
90             4
51             3
10.0           2
75.0           2
35.0           2
43.0           2
8.0            2
Name: count, dtype: int64

======================================================================
debt_to_income_ratio
======================================================================
Number of unique values: 20

Top values:
debt_to_income_ratio
50%-60%     83713
30%-<36%    83270
20%-<30%    76278
>60%        54057
NaN         53332
<20%        33308
49          31453
44          25959
42          24575
43          23358
48          22480
41          22236
47          22077
45          21436
40          20807
Name: count, dtype: int64

======================================================================
applicant_age
======================================================================
Number of unique values: 8

Top values:
applicant_age
35-44    189717
25-34    168089
45-54    146177
55-64     94572
65-74     47807
<25       30643
>74       17365
8888      15836
Name: count, dtype: int64

======================================================================
co-applicant_age
======================================================================
Number of unique values: 9

Top values:
co-applicant_age
9999     407318
35-44     77994
25-34     77090
45-54     58709
55-64     40056
65-74     22090
<25       14684
>74        7115
8888       5150
Name: count, dtype: int64

======================================================================
applicant_age_above_62
======================================================================
Number of unique values: 2

Top values:
applicant_age_above_62
No     605984
Yes     88386
NaN     15836
Name: count, dtype: int64

======================================================================
co-applicant_age_above_62
======================================================================
Number of unique values: 2

Top values:
co-applicant_age_above_62
NaN    412468
No     258094
Yes     39644
Name: count, dtype: int64

======================================================================
total_units_clean
======================================================================
Number of unique values: 9

Top values:
total_units_clean
1          699558
2            5974
4            1893
5-24          863
3             797
>149          565
50-99         215
25-49         187
100-149       154
Name: count, dtype: int64

In [33]:
# ============================================================
# SPECIAL VALUE INVESTIGATION
# ============================================================

# 1. Find Exempt values
print("=" * 70)
print("EXEMPT VALUES")
print("=" * 70)

for column in df.columns:
    count = (df[column].astype(str).str.strip() == 'Exempt').sum()

    if count > 0:
        print(f"{column}: {count}")


# 2. Applicant age = 8888
print("\n" + "=" * 70)
print("APPLICANT AGE = 8888")
print("=" * 70)

applicant_8888 = df[
    df['applicant_age'].astype(str).str.strip() == '8888'
]

print("Number of records:", len(applicant_8888))

print(
    applicant_8888[
        ['applicant_age',
         'applicant_age_above_62',
         'loan_amount',
         'action_taken']
    ].head(20)
)


# 3. Co-applicant age = 9999
print("\n" + "=" * 70)
print("CO-APPLICANT AGE = 9999")
print("=" * 70)

coapplicant_9999 = df[
    df['co-applicant_age'].astype(str).str.strip() == '9999'
]

print("Number of records:", len(coapplicant_9999))

print(
    coapplicant_9999[
        ['co-applicant_age',
         'co-applicant_age_above_62',
         'applicant_age',
         'loan_amount',
         'action_taken']
    ].head(20)
)


# 4. Co-applicant age = 8888
print("\n" + "=" * 70)
print("CO-APPLICANT AGE = 8888")
print("=" * 70)

coapplicant_8888 = df[
    df['co-applicant_age'].astype(str).str.strip() == '8888'
]

print("Number of records:", len(coapplicant_8888))

print(
    coapplicant_8888[
        ['co-applicant_age',
         'co-applicant_age_above_62',
         'applicant_age',
         'loan_amount',
         'action_taken']
    ].head(20)
)


# 5. Complete DTI distribution
print("\n" + "=" * 70)
print("DEBT-TO-INCOME RATIO")
print("=" * 70)

print(
    df['debt_to_income_ratio']
    .value_counts(dropna=False)
)

======================================================================
EXEMPT VALUES
======================================================================
loan_to_value_ratio: 16714
interest_rate: 16812
rate_spread: 16346
total_loan_costs: 16759
total_points_and_fees: 16759
origination_charges: 16811
discount_points: 16811
lender_credits: 16811
loan_term: 16578
prepayment_penalty_term: 16812
intro_rate_period: 16812
property_value: 16710
multifamily_affordable_units: 16810
debt_to_income_ratio: 16810

======================================================================
APPLICANT AGE = 8888
======================================================================
Number of records: 15836
     applicant_age applicant_age_above_62  loan_amount  action_taken
3353          8888                    NaN     285000.0             1
3357          8888                    NaN     195000.0             3
3358          8888                    NaN     945000.0             1
3359          8888                    NaN     495000.0             1
3360          8888                    NaN     285000.0             1
3361          8888                    NaN     325000.0             1
3362          8888                    NaN     605000.0             1
3363          8888                    NaN     325000.0             1
3364          8888                    NaN     165000.0             1
3365          8888                    NaN   19100000.0             1
3366          8888                    NaN   46800000.0             1
3367          8888                    NaN     225000.0             1
3369          8888                    NaN      55000.0             1
3370          8888                    NaN     605000.0             1
3371          8888                    NaN     755000.0             1
3372          8888                    NaN   50000000.0             1
3373          8888                    NaN     425000.0             1
3374          8888                    NaN     155000.0             1
3375          8888                    NaN     165000.0             1
3376          8888                    NaN    2505000.0             1

======================================================================
CO-APPLICANT AGE = 9999
======================================================================
Number of records: 407318
   co-applicant_age co-applicant_age_above_62 applicant_age  loan_amount  \
0              9999                       NaN         25-34     135000.0
5              9999                       NaN         35-44     175000.0
6              9999                       NaN         25-34     255000.0
7              9999                       NaN         55-64     275000.0
8              9999                       NaN         45-54     475000.0
9              9999                       NaN         25-34     605000.0
10             9999                       NaN         35-44     225000.0
13             9999                       NaN         35-44     375000.0
14             9999                       NaN         55-64     485000.0
15             9999                       NaN         45-54     155000.0
18             9999                       NaN         25-34     265000.0
19             9999                       NaN         35-44     175000.0
20             9999                       NaN         55-64     355000.0
21             9999                       NaN         45-54     285000.0
22             9999                       NaN         35-44     225000.0
29             9999                       NaN         25-34     515000.0
31             9999                       NaN         45-54     235000.0
33             9999                       NaN         45-54     265000.0
34             9999                       NaN         35-44     345000.0
35             9999                       NaN         25-34     625000.0

    action_taken
0              1
5              3
6              2
7              1
8              2
9              1
10             1
13             1
14             1
15             2
18             1
19             1
20             2
21             1
22             1
29             1
31             1
33             1
34             3
35             1

======================================================================
CO-APPLICANT AGE = 8888
======================================================================
Number of records: 5150
      co-applicant_age co-applicant_age_above_62 applicant_age  loan_amount  \
3376              8888                       NaN          8888    2505000.0
3390              8888                       NaN          8888     305000.0
4332              8888                       NaN          8888   20500000.0
8661              8888                       NaN          8888    1005000.0
8701              8888                       NaN          8888    1005000.0
8782              8888                       NaN         65-74    1605000.0
8846              8888                       NaN         45-54    2005000.0
8861              8888                       NaN         25-34    5005000.0
8896              8888                       NaN         35-44    1535000.0
8904              8888                       NaN         35-44    2225000.0
8936              8888                       NaN         45-54    2055000.0
8937              8888                       NaN         45-54    3685000.0
20693             8888                       NaN          8888    7195000.0
20824             8888                       NaN          8888   22400000.0
20825             8888                       NaN          8888   38500000.0
20826             8888                       NaN          8888   42800000.0
20827             8888                       NaN          8888   40700000.0
20828             8888                       NaN          8888   31600000.0
20829             8888                       NaN          8888   50000000.0
20830             8888                       NaN          8888   39000000.0

       action_taken
3376              1
3390              1
4332              1
8661              3
8701              3
8782              1
8846              1
8861              1
8896              1
8904              1
8936              1
8937              1
20693             1
20824             1
20825             1
20826             1
20827             1
20828             1
20829             1
20830             1

======================================================================
DEBT-TO-INCOME RATIO
======================================================================
debt_to_income_ratio
50%-60%     83713
30%-<36%    83270
20%-<30%    76278
>60%        54057
NaN         53332
<20%        33308
49          31453
44          25959
42          24575
43          23358
48          22480
41          22236
47          22077
45          21436
40          20807
46          20735
39          20353
38          18942
37          17910
36          17117
Exempt      16810
Name: count, dtype: int64

In [34]:
# ============================================================
# CREATE CLEAN NUMERIC HELPER COLUMNS
# ============================================================

numeric_columns = [
    'loan_to_value_ratio',
    'interest_rate',
    'rate_spread',
    'total_loan_costs',
    'total_points_and_fees',
    'origination_charges',
    'discount_points',
    'lender_credits',
    'loan_term',
    'prepayment_penalty_term',
    'intro_rate_period',
    'property_value',
    'multifamily_affordable_units'
]


for column in numeric_columns:

    clean_column = column + '_clean'

    df[clean_column] = pd.to_numeric(
        df[column],
        errors='coerce'
    )


# ------------------------------------------------------------
# Display the new numeric columns
# ------------------------------------------------------------

clean_columns = [
    column + '_clean'
    for column in numeric_columns
]

print("Clean numeric columns created:")
print(clean_columns)


# ------------------------------------------------------------
# Check their data types
# ------------------------------------------------------------

print("\nData types:")
print(df[clean_columns].dtypes)


# ------------------------------------------------------------
# Check how many values became missing
# ------------------------------------------------------------

print("\nMissing values after numeric conversion:")

for column in clean_columns:

    missing_count = df[column].isna().sum()

    print(f"{column}: {missing_count}")

Clean numeric columns created:
['loan_to_value_ratio_clean', 'interest_rate_clean', 'rate_spread_clean', 'total_loan_costs_clean', 'total_points_and_fees_clean', 'origination_charges_clean', 'discount_points_clean', 'lender_credits_clean', 'loan_term_clean', 'prepayment_penalty_term_clean', 'intro_rate_period_clean', 'property_value_clean', 'multifamily_affordable_units_clean']

Data types:
loan_to_value_ratio_clean             float64
interest_rate_clean                   float64
rate_spread_clean                     float64
total_loan_costs_clean                float64
total_points_and_fees_clean           float64
origination_charges_clean             float64
discount_points_clean                 float64
lender_credits_clean                  float64
loan_term_clean                       float64
prepayment_penalty_term_clean         float64
intro_rate_period_clean               float64
property_value_clean                  float64
multifamily_affordable_units_clean    float64
dtype: object

Missing values after numeric conversion:
loan_to_value_ratio_clean: 98182
interest_rate_clean: 200243
rate_spread_clean: 245547
total_loan_costs_clean: 305300
total_points_and_fees_clean: 696468
origination_charges_clean: 302164
discount_points_clean: 466885
lender_credits_clean: 575948
loan_term_clean: 29042
prepayment_penalty_term_clean: 709109
intro_rate_period_clean: 635582
property_value_clean: 43896
multifamily_affordable_units_clean: 708910

In [35]:
# ============================================================
# NEGATIVE INCOME INVESTIGATION
# ============================================================

print("=" * 70)
print("NEGATIVE INCOME INVESTIGATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Count negative income records
# ------------------------------------------------------------

negative_income = df[df['income'] < 0]

print("\nNumber of negative income records:")
print(len(negative_income))


# ------------------------------------------------------------
# 2. Basic statistics of negative income
# ------------------------------------------------------------

print("\nNegative income statistics:")

print(
    negative_income['income'].describe()
)


# ------------------------------------------------------------
# 3. Show sample records
# ------------------------------------------------------------

print("\nSample negative income records:")

print(
    negative_income[
        [
            'income',
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'debt_to_income_ratio',
            'derived_loan_product_type',
            'loan_purpose',
            'action_taken'
        ]
    ].head(20)
)


# ------------------------------------------------------------
# 4. Negative income by loan outcome
# ------------------------------------------------------------

print("\nNegative income by action taken:")

print(
    negative_income['action_taken']
    .value_counts()
    .sort_index()
)


# ------------------------------------------------------------
# 5. Negative income by loan product
# ------------------------------------------------------------

print("\nNegative income by loan product:")

print(
    negative_income['derived_loan_product_type']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 6. Negative income percentage
# ------------------------------------------------------------

negative_percentage = (
    len(negative_income) / len(df) * 100
)

print(
    f"\nNegative income percentage: "
    f"{negative_percentage:.2f}%"
)


# ------------------------------------------------------------
# 7. Check zero income
# ------------------------------------------------------------

zero_income = df[df['income'] == 0]

print("\nNumber of zero-income records:")
print(len(zero_income))

print(
    f"Zero income percentage: "
    f"{len(zero_income) / len(df) * 100:.2f}%"
)

======================================================================
NEGATIVE INCOME INVESTIGATION
======================================================================

Number of negative income records:
648

Negative income statistics:
count      648.000000
mean      -189.544753
std        583.755889
min     -10209.000000
25%       -158.250000
50%        -43.000000
75%        -13.000000
max         -1.000000
Name: income, dtype: float64

Sample negative income records:
       income  loan_amount  property_value_clean  loan_to_value_ratio_clean  \
778      -2.0     115000.0              105000.0                   100.0000
2457    -45.0     245000.0              245000.0                    99.4930
3313    -23.0      65000.0              295000.0                    20.3390
7485   -203.0    1265000.0             1575000.0                    80.0000
28597 -4737.0    2555000.0             4355000.0                    58.7170
29246   -75.0    1505000.0             2005000.0                    75.0000
36254    -3.0      55000.0              455000.0                    10.9890
37146    -6.0     275000.0              345000.0                    80.0000
37777  -257.0     235000.0              405000.0                    57.7500
41428    -3.0     245000.0              325000.0                    76.2420
41785    -1.0      55000.0              115000.0                    45.9130
42351   -80.0    1325000.0              995000.0                    65.0000
49337  -147.0     685000.0              855000.0                    80.0000
50103   -50.0     205000.0              305000.0                    66.9935
50289   -21.0     235000.0              375000.0                    63.4667
50618   -24.0     205000.0              265000.0                    77.3585
50919    -4.0     205000.0              295000.0                    70.0000
55868  -147.0     155000.0              575000.0                    26.0870
55918   -37.0      85000.0              305000.0                    51.3440
56128   -32.0     205000.0              485000.0                    79.9990

      debt_to_income_ratio      derived_loan_product_type  loan_purpose  \
778                   <20%                  VA:First Lien             4
2457                  <20%                  VA:First Lien            32
3313                  <20%        Conventional:First Lien             4
7485                  <20%        Conventional:First Lien             1
28597                 <20%        Conventional:First Lien            31
29246                 <20%        Conventional:First Lien             1
36254                 <20%        Conventional:First Lien             1
37146                 <20%        Conventional:First Lien            32
37777                 <20%        Conventional:First Lien            31
41428                 <20%                 FHA:First Lien            31
41785                 <20%        Conventional:First Lien            32
42351                 <20%        Conventional:First Lien            32
49337                 <20%        Conventional:First Lien             1
50103                 <20%        Conventional:First Lien             1
50289                 <20%        Conventional:First Lien            32
50618                 >60%        Conventional:First Lien             1
50919                 >60%        Conventional:First Lien            32
55868                 <20%        Conventional:First Lien             4
55918                 <20%  Conventional:Subordinate Lien            31
56128                 <20%  Conventional:Subordinate Lien             4

       action_taken
778               3
2457              3
3313              3
7485              3
28597             3
29246             3
36254             3
37146             3
37777             3
41428             3
41785             3
42351             3
49337             3
50103             1
50289             1
50618             2
50919             2
55868             3
55918             3
56128             3

Negative income by action taken:
action_taken
1     22
2      6
3    620
Name: count, dtype: int64

Negative income by loan product:
derived_loan_product_type
Conventional:First Lien          381
Conventional:Subordinate Lien    212
FHA:First Lien                    40
VA:First Lien                     15
Name: count, dtype: int64

Negative income percentage: 0.09%

Number of zero-income records:
10424
Zero income percentage: 1.47%

In [36]:
# ============================================================
# CREATE DATA QUALITY FLAGS
# ============================================================

# ------------------------------------------------------------
# 1. Negative income flag
# ------------------------------------------------------------

df['negative_income_flag'] = df['income'] < 0


# ------------------------------------------------------------
# 2. Zero income flag
# ------------------------------------------------------------

df['zero_income_flag'] = df['income'] == 0


# ------------------------------------------------------------
# 3. Check the flags
# ------------------------------------------------------------

print("=" * 70)
print("DATA QUALITY FLAGS")
print("=" * 70)

print("\nNegative income flag:")
print(
    df['negative_income_flag']
    .value_counts()
)


print("\nZero income flag:")
print(
    df['zero_income_flag']
    .value_counts()
)


# ------------------------------------------------------------
# 4. Verify counts
# ------------------------------------------------------------

print("\nNegative income records:")
print(
    df['negative_income_flag'].sum()
)

print("\nZero income records:")
print(
    df['zero_income_flag'].sum()
)

======================================================================
DATA QUALITY FLAGS
======================================================================

Negative income flag:
negative_income_flag
False    709558
True        648
Name: count, dtype: int64

Zero income flag:
zero_income_flag
False    699782
True      10424
Name: count, dtype: int64

Negative income records:
648

Zero income records:
10424

C:\Users\LENOVO GAMING\AppData\Local\Temp\ipykernel_24896\2979288870.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['negative_income_flag'] = df['income'] < 0
C:\Users\LENOVO GAMING\AppData\Local\Temp\ipykernel_24896\2979288870.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['zero_income_flag'] = df['income'] == 0

In [37]:
# ============================================================
# DEFRAGMENT DATAFRAME
# ============================================================

df = df.copy()

print("DataFrame defragmented successfully.")
print("Shape:", df.shape)

DataFrame defragmented successfully.
Shape: (710206, 116)

In [38]:
# ============================================================
# OUTLIER / EXTREME VALUE INVESTIGATION
# ============================================================

numeric_analysis_columns = [
    'loan_amount',
    'property_value_clean',
    'income',
    'loan_to_value_ratio_clean'
]


print("=" * 70)
print("OUTLIER / EXTREME VALUE INVESTIGATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Basic statistics
# ------------------------------------------------------------

print("\nBASIC STATISTICS")

print(
    df[numeric_analysis_columns].describe()
)


# ------------------------------------------------------------
# 2. Important percentiles
# ------------------------------------------------------------

print("\nPERCENTILE ANALYSIS")

percentiles = [
    0.01,
    0.05,
    0.25,
    0.50,
    0.75,
    0.95,
    0.99,
    0.995,
    0.999
]

print(
    df[numeric_analysis_columns]
    .quantile(percentiles)
)


# ------------------------------------------------------------
# 3. Top 20 loan amounts
# ------------------------------------------------------------

print("\nTOP 20 LOAN AMOUNTS")

print(
    df['loan_amount']
    .nlargest(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 4. Top 20 property values
# ------------------------------------------------------------

print("\nTOP 20 PROPERTY VALUES")

print(
    df['property_value_clean']
    .nlargest(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 5. Top 20 income values
# ------------------------------------------------------------

print("\nTOP 20 INCOME VALUES")

print(
    df['income']
    .nlargest(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 6. LTV above 100
# ------------------------------------------------------------

ltv_above_100 = df[
    df['loan_to_value_ratio_clean'] > 100
]

print("\nLTV ABOVE 100")

print(
    "Number of records:",
    len(ltv_above_100)
)

print(
    "Percentage:",
    f"{len(ltv_above_100) / len(df) * 100:.2f}%"
)


# ------------------------------------------------------------
# 7. Very high loan amounts
# ------------------------------------------------------------

loan_10m = df[
    df['loan_amount'] > 10_000_000
]

print("\nLOAN AMOUNT ABOVE $10 MILLION")

print(
    "Number of records:",
    len(loan_10m)
)

print(
    "Percentage:",
    f"{len(loan_10m) / len(df) * 100:.2f}%"
)


# ------------------------------------------------------------
# 8. Very high property values
# ------------------------------------------------------------

property_10m = df[
    df['property_value_clean'] > 10_000_000
]

print("\nPROPERTY VALUE ABOVE $10 MILLION")

print(
    "Number of records:",
    len(property_10m)
)

print(
    "Percentage:",
    f"{len(property_10m) / len(df) * 100:.2f}%"
)


# ------------------------------------------------------------
# 9. Very high income
# ------------------------------------------------------------

income_1m = df[
    df['income'] > 1_000_000
]

print("\nINCOME ABOVE $1 MILLION")

print(
    "Number of records:",
    len(income_1m)
)

print(
    "Percentage:",
    f"{len(income_1m) / len(df) * 100:.2f}%"
)

======================================================================
OUTLIER / EXTREME VALUE INVESTIGATION
======================================================================

BASIC STATISTICS
        loan_amount  property_value_clean        income  \
count  7.102060e+05          6.663100e+05  6.665100e+05
mean   3.135370e+05          4.777222e+05  1.569819e+02
std    2.111020e+06          4.924089e+06  2.872468e+03
min    5.000000e+03          5.000000e+03 -1.020900e+04
25%    1.250000e+05          2.450000e+05  7.100000e+01
50%    2.450000e+05          3.350000e+05  1.090000e+02
75%    3.550000e+05          4.950000e+05  1.680000e+02
max    6.450000e+08          1.838005e+09  1.620000e+06

       loan_to_value_ratio_clean
count               6.120240e+05
mean                2.480031e+02
std                 6.608274e+04
min                 1.000000e-03
25%                 6.861800e+01
50%                 8.000000e+01
75%                 9.650000e+01
max                 3.000000e+07

PERCENTILE ANALYSIS
       loan_amount  property_value_clean    income  loan_to_value_ratio_clean
0.010      15000.0               65000.0     0.000                  13.260230
0.050      45000.0              105000.0    34.000                  32.432000
0.250     125000.0              245000.0    71.000                  68.618000
0.500     245000.0              335000.0   109.000                  80.000000
0.750     355000.0              495000.0   168.000                  96.500000
0.950     655000.0              955000.0   356.000                 100.000000
0.990    1245000.0             1955000.0   786.000                 103.346310
0.995    1755000.0             2755000.0  1129.455                 110.176700
0.999    7355000.0             8905000.0  2922.491                 173.998275

TOP 20 LOAN AMOUNTS
645000000.0
581000000.0
550000000.0
344000000.0
344000000.0
344000000.0
344000000.0
344000000.0
344000000.0
344000000.0
344000000.0
344000000.0
262000000.0
260000000.0
238000000.0
211000000.0
186000000.0
178000000.0
163000000.0
148000000.0

TOP 20 PROPERTY VALUES
1838005000.0
1581075000.0
1576125000.0
1576125000.0
1050005000.0
 837155000.0
 734705000.0
 450005000.0
 447545000.0
 439705000.0
 387005000.0
 350885000.0
 350885000.0
 331805000.0
 313965000.0
 300005000.0
 300005000.0
 280005000.0
 240005000.0
 186895000.0

TOP 20 INCOME VALUES
1620000.0
1316000.0
1000000.0
 224000.0
 150000.0
 100408.0
  52000.0
  50000.0
  46080.0
  42741.0
  38117.0
  36293.0
  36028.0
  30923.0
  30793.0
  30793.0
  29674.0
  27887.0
  27887.0
  27887.0

LTV ABOVE 100
Number of records: 22241
Percentage: 3.13%

LOAN AMOUNT ABOVE $10 MILLION
Number of records: 593
Percentage: 0.08%

PROPERTY VALUE ABOVE $10 MILLION
Number of records: 615
Percentage: 0.09%

INCOME ABOVE $1 MILLION
Number of records: 2
Percentage: 0.00%

In [39]:
# ============================================================
# EXTREME VALUE RECORD INVESTIGATION
# ============================================================

print("=" * 70)
print("EXTREME VALUE RECORD INVESTIGATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Extremely high LTV
# ------------------------------------------------------------

print("\n1. LTV ABOVE 500")

ltv_extreme = df[
    df['loan_to_value_ratio_clean'] > 500
]

print("Number of records:", len(ltv_extreme))

print(
    ltv_extreme[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'income',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values('loan_to_value_ratio_clean', ascending=False)
    .head(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 2. Extremely high loan amounts
# ------------------------------------------------------------

print("\n2. LOAN AMOUNT ABOVE $10 MILLION")

loan_extreme = df[
    df['loan_amount'] > 10_000_000
]

print("Number of records:", len(loan_extreme))

print(
    loan_extreme[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'income',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values('loan_amount', ascending=False)
    .head(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 3. Extremely high property values
# ------------------------------------------------------------

print("\n3. PROPERTY VALUE ABOVE $10 MILLION")

property_extreme = df[
    df['property_value_clean'] > 10_000_000
]

print("Number of records:", len(property_extreme))

print(
    property_extreme[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'income',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values('property_value_clean', ascending=False)
    .head(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 4. Income above $1 million
# ------------------------------------------------------------

print("\n4. INCOME ABOVE $1 MILLION")

income_extreme = df[
    df['income'] > 1_000_000
]

print("Number of records:", len(income_extreme))

print(
    income_extreme[
        [
            'income',
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values('income', ascending=False)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 5. Summary by dwelling category
# ------------------------------------------------------------

print("\n5. EXTREME LOANS BY DWELLING CATEGORY")

print(
    loan_extreme['derived_dwelling_category']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 6. Summary by total units
# ------------------------------------------------------------

print("\n6. EXTREME LOANS BY TOTAL UNITS")

print(
    loan_extreme['total_units_clean']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 7. Extreme LTV by action taken
# ------------------------------------------------------------

print("\n7. EXTREME LTV BY ACTION TAKEN")

print(
    ltv_extreme['action_taken']
    .value_counts(dropna=False)
    .sort_index()
)

======================================================================
EXTREME VALUE RECORD INVESTIGATION
======================================================================

1. LTV ABOVE 500
Number of records: 188
 loan_amount  property_value_clean  loan_to_value_ratio_clean  income     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
    305000.0                5000.0               30000000.000    80.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
    295000.0              495000.0               29032800.000     NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            31             3
    255000.0              365000.0               25760000.000     NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
     65000.0                5000.0               16301700.000   135.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000    50.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000    50.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 303237.000   180.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    155000.0              215000.0                 159750.000     NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
     65000.0                5000.0                 113785.806   105.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 100000.000    24.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             1             3
    205000.0                5000.0                  97560.976    30.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     45000.0                5000.0                  95499.556    70.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     35000.0                5000.0                  92030.500    63.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    305000.0                5000.0                  85714.286   120.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
     35000.0                5000.0                  83743.273    98.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     65000.0                5000.0                  83422.479   165.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     65000.0                5000.0                  81493.636    83.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    155000.0                5000.0                  77439.714   400.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     45000.0                5000.0                  64452.537   760.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
    145000.0                5000.0                  62333.433    92.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3

2. LOAN AMOUNT ABOVE $10 MILLION
Number of records: 593
 loan_amount  property_value_clean  loan_to_value_ratio_clean  income derived_loan_product_type derived_dwelling_category total_units_clean  loan_purpose  action_taken
 645000000.0                   NaN                        NaN     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 581000000.0                   NaN                        NaN     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 550000000.0            92695000.0                      67.20     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             1
 344000000.0             3705000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0            38205000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            32             1
 344000000.0             2495000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0            53305000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built           100-149            32             1
 344000000.0            22705000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             50-99            32             1
 344000000.0             6605000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             50-99            32             1
 344000000.0             2825000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0             6935000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0             8645000.0                      67.00     NaN   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 262000000.0                   NaN                        NaN     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 260000000.0           447545000.0                      58.09     NaN   Conventional:First Lien    Multifamily:Site-Built              >149             5             1
 238000000.0           439705000.0                      54.07     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             1
 211000000.0           331805000.0                      63.50     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            32             1
 186000000.0                   NaN                        NaN     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            32             3
 178000000.0                   NaN                        NaN     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 163000000.0                   NaN                        NaN     NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 148000000.0           734705000.0                      67.21     NaN   Conventional:First Lien    Multifamily:Site-Built              >149             1             1

3. PROPERTY VALUE ABOVE $10 MILLION
Number of records: 615
 loan_amount  property_value_clean  loan_to_value_ratio_clean  income     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
 119000000.0          1838005000.0                     65.000     NaN       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
  62000000.0          1581075000.0                     51.480     NaN       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
  60000000.0          1576125000.0                     47.900     NaN       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
  70000000.0          1576125000.0                     47.900     NaN       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
      5000.0          1050005000.0                        NaN     NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 2             1             3
  11200000.0           837155000.0                   7500.000     NaN       Conventional:First Lien               Multifamily:Site-Built           100-149             2             3
 148000000.0           734705000.0                     67.210     NaN       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
    325000.0           450005000.0                      0.071    88.0                 VA:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
 260000000.0           447545000.0                     58.090     NaN       Conventional:First Lien               Multifamily:Site-Built              >149             5             1
 238000000.0           439705000.0                     54.070     NaN       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
    125000.0           387005000.0                      0.031   842.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
  92000000.0           350885000.0                     52.800     NaN       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
  28000000.0           350885000.0                      7.994     NaN       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
 211000000.0           331805000.0                     63.500     NaN       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
     75000.0           313965000.0                      0.054   197.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1            31             3
     95000.0           300005000.0                     80.000     NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             1
    305000.0           300005000.0                      0.100   100.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     25000.0           280005000.0                      0.060    45.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     45000.0           240005000.0                      0.060    63.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
  14000000.0           186895000.0                     67.280     NaN       Conventional:First Lien               Multifamily:Site-Built              >149             1             1

4. INCOME ABOVE $1 MILLION
Number of records: 2
   income  loan_amount  property_value_clean  loan_to_value_ratio_clean derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
1620000.0     645000.0                   NaN                        NaN   Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             2
1316000.0    3935000.0                   NaN                        NaN   Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             2

5. EXTREME LOANS BY DWELLING CATEGORY
derived_dwelling_category
Multifamily:Site-Built                    568
Single Family (1-4 Units):Site-Built       18
Multifamily:Manufactured                    6
Single Family (1-4 Units):Manufactured      1
Name: count, dtype: int64

6. EXTREME LOANS BY TOTAL UNITS
total_units_clean
>149       475
100-149     63
50-99       24
1           18
25-49        9
5-24         3
2            1
Name: count, dtype: int64

7. EXTREME LTV BY ACTION TAKEN
action_taken
1      5
3    183
Name: count, dtype: int64

In [40]:
# ============================================================
# LTV CONSISTENCY VALIDATION
# ============================================================

import numpy as np

print("=" * 70)
print("LTV CONSISTENCY VALIDATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Calculate LTV from loan amount and property value
# ------------------------------------------------------------

df['calculated_ltv'] = np.where(
    (df['loan_amount'] > 0) &
    (df['property_value_clean'] > 0),
    (df['loan_amount'] / df['property_value_clean']) * 100,
    np.nan
)


# ------------------------------------------------------------
# 2. Calculate difference between reported and calculated LTV
# ------------------------------------------------------------

df['ltv_difference'] = (
    df['loan_to_value_ratio_clean'] -
    df['calculated_ltv']
)


# ------------------------------------------------------------
# 3. Count records where both LTV values are available
# ------------------------------------------------------------

valid_ltv_comparison = df[
    df['loan_to_value_ratio_clean'].notna() &
    df['calculated_ltv'].notna()
].copy()

print("\nVALID LTV COMPARISONS")
print("Number of records:", len(valid_ltv_comparison))


# ------------------------------------------------------------
# 4. Basic statistics of the difference
# ------------------------------------------------------------

print("\nLTV DIFFERENCE STATISTICS")

print(
    valid_ltv_comparison['ltv_difference'].describe()
)


# ------------------------------------------------------------
# 5. Show records with largest LTV differences
# ------------------------------------------------------------

print("\nLARGEST LTV DIFFERENCES")

print(
    valid_ltv_comparison[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'calculated_ltv',
            'ltv_difference',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'ltv_difference',
        key=lambda x: x.abs(),
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 6. Count records with large LTV differences
# ------------------------------------------------------------

for threshold in [1, 5, 10, 25, 50, 100]:

    count = (
        valid_ltv_comparison['ltv_difference']
        .abs() > threshold
    ).sum()

    percentage = (
        count / len(valid_ltv_comparison) * 100
    )

    print(
        f"\nAbsolute LTV difference > {threshold}: "
        f"{count} records ({percentage:.2f}%)"
    )


# ------------------------------------------------------------
# 7. Compare extreme reported LTV with calculated LTV
# ------------------------------------------------------------

print("\nREPORTED LTV ABOVE 500")

extreme_ltv_comparison = valid_ltv_comparison[
    valid_ltv_comparison['loan_to_value_ratio_clean'] > 500
]

print(
    extreme_ltv_comparison[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'calculated_ltv',
            'ltv_difference',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'action_taken'
        ]
    ]
    .sort_values(
        'loan_to_value_ratio_clean',
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)

======================================================================
LTV CONSISTENCY VALIDATION
======================================================================

VALID LTV COMPARISONS
Number of records: 605451

LTV DIFFERENCE STATISTICS
count    6.054510e+05
mean     1.791664e+02
std      6.643541e+04
min     -1.372058e+04
25%     -7.602740e-01
50%      8.771930e-03
75%      1.500000e+00
max      2.999390e+07
Name: ltv_difference, dtype: float64

LARGEST LTV DIFFERENCES
 loan_amount  property_value_clean  loan_to_value_ratio_clean  calculated_ltv  ltv_difference     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
    305000.0                5000.0               30000000.000     6100.000000    2.999390e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
    295000.0              495000.0               29032800.000       59.595960    2.903274e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            31             3
    255000.0              365000.0               25760000.000       69.863014    2.575993e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
     65000.0                5000.0               16301700.000     1300.000000    1.630040e+07 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000      700.000000    3.493000e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000      700.000000    3.493000e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 303237.000      700.000000    3.025370e+05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    155000.0              215000.0                 159750.000       72.093023    1.596779e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
     65000.0                5000.0                 113785.806     1300.000000    1.124858e+05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 100000.000      700.000000    9.930000e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             1             3
     45000.0                5000.0                  95499.556      900.000000    9.459956e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
    205000.0                5000.0                  97560.976     4100.000000    9.346098e+04       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                  92030.500      700.000000    9.133050e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                  83743.273      700.000000    8.304327e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     65000.0                5000.0                  83422.479     1300.000000    8.212248e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     65000.0                5000.0                  81493.636     1300.000000    8.019364e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    305000.0                5000.0                  85714.286     6100.000000    7.961429e+04       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
    155000.0                5000.0                  77439.714     3100.000000    7.433971e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     45000.0                5000.0                  64452.537      900.000000    6.355254e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
    145000.0                5000.0                  62333.433     2900.000000    5.943343e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3

Absolute LTV difference > 1: 308055 records (50.88%)

Absolute LTV difference > 5: 110226 records (18.21%)

Absolute LTV difference > 10: 100126 records (16.54%)

Absolute LTV difference > 25: 88382 records (14.60%)

Absolute LTV difference > 50: 52639 records (8.69%)

Absolute LTV difference > 100: 1114 records (0.18%)

REPORTED LTV ABOVE 500
 loan_amount  property_value_clean  loan_to_value_ratio_clean  calculated_ltv  ltv_difference     derived_loan_product_type            derived_dwelling_category total_units_clean  action_taken
    305000.0                5000.0               30000000.000     6100.000000    2.999390e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             3
    295000.0              495000.0               29032800.000       59.595960    2.903274e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             3
    255000.0              365000.0               25760000.000       69.863014    2.575993e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1
     65000.0                5000.0               16301700.000     1300.000000    1.630040e+07 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
     35000.0                5000.0                 350000.000      700.000000    3.493000e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             3
     35000.0                5000.0                 350000.000      700.000000    3.493000e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             3
     35000.0                5000.0                 303237.000      700.000000    3.025370e+05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
    155000.0              215000.0                 159750.000       72.093023    1.596779e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1
     65000.0                5000.0                 113785.806     1300.000000    1.124858e+05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
     35000.0                5000.0                 100000.000      700.000000    9.930000e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
    205000.0                5000.0                  97560.976     4100.000000    9.346098e+04       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             3
     45000.0                5000.0                  95499.556      900.000000    9.459956e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
     35000.0                5000.0                  92030.500      700.000000    9.133050e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
    305000.0                5000.0                  85714.286     6100.000000    7.961429e+04       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             3
     35000.0                5000.0                  83743.273      700.000000    8.304327e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
     65000.0                5000.0                  83422.479     1300.000000    8.212248e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
     65000.0                5000.0                  81493.636     1300.000000    8.019364e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
    155000.0                5000.0                  77439.714     3100.000000    7.433971e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
     45000.0                5000.0                  64452.537      900.000000    6.355254e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3
    145000.0                5000.0                  62333.433     2900.000000    5.943343e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             3

In [41]:

# ============================================================
# LTV DATA QUALITY FLAGS
# ============================================================

print("=" * 70)
print("LTV DATA QUALITY FLAGS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Flag extremely high reported LTV
# ------------------------------------------------------------

df['extreme_ltv_flag'] = (
    df['loan_to_value_ratio_clean'] > 500
)


# ------------------------------------------------------------
# 2. Flag extreme disagreement between reported and
#    approximately calculated LTV
# ------------------------------------------------------------

df['ltv_consistency_flag'] = (
    df['ltv_difference'].abs() > 100
)


# ------------------------------------------------------------
# 3. Summary
# ------------------------------------------------------------

print("\nEXTREME LTV FLAG")

print(
    df['extreme_ltv_flag']
    .value_counts()
)


print("\nLTV CONSISTENCY FLAG")

print(
    df['ltv_consistency_flag']
    .value_counts()
)


# ------------------------------------------------------------
# 4. Both flags
# ------------------------------------------------------------

both_flags = df[
    df['extreme_ltv_flag'] &
    df['ltv_consistency_flag']
]

print("\nBOTH FLAGS")

print("Number of records:", len(both_flags))


print(
    "\nPercentage of dataset:",
    f"{len(both_flags) / len(df) * 100:.2f}%"
)


# ------------------------------------------------------------
# 5. Inspect flagged records
# ------------------------------------------------------------

print("\nFLAGGED RECORDS")

print(
    both_flags[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'calculated_ltv',
            'ltv_difference',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'loan_to_value_ratio_clean',
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)

======================================================================
LTV DATA QUALITY FLAGS
======================================================================

EXTREME LTV FLAG
extreme_ltv_flag
False    710018
True        188
Name: count, dtype: int64

LTV CONSISTENCY FLAG
ltv_consistency_flag
False    709092
True       1114
Name: count, dtype: int64

BOTH FLAGS
Number of records: 166

Percentage of dataset: 0.02%

FLAGGED RECORDS
 loan_amount  property_value_clean  loan_to_value_ratio_clean  calculated_ltv  ltv_difference     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
    305000.0                5000.0               30000000.000     6100.000000    2.999390e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
    295000.0              495000.0               29032800.000       59.595960    2.903274e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            31             3
    255000.0              365000.0               25760000.000       69.863014    2.575993e+07       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
     65000.0                5000.0               16301700.000     1300.000000    1.630040e+07 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000      700.000000    3.493000e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000      700.000000    3.493000e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 303237.000      700.000000    3.025370e+05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    155000.0              215000.0                 159750.000       72.093023    1.596779e+05       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
     65000.0                5000.0                 113785.806     1300.000000    1.124858e+05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 100000.000      700.000000    9.930000e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             1             3
    205000.0                5000.0                  97560.976     4100.000000    9.346098e+04       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     45000.0                5000.0                  95499.556      900.000000    9.459956e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     35000.0                5000.0                  92030.500      700.000000    9.133050e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    305000.0                5000.0                  85714.286     6100.000000    7.961429e+04       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
     35000.0                5000.0                  83743.273      700.000000    8.304327e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     65000.0                5000.0                  83422.479     1300.000000    8.212248e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     65000.0                5000.0                  81493.636     1300.000000    8.019364e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    155000.0                5000.0                  77439.714     3100.000000    7.433971e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     45000.0                5000.0                  64452.537      900.000000    6.355254e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
    145000.0                5000.0                  62333.433     2900.000000    5.943343e+04 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3

In [42]:
# ============================================================
# SUSPICIOUS LTV PATTERN ANALYSIS
# ============================================================

print("=" * 70)
print("SUSPICIOUS LTV PATTERN ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create suspicious LTV dataset
# ------------------------------------------------------------

suspicious_ltv = df[
    df['ltv_consistency_flag']
].copy()

print("\nTOTAL SUSPICIOUS LTV RECORDS")
print(len(suspicious_ltv))

print(
    "Percentage of dataset:",
    f"{len(suspicious_ltv) / len(df) * 100:.2f}%"
)


# ------------------------------------------------------------
# 2. By Action Taken
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BY ACTION TAKEN")
print("-" * 70)

print(
    suspicious_ltv['action_taken']
    .value_counts(dropna=False)
    .sort_index()
)


# ------------------------------------------------------------
# 3. By Loan Purpose
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BY LOAN PURPOSE")
print("-" * 70)

print(
    suspicious_ltv['loan_purpose']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 4. By Lien Status
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BY LIEN STATUS")
print("-" * 70)

print(
    suspicious_ltv['lien_status']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 5. By Loan Product
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BY LOAN PRODUCT")
print("-" * 70)

print(
    suspicious_ltv['derived_loan_product_type']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 6. By Dwelling Category
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BY DWELLING CATEGORY")
print("-" * 70)

print(
    suspicious_ltv['derived_dwelling_category']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 7. By Total Units
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BY TOTAL UNITS")
print("-" * 70)

print(
    suspicious_ltv['total_units_clean']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 8. Extremely high reported LTV (>500)
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("EXTREME REPORTED LTV (>500)")
print("-" * 70)

extreme_ltv = df[
    df['extreme_ltv_flag']
].copy()

print("Records:", len(extreme_ltv))

print("\nBy action:")
print(
    extreme_ltv['action_taken']
    .value_counts(dropna=False)
    .sort_index()
)

print("\nBy dwelling:")
print(
    extreme_ltv['derived_dwelling_category']
    .value_counts(dropna=False)
)

print("\nBy total units:")
print(
    extreme_ltv['total_units_clean']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 9. Suspicious LTV by product + dwelling
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("PRODUCT + DWELLING COMBINATION")
print("-" * 70)

print(
    suspicious_ltv
    .groupby(
        [
            'derived_loan_product_type',
            'derived_dwelling_category'
        ],
        dropna=False
    )
    .size()
    .sort_values(ascending=False)
)


# ------------------------------------------------------------
# 10. Summary statistics of suspicious records
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("SUSPICIOUS RECORD LTV STATISTICS")
print("-" * 70)

print(
    suspicious_ltv[
        [
            'loan_to_value_ratio_clean',
            'calculated_ltv',
            'ltv_difference'
        ]
    ]
    .describe()
)

======================================================================
SUSPICIOUS LTV PATTERN ANALYSIS
======================================================================

TOTAL SUSPICIOUS LTV RECORDS
1114
Percentage of dataset: 0.16%

----------------------------------------------------------------------
BY ACTION TAKEN
----------------------------------------------------------------------
action_taken
1    521
2     45
3    548
Name: count, dtype: int64

----------------------------------------------------------------------
BY LOAN PURPOSE
----------------------------------------------------------------------
loan_purpose
1     535
4     276
2     131
32     89
31     83
Name: count, dtype: int64

----------------------------------------------------------------------
BY LIEN STATUS
----------------------------------------------------------------------
lien_status
2    640
1    474
Name: count, dtype: int64

----------------------------------------------------------------------
BY LOAN PRODUCT
----------------------------------------------------------------------
derived_loan_product_type
Conventional:Subordinate Lien    567
Conventional:First Lien          455
FSA/RHS:Subordinate Lien          72
FHA:First Lien                    13
VA:First Lien                      6
FHA:Subordinate Lien               1
Name: count, dtype: int64

----------------------------------------------------------------------
BY DWELLING CATEGORY
----------------------------------------------------------------------
derived_dwelling_category
Single Family (1-4 Units):Site-Built      1051
Multifamily:Site-Built                      38
Single Family (1-4 Units):Manufactured      25
Name: count, dtype: int64

----------------------------------------------------------------------
BY TOTAL UNITS
----------------------------------------------------------------------
total_units_clean
1          1053
2            16
25-49         9
5-24          8
>149          8
100-149       8
50-99         5
4             5
3             2
Name: count, dtype: int64

----------------------------------------------------------------------
EXTREME REPORTED LTV (>500)
----------------------------------------------------------------------
Records: 188

By action:
action_taken
1      5
3    183
Name: count, dtype: int64

By dwelling:
derived_dwelling_category
Single Family (1-4 Units):Site-Built      185
Single Family (1-4 Units):Manufactured      2
Multifamily:Site-Built                      1
Name: count, dtype: int64

By total units:
total_units_clean
1          184
2            2
100-149      1
3            1
Name: count, dtype: int64

----------------------------------------------------------------------
PRODUCT + DWELLING COMBINATION
----------------------------------------------------------------------
derived_loan_product_type      derived_dwelling_category
Conventional:Subordinate Lien  Single Family (1-4 Units):Site-Built      549
Conventional:First Lien        Single Family (1-4 Units):Site-Built      417
FSA/RHS:Subordinate Lien       Single Family (1-4 Units):Site-Built       68
Conventional:First Lien        Multifamily:Site-Built                     34
Conventional:Subordinate Lien  Single Family (1-4 Units):Manufactured     15
FHA:First Lien                 Single Family (1-4 Units):Site-Built       10
VA:First Lien                  Single Family (1-4 Units):Site-Built        6
FSA/RHS:Subordinate Lien       Single Family (1-4 Units):Manufactured      4
Conventional:First Lien        Single Family (1-4 Units):Manufactured      4
Conventional:Subordinate Lien  Multifamily:Site-Built                      3
FHA:First Lien                 Single Family (1-4 Units):Manufactured      2
                               Multifamily:Site-Built                      1
FHA:Subordinate Lien           Single Family (1-4 Units):Site-Built        1
dtype: int64

----------------------------------------------------------------------
SUSPICIOUS RECORD LTV STATISTICS
----------------------------------------------------------------------
       loan_to_value_ratio_clean  calculated_ltv  ltv_difference
count               1.114000e+03     1114.000000    1.114000e+03
mean                9.341305e+04      311.404957    9.310164e+04
std                 1.546806e+06      963.356210    1.546702e+06
min                 1.060000e+00        1.234568   -1.372058e+04
25%                 1.021200e+02        7.110958    1.000792e+02
50%                 1.193380e+02       60.000000    1.028040e+02
75%                 2.123940e+02      217.880221    1.498862e+02
max                 3.000000e+07    13787.575150    2.999390e+07

In [43]:
# ============================================================
# LTV ANOMALY + PROPERTY VALUE INVESTIGATION
# ============================================================

print("=" * 70)
print("LTV ANOMALY + PROPERTY VALUE INVESTIGATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Property value distribution among suspicious LTV records
# ------------------------------------------------------------

suspicious_ltv = df[df['ltv_consistency_flag']].copy()

print("\nPROPERTY VALUE - SUSPICIOUS LTV RECORDS")
print("-" * 70)

print(
    suspicious_ltv['property_value_clean']
    .describe()
)


# ------------------------------------------------------------
# 2. How many suspicious records have property value <= $10,000?
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("LOW PROPERTY VALUE CHECK")
print("-" * 70)

for threshold in [5000, 10000, 25000, 50000, 100000]:

    count = (
        suspicious_ltv['property_value_clean'] <= threshold
    ).sum()

    percentage = count / len(suspicious_ltv) * 100

    print(
        f"Property value <= ${threshold:,}: "
        f"{count:,} records ({percentage:.2f}%)"
    )


# ------------------------------------------------------------
# 3. Exact property values among suspicious records
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("MOST COMMON PROPERTY VALUES")
print("-" * 70)

print(
    suspicious_ltv['property_value_clean']
    .value_counts(dropna=False)
    .head(20)
)


# ------------------------------------------------------------
# 4. Property value = $5,000
# ------------------------------------------------------------

property_5000 = suspicious_ltv[
    suspicious_ltv['property_value_clean'] == 5000
].copy()

print("\n" + "-" * 70)
print("PROPERTY VALUE = $5,000")
print("-" * 70)

print("Records:", len(property_5000))

print(
    "Percentage of suspicious LTV records:",
    f"{len(property_5000) / len(suspicious_ltv) * 100:.2f}%"
)

print("\nBy action:")
print(
    property_5000['action_taken']
    .value_counts(dropna=False)
    .sort_index()
)

print("\nBy dwelling:")
print(
    property_5000['derived_dwelling_category']
    .value_counts(dropna=False)
)

print("\nBy loan product:")
print(
    property_5000['derived_loan_product_type']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 5. Compare suspicious records with normal records
# ------------------------------------------------------------

normal_ltv = df[
    ~df['ltv_consistency_flag']
].copy()

print("\n" + "-" * 70)
print("PROPERTY VALUE COMPARISON")
print("-" * 70)

comparison = pd.DataFrame({
    'Suspicious_LTV': suspicious_ltv['property_value_clean'].describe(),
    'Normal_LTV': normal_ltv['property_value_clean'].describe()
})

print(comparison)


# ------------------------------------------------------------
# 6. Extreme LTV records and property value
# ------------------------------------------------------------

extreme_ltv = df[
    df['extreme_ltv_flag']
].copy()

print("\n" + "-" * 70)
print("EXTREME LTV (>500) PROPERTY VALUES")
print("-" * 70)

print(
    extreme_ltv['property_value_clean']
    .describe()
)


# ------------------------------------------------------------
# 7. Extreme LTV with $5,000 property
# ------------------------------------------------------------

extreme_5000 = extreme_ltv[
    extreme_ltv['property_value_clean'] == 5000
].copy()

print("\n" + "-" * 70)
print("EXTREME LTV + $5,000 PROPERTY")
print("-" * 70)

print("Records:", len(extreme_5000))

print("\nSample:")
print(
    extreme_5000[
        [
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'calculated_ltv',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'loan_to_value_ratio_clean',
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)


# ------------------------------------------------------------
# 8. Missing property values among suspicious LTV
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("MISSING PROPERTY VALUE")
print("-" * 70)

missing_property = suspicious_ltv[
    suspicious_ltv['property_value_clean'].isna()
]

print("Suspicious records with missing property value:",
      len(missing_property))

print(
    "Percentage:",
    f"{len(missing_property) / len(suspicious_ltv) * 100:.2f}%"
)


# ------------------------------------------------------------
# 9. Final diagnostic summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL DIAGNOSTIC SUMMARY")
print("=" * 70)

print("Total dataset:", len(df))
print("LTV consistency anomalies:", len(suspicious_ltv))
print("Extreme LTV anomalies:", len(extreme_ltv))
print("Extreme + consistency anomalies:",
      len(
          df[
              df['extreme_ltv_flag'] &
              df['ltv_consistency_flag']
          ]
      ))

print("Suspicious records with $5,000 property:",
      len(property_5000))

print("Extreme LTV records with $5,000 property:",
      len(extreme_5000))

======================================================================
LTV ANOMALY + PROPERTY VALUE INVESTIGATION
======================================================================

PROPERTY VALUE - SUSPICIOUS LTV RECORDS
----------------------------------------------------------------------
count    1.114000e+03
mean     1.262092e+06
std      2.531464e+07
min      5.000000e+03
25%      1.250000e+05
50%      2.250000e+05
75%      3.050000e+05
max      8.371550e+08
Name: property_value_clean, dtype: float64

----------------------------------------------------------------------
LOW PROPERTY VALUE CHECK
----------------------------------------------------------------------
Property value <= $5,000: 107 records (9.61%)
Property value <= $10,000: 107 records (9.61%)
Property value <= $25,000: 151 records (13.55%)
Property value <= $50,000: 188 records (16.88%)
Property value <= $100,000: 239 records (21.45%)

----------------------------------------------------------------------
MOST COMMON PROPERTY VALUES
----------------------------------------------------------------------
property_value_clean
5000.0      107
245000.0     67
225000.0     49
255000.0     47
185000.0     38
175000.0     36
205000.0     35
195000.0     31
305000.0     30
235000.0     30
215000.0     29
275000.0     27
285000.0     26
25000.0      25
135000.0     25
155000.0     23
265000.0     22
295000.0     21
115000.0     21
35000.0      20
Name: count, dtype: int64

----------------------------------------------------------------------
PROPERTY VALUE = $5,000
----------------------------------------------------------------------
Records: 107
Percentage of suspicious LTV records: 9.61%

By action:
action_taken
1      4
3    103
Name: count, dtype: int64

By dwelling:
derived_dwelling_category
Single Family (1-4 Units):Site-Built      105
Single Family (1-4 Units):Manufactured      2
Name: count, dtype: int64

By loan product:
derived_loan_product_type
Conventional:First Lien          76
Conventional:Subordinate Lien    31
Name: count, dtype: int64

----------------------------------------------------------------------
PROPERTY VALUE COMPARISON
----------------------------------------------------------------------
       Suspicious_LTV    Normal_LTV
count    1.114000e+03  6.651960e+05
mean     1.262092e+06  4.764086e+05
std      2.531464e+07  4.818090e+06
min      5.000000e+03  5.000000e+03
25%      1.250000e+05  2.450000e+05
50%      2.250000e+05  3.350000e+05
75%      3.050000e+05  4.950000e+05
max      8.371550e+08  1.838005e+09

----------------------------------------------------------------------
EXTREME LTV (>500) PROPERTY VALUES
----------------------------------------------------------------------
count    1.840000e+02
mean     4.591250e+06
std      6.171288e+07
min      5.000000e+03
25%      5.000000e+03
50%      5.000000e+03
75%      2.500000e+04
max      8.371550e+08
Name: property_value_clean, dtype: float64

----------------------------------------------------------------------
EXTREME LTV + $5,000 PROPERTY
----------------------------------------------------------------------
Records: 108

Sample:
 loan_amount  property_value_clean  loan_to_value_ratio_clean  calculated_ltv     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
    305000.0                5000.0               30000000.000          6100.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     65000.0                5000.0               16301700.000          1300.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000           700.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 350000.000           700.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 303237.000           700.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     65000.0                5000.0                 113785.806          1300.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     35000.0                5000.0                 100000.000           700.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             1             3
    205000.0                5000.0                  97560.976          4100.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
     45000.0                5000.0                  95499.556           900.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     35000.0                5000.0                  92030.500           700.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    305000.0                5000.0                  85714.286          6100.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
     35000.0                5000.0                  83743.273           700.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     65000.0                5000.0                  83422.479          1300.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
     65000.0                5000.0                  81493.636          1300.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    155000.0                5000.0                  77439.714          3100.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     45000.0                5000.0                  64452.537           900.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
    145000.0                5000.0                  62333.433          2900.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
    205000.0                5000.0                  53333.333          4100.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             2             3
     35000.0                5000.0                  46327.222           700.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
     75000.0                5000.0                  37500.000          1500.0       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3

----------------------------------------------------------------------
MISSING PROPERTY VALUE
----------------------------------------------------------------------
Suspicious records with missing property value: 0
Percentage: 0.00%

======================================================================
FINAL DIAGNOSTIC SUMMARY
======================================================================
Total dataset: 710206
LTV consistency anomalies: 1114
Extreme LTV anomalies: 188
Extreme + consistency anomalies: 166
Suspicious records with $5,000 property: 107
Extreme LTV records with $5,000 property: 108

In [44]:
# ============================================================
# FINAL LTV DATA QUALITY TREATMENT
# ============================================================

print("=" * 70)
print("FINAL LTV DATA QUALITY TREATMENT")
print("=" * 70)


# ------------------------------------------------------------
# 1. Preserve original LTV
# ------------------------------------------------------------

df['loan_to_value_ratio_original'] = df['loan_to_value_ratio']


# ------------------------------------------------------------
# 2. Create analysis-ready LTV field
#
# Severe anomalies (>500) are excluded from LTV-specific
# analysis, but the original records remain in the dataset.
# ------------------------------------------------------------

df['ltv_analysis_value'] = df['loan_to_value_ratio_clean'].copy()

df.loc[
    df['extreme_ltv_flag'],
    'ltv_analysis_value'
] = np.nan


# ------------------------------------------------------------
# 3. Create a final LTV quality category
# ------------------------------------------------------------

df['ltv_quality_category'] = 'Valid / Usable'

df.loc[
    df['ltv_consistency_flag'],
    'ltv_quality_category'
] = 'Consistency Anomaly'

df.loc[
    df['extreme_ltv_flag'],
    'ltv_quality_category'
] = 'Extreme Anomaly'


# Missing or non-numeric LTV
df.loc[
    df['loan_to_value_ratio_clean'].isna(),
    'ltv_quality_category'
] = 'Missing / Non-numeric'


# ------------------------------------------------------------
# 4. Check final categories
# ------------------------------------------------------------

print("\nLTV QUALITY CATEGORY")
print("-" * 70)

print(
    df['ltv_quality_category']
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 5. Check analysis field
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("LTV ANALYSIS VALUE")
print("-" * 70)

print(
    df['ltv_analysis_value']
    .describe()
)


# ------------------------------------------------------------
# 6. Verify extreme anomalies are excluded
# ------------------------------------------------------------

remaining_extreme = (
    df['ltv_analysis_value'] > 500
).sum()

print("\nExtreme LTV values remaining in analysis field:",
      remaining_extreme)


# ------------------------------------------------------------
# 7. Verify original LTV is still available
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("ORIGINAL LTV PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'loan_to_value_ratio_original',
            'loan_to_value_ratio_clean',
            'ltv_analysis_value',
            'ltv_quality_category'
        ]
    ].head(10)
)


# ------------------------------------------------------------
# 8. Final counts
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL LTV SUMMARY")
print("=" * 70)

print("Total records:", len(df))

print(
    "Numeric LTV records:",
    df['loan_to_value_ratio_clean'].notna().sum()
)

print(
    "LTV consistency anomalies:",
    df['ltv_consistency_flag'].sum()
)

print(
    "Extreme LTV anomalies:",
    df['extreme_ltv_flag'].sum()
)

print(
    "Usable LTV records:",
    df['ltv_analysis_value'].notna().sum()
)

print(
    "Excluded from LTV-specific analysis:",
    df['ltv_analysis_value'].isna().sum()
)

======================================================================
FINAL LTV DATA QUALITY TREATMENT
======================================================================

LTV QUALITY CATEGORY
----------------------------------------------------------------------
ltv_quality_category
Valid / Usable           610888
Missing / Non-numeric     98182
Consistency Anomaly         948
Extreme Anomaly             188
Name: count, dtype: int64

----------------------------------------------------------------------
LTV ANALYSIS VALUE
----------------------------------------------------------------------
count    611836.000000
mean         78.171513
std          21.974212
min           0.001000
25%          68.607750
50%          80.000000
75%          96.500000
max         500.000000
Name: ltv_analysis_value, dtype: float64

Extreme LTV values remaining in analysis field: 0

----------------------------------------------------------------------
ORIGINAL LTV PRESERVATION CHECK
----------------------------------------------------------------------
  loan_to_value_ratio_original  loan_to_value_ratio_clean  ltv_analysis_value  \
0                       39.394                     39.394              39.394
1                          NaN                        NaN                 NaN
2                          NaN                        NaN                 NaN
3                      101.607                    101.607             101.607
4                          NaN                        NaN                 NaN
5                          NaN                        NaN                 NaN
6                          NaN                        NaN                 NaN
7                          NaN                        NaN                 NaN
8                          NaN                        NaN                 NaN
9                           95                     95.000              95.000

    ltv_quality_category
0         Valid / Usable
1  Missing / Non-numeric
2  Missing / Non-numeric
3         Valid / Usable
4  Missing / Non-numeric
5  Missing / Non-numeric
6  Missing / Non-numeric
7  Missing / Non-numeric
8  Missing / Non-numeric
9         Valid / Usable

======================================================================
FINAL LTV SUMMARY
======================================================================
Total records: 710206
Numeric LTV records: 612024
LTV consistency anomalies: 1114
Extreme LTV anomalies: 188
Usable LTV records: 611836
Excluded from LTV-specific analysis: 98370

In [45]:
# ============================================================
# INTEREST RATE DATA QUALITY INVESTIGATION
# ============================================================

print("=" * 70)
print("INTEREST RATE DATA QUALITY INVESTIGATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Basic information
# ------------------------------------------------------------

print("\nINTEREST RATE DTYPE")
print("-" * 70)

print(df['interest_rate'].dtype)


print("\nMISSING VALUES")
print("-" * 70)

print(
    "Missing:",
    df['interest_rate'].isna().sum()
)

print(
    "Missing percentage:",
    f"{df['interest_rate'].isna().mean() * 100:.2f}%"
)


# ------------------------------------------------------------
# 2. Exempt values
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("EXEMPT VALUES")
print("-" * 70)

exempt_interest = (
    df['interest_rate']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print("Exempt:", exempt_interest)

print(
    "Exempt percentage:",
    f"{exempt_interest / len(df) * 100:.2f}%"
)


# ------------------------------------------------------------
# 3. Create numeric helper column
# ------------------------------------------------------------

df['interest_rate_clean'] = pd.to_numeric(
    df['interest_rate'],
    errors='coerce'
)


# ------------------------------------------------------------
# 4. Numeric summary
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("NUMERIC INTEREST RATE SUMMARY")
print("-" * 70)

print(
    df['interest_rate_clean']
    .describe()
)


# ------------------------------------------------------------
# 5. Negative interest rates
# ------------------------------------------------------------

negative_interest = df[
    df['interest_rate_clean'] < 0
]

print("\n" + "-" * 70)
print("NEGATIVE INTEREST RATES")
print("-" * 70)

print("Records:", len(negative_interest))

if len(negative_interest) > 0:
    print(
        negative_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .head(20)
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 6. Zero interest rates
# ------------------------------------------------------------

zero_interest = df[
    df['interest_rate_clean'] == 0
]

print("\n" + "-" * 70)
print("ZERO INTEREST RATES")
print("-" * 70)

print("Records:", len(zero_interest))

if len(zero_interest) > 0:
    print(
        zero_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'derived_loan_product_type',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .head(20)
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 7. Interest rate above 15%
# ------------------------------------------------------------

high_interest = df[
    df['interest_rate_clean'] > 15
]

print("\n" + "-" * 70)
print("INTEREST RATE > 15%")
print("-" * 70)

print("Records:", len(high_interest))

print(
    "Percentage:",
    f"{len(high_interest) / len(df) * 100:.4f}%"
)

if len(high_interest) > 0:
    print(
        high_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'interest_rate_clean',
            ascending=False
        )
        .head(20)
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 8. Interest rate above 20%
# ------------------------------------------------------------

very_high_interest = df[
    df['interest_rate_clean'] > 20
]

print("\n" + "-" * 70)
print("INTEREST RATE > 20%")
print("-" * 70)

print("Records:", len(very_high_interest))

print(
    "Percentage:",
    f"{len(very_high_interest) / len(df) * 100:.4f}%"
)


# ------------------------------------------------------------
# 9. Interest rate percentiles
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("INTEREST RATE PERCENTILES")
print("-" * 70)

print(
    df['interest_rate_clean']
    .quantile(
        [
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.995,
            0.999
        ]
    )
)


# ------------------------------------------------------------
# 10. Most common interest rates
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("MOST COMMON INTEREST RATES")
print("-" * 70)

print(
    df['interest_rate_clean']
    .value_counts(dropna=False)
    .head(20)
)


# ------------------------------------------------------------
# 11. Very low interest rates
# ------------------------------------------------------------

low_interest = df[
    (df['interest_rate_clean'] > 0) &
    (df['interest_rate_clean'] < 1)
]

print("\n" + "-" * 70)
print("INTEREST RATE BETWEEN 0 AND 1%")
print("-" * 70)

print("Records:", len(low_interest))

if len(low_interest) > 0:
    print(
        low_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'derived_loan_product_type',
                'action_taken'
            ]
        ]
        .head(20)
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 12. Distribution by loan product for high rates
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("HIGH INTEREST RATE BY LOAN PRODUCT")
print("-" * 70)

if len(high_interest) > 0:
    print(
        high_interest[
            'derived_loan_product_type'
        ]
        .value_counts(dropna=False)
    )


# ------------------------------------------------------------
# 13. Final summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INTEREST RATE DIAGNOSTIC SUMMARY")
print("=" * 70)

print("Total records:", len(df))

print(
    "Numeric interest rates:",
    df['interest_rate_clean'].notna().sum()
)

print(
    "Missing/non-numeric:",
    df['interest_rate_clean'].isna().sum()
)

print(
    "Negative:",
    (df['interest_rate_clean'] < 0).sum()
)

print(
    "Zero:",
    (df['interest_rate_clean'] == 0).sum()
)

print(
    "Above 15%:",
    (df['interest_rate_clean'] > 15).sum()
)

print(
    "Above 20%:",
    (df['interest_rate_clean'] > 20).sum()
)

======================================================================
INTEREST RATE DATA QUALITY INVESTIGATION
======================================================================

INTEREST RATE DTYPE
----------------------------------------------------------------------
object

MISSING VALUES
----------------------------------------------------------------------
Missing: 183431
Missing percentage: 25.83%

----------------------------------------------------------------------
EXEMPT VALUES
----------------------------------------------------------------------
Exempt: 16812
Exempt percentage: 2.37%

----------------------------------------------------------------------
NUMERIC INTEREST RATE SUMMARY
----------------------------------------------------------------------
count    509963.000000
mean          6.787371
std           1.534261
min           0.000000
25%           5.999000
50%           6.625000
75%           7.375000
max          23.000000
Name: interest_rate_clean, dtype: float64

----------------------------------------------------------------------
NEGATIVE INTEREST RATES
----------------------------------------------------------------------
Records: 0

----------------------------------------------------------------------
ZERO INTEREST RATES
----------------------------------------------------------------------
Records: 3646
interest_rate  loan_amount  property_value_clean     derived_loan_product_type  loan_purpose  action_taken
            0      15000.0              405000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              285000.0 Conventional:Subordinate Lien             1             1
            0      15000.0              305000.0 Conventional:Subordinate Lien             1             1
            0      15000.0              325000.0 Conventional:Subordinate Lien             1             1
            0      15000.0              415000.0 Conventional:Subordinate Lien             1             1
            0      15000.0              495000.0 Conventional:Subordinate Lien             1             1
            0     165000.0              265000.0       Conventional:First Lien            31             2
            0     235000.0              295000.0       Conventional:First Lien            31             2
            0      15000.0              315000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              265000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              185000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              125000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              165000.0 Conventional:Subordinate Lien             1             2
            0       5000.0              155000.0 Conventional:Subordinate Lien             1             1
            0      15000.0              245000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              185000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              255000.0 Conventional:Subordinate Lien             1             1
            0      15000.0              285000.0 Conventional:Subordinate Lien             1             1
            0       5000.0              225000.0 Conventional:Subordinate Lien             1             2
            0       5000.0              315000.0 Conventional:Subordinate Lien             1             1

----------------------------------------------------------------------
INTEREST RATE > 15%
----------------------------------------------------------------------
Records: 84
Percentage: 0.0118%

KeyError: 'interest_rate_clean'

In [46]:
# ============================================================
# INTEREST RATE INVESTIGATION - CONTINUATION
# ============================================================

print("=" * 70)
print("INTEREST RATE INVESTIGATION - CONTINUATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Interest rate > 15%
# ------------------------------------------------------------

high_interest = df[
    df['interest_rate_clean'] > 15
].copy()

print("\nINTEREST RATE > 15%")
print("-" * 70)

print("Records:", len(high_interest))

print(
    "Percentage:",
    f"{len(high_interest) / len(df) * 100:.4f}%"
)

if len(high_interest) > 0:

    print("\nHighest interest rates:")

    print(
        high_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'interest_rate',
            ascending=False
        )
        .head(20)
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 2. Interest rate > 20%
# ------------------------------------------------------------

very_high_interest = df[
    df['interest_rate_clean'] > 20
].copy()

print("\n" + "-" * 70)
print("INTEREST RATE > 20%")
print("-" * 70)

print("Records:", len(very_high_interest))

print(
    "Percentage:",
    f"{len(very_high_interest) / len(df) * 100:.4f}%"
)

if len(very_high_interest) > 0:

    print(
        very_high_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'interest_rate',
            ascending=False
        )
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 3. Interest rate percentiles
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("INTEREST RATE PERCENTILES")
print("-" * 70)

print(
    df['interest_rate_clean']
    .quantile(
        [
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.995,
            0.999
        ]
    )
)


# ------------------------------------------------------------
# 4. Most common interest rates
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("MOST COMMON INTEREST RATES")
print("-" * 70)

print(
    df['interest_rate_clean']
    .value_counts(dropna=False)
    .head(20)
)


# ------------------------------------------------------------
# 5. Very low interest rates
# ------------------------------------------------------------

low_interest = df[
    (df['interest_rate_clean'] > 0) &
    (df['interest_rate_clean'] < 1)
].copy()

print("\n" + "-" * 70)
print("INTEREST RATE BETWEEN 0 AND 1%")
print("-" * 70)

print("Records:", len(low_interest))

if len(low_interest) > 0:

    print(
        low_interest[
            [
                'interest_rate',
                'loan_amount',
                'property_value_clean',
                'derived_loan_product_type',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .head(20)
        .to_string(index=False)
    )


# ------------------------------------------------------------
# 6. High interest rate by loan product
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("HIGH INTEREST RATE BY LOAN PRODUCT")
print("-" * 70)

if len(high_interest) > 0:

    print(
        high_interest[
            'derived_loan_product_type'
        ]
        .value_counts(dropna=False)
    )


# ------------------------------------------------------------
# 7. High interest rate by action
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("HIGH INTEREST RATE BY ACTION")
print("-" * 70)

if len(high_interest) > 0:

    print(
        high_interest[
            'action_taken'
        ]
        .value_counts(dropna=False)
        .sort_index()
    )


# ------------------------------------------------------------
# 8. Zero interest rate by loan product
# ------------------------------------------------------------

zero_interest = df[
    df['interest_rate_clean'] == 0
].copy()

print("\n" + "-" * 70)
print("ZERO INTEREST RATE BY LOAN PRODUCT")
print("-" * 70)

print(
    zero_interest[
        'derived_loan_product_type'
    ]
    .value_counts(dropna=False)
)


# ------------------------------------------------------------
# 9. Zero interest rate by action
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("ZERO INTEREST RATE BY ACTION")
print("-" * 70)

print(
    zero_interest[
        'action_taken'
    ]
    .value_counts(dropna=False)
    .sort_index()
)


# ------------------------------------------------------------
# 10. Final diagnostic summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("INTEREST RATE DIAGNOSTIC SUMMARY")
print("=" * 70)

print("Total records:", len(df))

print(
    "Numeric interest rates:",
    df['interest_rate_clean'].notna().sum()
)

print(
    "Missing/non-numeric:",
    df['interest_rate_clean'].isna().sum()
)

print(
    "Negative:",
    (df['interest_rate_clean'] < 0).sum()
)

print(
    "Zero:",
    (df['interest_rate_clean'] == 0).sum()
)

print(
    "Between 0 and 1%:",
    len(low_interest)
)

print(
    "Above 15%:",
    len(high_interest)
)

print(
    "Above 20%:",
    len(very_high_interest)
)

======================================================================
INTEREST RATE INVESTIGATION - CONTINUATION
======================================================================

INTEREST RATE > 15%
----------------------------------------------------------------------
Records: 84
Percentage: 0.0118%

Highest interest rates:

TypeError: '<' not supported between instances of 'str' and 'float'

In [47]:
high_interest = df[df['interest_rate_clean'] > 15].copy()

print(high_interest[
    [
        'interest_rate',
        'interest_rate_clean',
        'loan_amount',
        'property_value_clean',
        'derived_loan_product_type',
        'derived_dwelling_category',
        'loan_purpose',
        'action_taken'
    ]
].sort_values(
    'interest_rate_clean',
    ascending=False
).head(20).to_string(index=False))

interest_rate  interest_rate_clean  loan_amount  property_value_clean     derived_loan_product_type            derived_dwelling_category  loan_purpose  action_taken
           23               23.000     285000.0              815000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built            32             2
         19.0               19.000    5505000.0            60905000.0       Conventional:First Lien               Multifamily:Site-Built             1             1
        18.99               18.990      35000.0              105000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built             1             1
         18.0               18.000    1205000.0            21005000.0       Conventional:First Lien               Multifamily:Site-Built            31             1
           18               18.000      65000.0              295000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built            32             1
        17.99               17.990     365000.0              485000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built             1             1
        17.67               17.670      75000.0              475000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             1             1
       17.375               17.375     185000.0              405000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built             2             1
        16.57               16.570      35000.0              165000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             1             1
         16.5               16.500      55000.0              285000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
         16.5               16.500      65000.0              375000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
         16.5               16.500      75000.0              495000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
         16.5               16.500      85000.0              285000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
        16.25               16.250      65000.0             1075000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
        16.25               16.250      65000.0              485000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
        16.24               16.240      95000.0              205000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built             4             1
       16.125               16.125     365000.0              805000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built             2             1
       16.116               16.116      45000.0              195000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built             1             1
           16               16.000      45000.0                   NaN Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1
           16               16.000      25000.0                   NaN Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built             4             1

In [48]:
# Interest Rate Pattern Analysis

high_interest = df[df['interest_rate_clean'] > 15].copy()

print("=" * 70)
print("HIGH INTEREST RATE PATTERN ANALYSIS")
print("=" * 70)

print("\nBY LOAN PRODUCT")
print("-" * 70)
print(high_interest['derived_loan_product_type'].value_counts(dropna=False))

print("\nBY LIEN STATUS")
print("-" * 70)
print(high_interest['lien_status'].value_counts(dropna=False))

print("\nBY ACTION TAKEN")
print("-" * 70)
print(high_interest['action_taken'].value_counts().sort_index())

print("\nBY LOAN PURPOSE")
print("-" * 70)
print(high_interest['loan_purpose'].value_counts().sort_index())

print("\nBY DWELLING CATEGORY")
print("-" * 70)
print(high_interest['derived_dwelling_category'].value_counts(dropna=False))

print("\nINTEREST RATE SUMMARY BY LOAN PRODUCT")
print("-" * 70)
print(
    high_interest
    .groupby('derived_loan_product_type')['interest_rate_clean']
    .agg(['count', 'min', 'median', 'max'])
    .sort_values('count', ascending=False)
)

print("\nHIGH INTEREST RATE STATISTICS")
print("-" * 70)
print(high_interest['interest_rate_clean'].describe())

======================================================================
HIGH INTEREST RATE PATTERN ANALYSIS
======================================================================

BY LOAN PRODUCT
----------------------------------------------------------------------
derived_loan_product_type
Conventional:Subordinate Lien    70
Conventional:First Lien          14
Name: count, dtype: int64

BY LIEN STATUS
----------------------------------------------------------------------
lien_status
2    70
1    14
Name: count, dtype: int64

BY ACTION TAKEN
----------------------------------------------------------------------
action_taken
1    73
2    11
Name: count, dtype: int64

BY LOAN PURPOSE
----------------------------------------------------------------------
loan_purpose
1     10
2     22
4     48
31     1
32     3
Name: count, dtype: int64

BY DWELLING CATEGORY
----------------------------------------------------------------------
derived_dwelling_category
Single Family (1-4 Units):Site-Built    82
Multifamily:Site-Built                   2
Name: count, dtype: int64

INTEREST RATE SUMMARY BY LOAN PRODUCT
----------------------------------------------------------------------
                               count     min   median   max
derived_loan_product_type
Conventional:Subordinate Lien     70  15.050  15.3625  18.0
Conventional:First Lien           14  15.375  16.1825  23.0

HIGH INTEREST RATE STATISTICS
----------------------------------------------------------------------
count    84.000000
mean     15.836345
std       1.160066
min      15.050000
25%      15.240000
50%      15.500000
75%      15.992500
max      23.000000
Name: interest_rate_clean, dtype: float64

In [49]:
# Detailed investigation of high interest-rate records

high_interest = df[df['interest_rate_clean'] > 15].copy()

print("=" * 70)
print("HIGH INTEREST RATE DETAILED INVESTIGATION")
print("=" * 70)

# Show all 84 records with important financial fields
columns_to_check = [
    'interest_rate',
    'interest_rate_clean',
    'loan_amount',
    'property_value_clean',
    'loan_to_value_ratio_clean',
    'debt_to_income_ratio',
    'derived_loan_product_type',
    'lien_status',
    'loan_purpose',
    'action_taken'
]

print("\nHIGH INTEREST RATE RECORDS")
print("-" * 70)

print(
    high_interest[
        columns_to_check
    ]
    .sort_values('interest_rate_clean', ascending=False)
    .to_string(index=False)
)

# Check whether any high-interest records also have extreme LTV
print("\n" + "=" * 70)
print("HIGH INTEREST + EXTREME LTV")
print("=" * 70)

high_interest_extreme_ltv = high_interest[
    high_interest['extreme_ltv_flag']
]

print("Records:", len(high_interest_extreme_ltv))

if len(high_interest_extreme_ltv) > 0:
    print(
        high_interest_extreme_ltv[
            columns_to_check
        ]
        .sort_values('interest_rate_clean', ascending=False)
        .to_string(index=False)
    )

# Check missing values in important fields
print("\n" + "=" * 70)
print("MISSING VALUES AMONG HIGH INTEREST RECORDS")
print("=" * 70)

print(
    high_interest[
        [
            'interest_rate_clean',
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'debt_to_income_ratio'
        ]
    ]
    .isna()
    .sum()
)

======================================================================
HIGH INTEREST RATE DETAILED INVESTIGATION
======================================================================

HIGH INTEREST RATE RECORDS
----------------------------------------------------------------------
interest_rate  interest_rate_clean  loan_amount  property_value_clean  loan_to_value_ratio_clean debt_to_income_ratio     derived_loan_product_type  lien_status  loan_purpose  action_taken
           23               23.000     285000.0              815000.0                   35.30300                 >60%       Conventional:First Lien            1            32             2
         19.0               19.000    5505000.0            60905000.0                    9.03000                  NaN       Conventional:First Lien            1             1             1
        18.99               18.990      35000.0              105000.0                   24.00000                  NaN       Conventional:First Lien            1             1             1
         18.0               18.000    1205000.0            21005000.0                    5.71000                  NaN       Conventional:First Lien            1            31             1
           18               18.000      65000.0              295000.0                   22.75000              50%-60% Conventional:Subordinate Lien            2            32             1
        17.99               17.990     365000.0              485000.0                   75.00000                 >60%       Conventional:First Lien            1             1             1
        17.67               17.670      75000.0              475000.0                   68.98500                   49 Conventional:Subordinate Lien            2             1             1
       17.375               17.375     185000.0              405000.0                   55.00000                  NaN       Conventional:First Lien            1             2             1
        16.57               16.570      35000.0              165000.0                   64.98300                   36 Conventional:Subordinate Lien            2             1             1
         16.5               16.500      55000.0              285000.0                   58.98600                   36 Conventional:Subordinate Lien            2             4             1
         16.5               16.500      65000.0              375000.0                   78.46900                   41 Conventional:Subordinate Lien            2             4             1
         16.5               16.500      75000.0              495000.0                   79.99300                   43 Conventional:Subordinate Lien            2             4             1
         16.5               16.500      85000.0              285000.0                   79.67000             30%-<36% Conventional:Subordinate Lien            2             4             1
        16.25               16.250      65000.0             1075000.0                   79.99800             20%-<30% Conventional:Subordinate Lien            2             4             1
        16.25               16.250      65000.0              485000.0                   79.47900                   49 Conventional:Subordinate Lien            2             4             1
        16.24               16.240      95000.0              205000.0                   44.55400                   42       Conventional:First Lien            1             4             1
       16.125               16.125     365000.0              805000.0                   64.96000                  NaN       Conventional:First Lien            1             2             1
       16.116               16.116      45000.0              195000.0                   20.94600             20%-<30%       Conventional:First Lien            1             1             1
           16               16.000      45000.0                   NaN                   54.15195                   49 Conventional:Subordinate Lien            2             4             1
           16               16.000      25000.0                   NaN                   52.13908                   49 Conventional:Subordinate Lien            2             4             1
           16               16.000      75000.0              345000.0                   74.34100                   46 Conventional:Subordinate Lien            2             2             1
        15.99               15.990     115000.0              115000.0                   65.00000                  NaN       Conventional:First Lien            1             1             1
        15.97               15.970      55000.0              165000.0                   79.96000                   36 Conventional:Subordinate Lien            2             1             1
       15.875               15.875     275000.0              505000.0                   59.96000                  NaN       Conventional:First Lien            1             2             1
        15.75               15.750      95000.0              195000.0                   77.03700                   40 Conventional:Subordinate Lien            2             4             1
        15.75               15.750      85000.0              355000.0                   79.56700             30%-<36% Conventional:Subordinate Lien            2             2             1
        15.75               15.750      65000.0              555000.0                   74.59300             30%-<36% Conventional:Subordinate Lien            2             4             1
        15.75               15.750      55000.0              325000.0                   66.68600                   43 Conventional:Subordinate Lien            2             2             1
        15.75               15.750      85000.0              615000.0                   72.78600             20%-<30% Conventional:Subordinate Lien            2             4             1
        15.75               15.750      25000.0                   NaN                   64.99333                 <20% Conventional:Subordinate Lien            2             4             2
        15.75               15.750      65000.0              315000.0                   79.86900                   49 Conventional:Subordinate Lien            2             2             1
        15.74               15.740     275000.0                   NaN                   70.00000                 <20% Conventional:Subordinate Lien            2             4             2
        15.69               15.690      35000.0              245000.0                   80.00000             20%-<30% Conventional:Subordinate Lien            2             4             1
       15.625               15.625    1355000.0             2405000.0                        NaN                  NaN       Conventional:First Lien            1             2             2
         15.6               15.600     215000.0                   NaN                   65.00000                 <20% Conventional:Subordinate Lien            2             2             1
         15.6               15.600      65000.0                   NaN                   62.97228                   41 Conventional:Subordinate Lien            2             4             1
         15.6               15.600      45000.0                   NaN                   61.37830                   44 Conventional:Subordinate Lien            2             2             1
         15.6               15.600      75000.0                   NaN                   64.96829             20%-<30% Conventional:Subordinate Lien            2             4             1
         15.5               15.500     145000.0                   NaN                   65.00000                   38 Conventional:Subordinate Lien            2             2             2
         15.5               15.500     145000.0              525000.0                   74.02600                   44 Conventional:Subordinate Lien            2             4             1
         15.5               15.500      45000.0                   NaN                        NaN                  NaN Conventional:Subordinate Lien            2             4             2
         15.5               15.500      95000.0              715000.0                   79.06200                   48 Conventional:Subordinate Lien            2             4             1
         15.5               15.500      85000.0              385000.0                   80.00000                   47 Conventional:Subordinate Lien            2             4             1
         15.5               15.500      65000.0              275000.0                   66.42700                   44 Conventional:Subordinate Lien            2             4             1
        15.49               15.490      45000.0                   NaN                   70.00000                   45 Conventional:Subordinate Lien            2             2             2
       15.375               15.375     105000.0              225000.0                   54.05000                  NaN       Conventional:First Lien            1             2             1
       15.375               15.375     115000.0              465000.0                   58.80000                   42 Conventional:Subordinate Lien            2             4             1
       15.375               15.375     165000.0              495000.0                   67.92200                   49 Conventional:Subordinate Lien            2             4             2
       15.375               15.375     585000.0             1075000.0                   54.51000                  NaN       Conventional:First Lien            1             2             1
        15.35               15.350      65000.0                   NaN                   44.34702                   44 Conventional:Subordinate Lien            2             4             1
        15.35               15.350      75000.0              675000.0                   33.24200                   43 Conventional:Subordinate Lien            2             4             1
        15.35               15.350     255000.0                   NaN                   36.96380             20%-<30% Conventional:Subordinate Lien            2             4             1
         15.3               15.300      35000.0              545000.0                   58.53000                   39 Conventional:Subordinate Lien            2             2             1
         15.3               15.300      45000.0              595000.0                   80.00000                   41 Conventional:Subordinate Lien            2             4             1
        15.25               15.250     135000.0              715000.0                   79.86600                   48 Conventional:Subordinate Lien            2             2             1
        15.25               15.250      65000.0              515000.0                   76.86200             30%-<36% Conventional:Subordinate Lien            2             4             1
        15.25               15.250     155000.0             1185000.0                   80.00000                   47 Conventional:Subordinate Lien            2             4             1
        15.25               15.250     145000.0              765000.0                   76.27800                   37 Conventional:Subordinate Lien            2             4             1
        15.25               15.250     205000.0              455000.0                   70.97900                   36 Conventional:Subordinate Lien            2             4             1
        15.25               15.250      65000.0              385000.0                   63.06900                   46 Conventional:Subordinate Lien            2             4             1
        15.25               15.250      65000.0              335000.0                   79.80800                   44 Conventional:Subordinate Lien            2             2             1
        15.24               15.240      85000.0              545000.0                   79.36000                   49 Conventional:Subordinate Lien            2             4             1
        15.24               15.240      45000.0                   NaN                   69.06625             30%-<36% Conventional:Subordinate Lien            2             4             1
        15.24               15.240      55000.0              395000.0                   80.00000                   46 Conventional:Subordinate Lien            2             4             1
         15.2               15.200      55000.0              345000.0                   67.73000             20%-<30% Conventional:Subordinate Lien            2             4             2
       15.166               15.166      55000.0              275000.0                   80.00000                   40 Conventional:Subordinate Lien            2             1             1
        15.15               15.150      35000.0              215000.0                   50.79000                   46 Conventional:Subordinate Lien            2             4             1
       15.149               15.149      45000.0              205000.0                   79.91800                   49 Conventional:Subordinate Lien            2            32             1
       15.125               15.125      85000.0              275000.0                   71.65000             20%-<30% Conventional:Subordinate Lien            2             2             1
       15.125               15.125      65000.0              315000.0                   51.77000             30%-<36% Conventional:Subordinate Lien            2             2             1
       15.125               15.125      65000.0              325000.0                   58.29800                   44 Conventional:Subordinate Lien            2             4             1
       15.125               15.125     115000.0              315000.0                   68.67000             30%-<36% Conventional:Subordinate Lien            2             4             1
       15.125               15.125      55000.0              455000.0                   64.74000                   43 Conventional:Subordinate Lien            2             2             1
       15.112               15.112      85000.0              395000.0                   79.98300                   47 Conventional:Subordinate Lien            2             1             1
         15.1               15.100      35000.0              505000.0                   64.99000                   45 Conventional:Subordinate Lien            2             4             1
         15.1               15.100     115000.0                   NaN                   75.00000                   37 Conventional:Subordinate Lien            2             4             1
       15.075               15.075      95000.0              665000.0                   79.72500                   40 Conventional:Subordinate Lien            2             4             1
        15.05               15.050     105000.0              435000.0                   76.33000             20%-<30% Conventional:Subordinate Lien            2             4             1
        15.05               15.050     115000.0              335000.0                   65.04000                   49 Conventional:Subordinate Lien            2             4             1
        15.05               15.050     115000.0              245000.0                   75.00000                   44 Conventional:Subordinate Lien            2             4             1
        15.05               15.050      75000.0              295000.0                   48.96000                   39 Conventional:Subordinate Lien            2             4             2
        15.05               15.050      85000.0              345000.0                   67.45000                   49 Conventional:Subordinate Lien            2             2             1
        15.05               15.050     125000.0              665000.0                   73.35000                   38 Conventional:Subordinate Lien            2             4             1
        15.05               15.050      35000.0              615000.0                   75.00000                   45 Conventional:Subordinate Lien            2             2             2

======================================================================
HIGH INTEREST + EXTREME LTV
======================================================================
Records: 0

======================================================================
MISSING VALUES AMONG HIGH INTEREST RECORDS
======================================================================
interest_rate_clean           0
loan_amount                   0
property_value_clean         15
loan_to_value_ratio_clean     2
debt_to_income_ratio         11
dtype: int64

In [50]:
# ==============================================================
# FINAL INTEREST RATE DATA QUALITY TREATMENT
# ==============================================================

# Preserve original interest rate
df['interest_rate_original'] = df['interest_rate']

# Create analysis-ready interest rate
df['interest_rate_analysis_value'] = df['interest_rate_clean'].copy()

# Flag high interest rates
df['high_interest_rate_flag'] = df['interest_rate_clean'] > 15

# Create quality category
df['interest_rate_quality_category'] = 'Valid / Usable'

df.loc[
    df['interest_rate_clean'].isna(),
    'interest_rate_quality_category'
] = 'Missing / Non-numeric'

df.loc[
    df['high_interest_rate_flag'],
    'interest_rate_quality_category'
] = 'High Rate - Retained'

# ==============================================================
# CHECKS
# ==============================================================

print("=" * 70)
print("FINAL INTEREST RATE DATA QUALITY TREATMENT")
print("=" * 70)

print("\nINTEREST RATE QUALITY CATEGORY")
print("-" * 70)
print(df['interest_rate_quality_category'].value_counts())

print("\nHIGH INTEREST RATE FLAG")
print("-" * 70)
print(df['high_interest_rate_flag'].value_counts())

print("\nINTEREST RATE ANALYSIS VALUE")
print("-" * 70)
print(df['interest_rate_analysis_value'].describe())

print("\nORIGINAL INTEREST RATE PRESERVATION CHECK")
print("-" * 70)
print(
    df[
        [
            'interest_rate_original',
            'interest_rate_clean',
            'interest_rate_analysis_value',
            'interest_rate_quality_category'
        ]
    ].head(10)
)

print("\nFINAL INTEREST RATE SUMMARY")
print("-" * 70)
print("Total records:", len(df))
print(
    "Numeric interest rate records:",
    df['interest_rate_clean'].notna().sum()
)
print(
    "Missing / non-numeric:",
    df['interest_rate_clean'].isna().sum()
)
print(
    "High interest rate records (>15%):",
    df['high_interest_rate_flag'].sum()
)
print(
    "Analysis-ready interest rate records:",
    df['interest_rate_analysis_value'].notna().sum()
)

======================================================================
FINAL INTEREST RATE DATA QUALITY TREATMENT
======================================================================

INTEREST RATE QUALITY CATEGORY
----------------------------------------------------------------------
interest_rate_quality_category
Valid / Usable           509879
Missing / Non-numeric    200243
High Rate - Retained         84
Name: count, dtype: int64

HIGH INTEREST RATE FLAG
----------------------------------------------------------------------
high_interest_rate_flag
False    710122
True         84
Name: count, dtype: int64

INTEREST RATE ANALYSIS VALUE
----------------------------------------------------------------------
count    509963.000000
mean          6.787371
std           1.534261
min           0.000000
25%           5.999000
50%           6.625000
75%           7.375000
max          23.000000
Name: interest_rate_analysis_value, dtype: float64

ORIGINAL INTEREST RATE PRESERVATION CHECK
----------------------------------------------------------------------
  interest_rate_original  interest_rate_clean  interest_rate_analysis_value  \
0                   5.75                5.750                         5.750
1                    6.5                6.500                         6.500
2                      6                6.000                         6.000
3                    NaN                  NaN                           NaN
4                   6.99                6.990                         6.990
5                    NaN                  NaN                           NaN
6                  6.375                6.375                         6.375
7                   6.25                6.250                         6.250
8                    6.5                6.500                         6.500
9                   6.49                6.490                         6.490

  interest_rate_quality_category
0                 Valid / Usable
1                 Valid / Usable
2                 Valid / Usable
3          Missing / Non-numeric
4                 Valid / Usable
5          Missing / Non-numeric
6                 Valid / Usable
7                 Valid / Usable
8                 Valid / Usable
9                 Valid / Usable

FINAL INTEREST RATE SUMMARY
----------------------------------------------------------------------
Total records: 710206
Numeric interest rate records: 509963
Missing / non-numeric: 200243
High interest rate records (>15%): 84
Analysis-ready interest rate records: 509963

In [51]:
# ==============================================================
# RATE SPREAD DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("RATE SPREAD DATA QUALITY INVESTIGATION")
print("=" * 70)

# --------------------------------------------------------------
# 1. Check data type
# --------------------------------------------------------------

print("\nRATE SPREAD DTYPE")
print("-" * 70)
print(df['rate_spread'].dtype)


# --------------------------------------------------------------
# 2. Missing values
# --------------------------------------------------------------

missing_rate_spread = df['rate_spread'].isna().sum()

print("\nMISSING VALUES")
print("-" * 70)
print("Missing:", missing_rate_spread)
print(
    "Missing percentage:",
    round(missing_rate_spread / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 3. Exempt values
# --------------------------------------------------------------

exempt_rate_spread = (
    df['rate_spread']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print("\nEXEMPT VALUES")
print("-" * 70)
print("Exempt:", exempt_rate_spread)
print(
    "Exempt percentage:",
    round(exempt_rate_spread / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 4. Convert to numeric helper column
# --------------------------------------------------------------

df['rate_spread_clean'] = pd.to_numeric(
    df['rate_spread'],
    errors='coerce'
)

print("\nNUMERIC RATE SPREAD SUMMARY")
print("-" * 70)
print(df['rate_spread_clean'].describe())


# --------------------------------------------------------------
# 5. Negative values
# --------------------------------------------------------------

negative_rate_spread = df[
    df['rate_spread_clean'] < 0
]

print("\nNEGATIVE RATE SPREAD")
print("-" * 70)
print("Records:", len(negative_rate_spread))

if len(negative_rate_spread) > 0:
    print(
        negative_rate_spread[
            [
                'rate_spread',
                'rate_spread_clean',
                'interest_rate_clean',
                'loan_amount',
                'property_value_clean',
                'derived_loan_product_type',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'rate_spread_clean'
        )
        .head(20)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 6. Zero values
# --------------------------------------------------------------

zero_rate_spread = df[
    df['rate_spread_clean'] == 0
]

print("\nZERO RATE SPREAD")
print("-" * 70)
print("Records:", len(zero_rate_spread))

if len(zero_rate_spread) > 0:
    print(
        zero_rate_spread[
            [
                'rate_spread',
                'interest_rate_clean',
                'loan_amount',
                'property_value_clean',
                'derived_loan_product_type',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .head(10)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 7. Very high rate spread
# --------------------------------------------------------------

high_rate_spread = df[
    df['rate_spread_clean'] > 10
]

print("\nRATE SPREAD > 10")
print("-" * 70)
print("Records:", len(high_rate_spread))
print(
    "Percentage:",
    round(len(high_rate_spread) / len(df) * 100, 4),
    "%"
)

if len(high_rate_spread) > 0:
    print("\nHighest rate spreads:")
    print(
        high_rate_spread[
            [
                'rate_spread',
                'rate_spread_clean',
                'interest_rate_clean',
                'loan_amount',
                'property_value_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'rate_spread_clean',
            ascending=False
        )
        .head(20)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 8. Very low rate spread
# --------------------------------------------------------------

low_rate_spread = df[
    df['rate_spread_clean'] < -10
]

print("\nRATE SPREAD < -10")
print("-" * 70)
print("Records:", len(low_rate_spread))


# --------------------------------------------------------------
# 9. Unique values
# --------------------------------------------------------------

print("\nUNIQUE RATE SPREAD VALUES")
print("-" * 70)
print(
    "Unique numeric values:",
    df['rate_spread_clean'].nunique()
)


# --------------------------------------------------------------
# 10. Missing values in important related fields
# --------------------------------------------------------------

print("\nMISSING VALUES IN IMPORTANT RELATED FIELDS")
print("-" * 70)

print(
    df[
        [
            'rate_spread_clean',
            'interest_rate_clean',
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean'
        ]
    ]
    .isna()
    .sum()
)

======================================================================
RATE SPREAD DATA QUALITY INVESTIGATION
======================================================================

RATE SPREAD DTYPE
----------------------------------------------------------------------
object

MISSING VALUES
----------------------------------------------------------------------
Missing: 229201
Missing percentage: 32.27 %

EXEMPT VALUES
----------------------------------------------------------------------
Exempt: 16346
Exempt percentage: 2.3 %

NUMERIC RATE SPREAD SUMMARY
----------------------------------------------------------------------
count    464659.000000
mean          0.351291
std           2.338775
min        -385.000000
25%          -0.355000
50%           0.220000
75%           0.879000
max         375.000000
Name: rate_spread_clean, dtype: float64

NEGATIVE RATE SPREAD
----------------------------------------------------------------------
Records: 181259
rate_spread  rate_spread_clean  interest_rate_clean  loan_amount  property_value_clean     derived_loan_product_type  loan_purpose  action_taken
       -385            -385.00                 6.00     325000.0              365000.0       Conventional:First Lien             1             1
      -8.26              -8.26                  NaN      95000.0              205000.0 Conventional:Subordinate Lien            31             1
      -8.24              -8.24                 0.00      55000.0              585000.0 Conventional:Subordinate Lien             2             1
      -8.22              -8.22                  NaN      75000.0              395000.0 Conventional:Subordinate Lien             4             1
      -8.19              -8.19                  NaN     135000.0             3205000.0 Conventional:Subordinate Lien             4             1
      -8.18              -8.18                 6.49     105000.0              395000.0 Conventional:Subordinate Lien            32             1
      -8.17              -8.17                  NaN      95000.0              195000.0       Conventional:First Lien             2             1
      -8.14              -8.14                 0.00      25000.0              245000.0 Conventional:Subordinate Lien             2             1
      -8.14              -8.14                 0.00     115000.0              345000.0 Conventional:Subordinate Lien             4             1
      -8.11              -8.11                 0.00       5000.0              185000.0 Conventional:Subordinate Lien             1             1
      -7.84              -7.84                 0.00       5000.0              235000.0 Conventional:Subordinate Lien             1             2
      -7.84              -7.84                 0.00       5000.0              185000.0 Conventional:Subordinate Lien             1             1
      -7.77              -7.77                  NaN       5000.0              225000.0      FSA/RHS:Subordinate Lien             1             2
      -7.74              -7.74                 0.00       5000.0              295000.0       Conventional:First Lien             1             1
       -7.7              -7.70                 0.00       5000.0              335000.0 Conventional:Subordinate Lien             1             1
       -7.6              -7.60                 0.00     155000.0              585000.0 Conventional:Subordinate Lien             2             1
      -7.59              -7.59                 6.50    1025000.0             1365000.0       Conventional:First Lien             1             2
      -7.58              -7.58                  NaN      15000.0              335000.0      FSA/RHS:Subordinate Lien             1             2
      -7.56              -7.56                 0.00       5000.0              205000.0 Conventional:Subordinate Lien             1             1
      -7.49              -7.49                  NaN       5000.0              165000.0      FSA/RHS:Subordinate Lien             1             1

ZERO RATE SPREAD
----------------------------------------------------------------------
Records: 2944
rate_spread  interest_rate_clean  loan_amount  property_value_clean derived_loan_product_type  loan_purpose  action_taken
          0                6.250     255000.0                   NaN             VA:First Lien            31             2
          0                6.250     285000.0              315000.0            FHA:First Lien             1             1
          0                6.625     355000.0              395000.0   Conventional:First Lien             1             1
          0                6.625     505000.0              595000.0   Conventional:First Lien             1             1
        0.0                5.500     425000.0              425000.0            FHA:First Lien             1             1
        0.0                6.500     265000.0              275000.0   Conventional:First Lien             1             1
        0.0                6.125     435000.0              545000.0   Conventional:First Lien             1             1
        0.0                5.875     235000.0              255000.0   Conventional:First Lien             1             1
          0                6.350    1705000.0             2775000.0   Conventional:First Lien            31             1
          0                5.125     325000.0              325000.0            FHA:First Lien             1             1

RATE SPREAD > 10
----------------------------------------------------------------------
Records: 70
Percentage: 0.0099 %

Highest rate spreads:
rate_spread  rate_spread_clean  interest_rate_clean  loan_amount  property_value_clean derived_loan_product_type derived_dwelling_category  loan_purpose  action_taken
      375.0              375.0                9.080    5755000.0            12775000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      375.0              375.0                9.080   37700000.0            47085000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      375.0              375.0                8.531   13000000.0            18575000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      375.0              375.0                9.094   12300000.0            16435000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      287.0              287.0                3.650    5295000.0             8145000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      252.0              252.0                4.290   10500000.0            14005000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      224.0              224.0                4.640    3005000.0             5455000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      221.0              221.0                6.550    1905000.0             2925000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      203.0              203.0                6.350    1405000.0             2165000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      193.0              193.0                4.240    3395000.0             4855000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      193.0              193.0                3.350   38000000.0            54285000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      190.0              190.0                5.540    5365000.0             8245000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      181.0              181.0                5.590   14000000.0            18655000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      181.0              181.0                5.810   17200000.0            22865000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      174.0              174.0                5.550   31100000.0            47845000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      170.0              170.0                6.060   37500000.0            57735000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      162.0              162.0                5.700   12100000.0            16115000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      162.0              162.0                3.440   28000000.0            43105000.0   Conventional:First Lien    Multifamily:Site-Built             4             1
      161.0              161.0                2.470   20400000.0            34005000.0   Conventional:First Lien    Multifamily:Site-Built            31             1
      160.0              160.0                5.690   24600000.0            35175000.0   Conventional:First Lien    Multifamily:Site-Built             4             1

RATE SPREAD < -10
----------------------------------------------------------------------
Records: 1

UNIQUE RATE SPREAD VALUES
----------------------------------------------------------------------
Unique numeric values: 20260

MISSING VALUES IN IMPORTANT RELATED FIELDS
----------------------------------------------------------------------
rate_spread_clean            245547
interest_rate_clean          200243
loan_amount                       0
property_value_clean          43896
loan_to_value_ratio_clean     98182
dtype: int64

In [52]:
# ==============================================================
# RATE SPREAD EXTREME VALUE INVESTIGATION
# ==============================================================

print("=" * 70)
print("RATE SPREAD EXTREME VALUE INVESTIGATION")
print("=" * 70)

# --------------------------------------------------------------
# 1. Extremely negative rate spread
# --------------------------------------------------------------

extreme_negative = df[
    df['rate_spread_clean'] < -10
].copy()

print("\nEXTREME NEGATIVE RATE SPREAD (< -10)")
print("-" * 70)
print("Records:", len(extreme_negative))

if len(extreme_negative) > 0:
    print(
        extreme_negative[
            [
                'rate_spread',
                'rate_spread_clean',
                'interest_rate_clean',
                'loan_amount',
                'property_value_clean',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'lien_status',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'rate_spread_clean'
        )
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 2. Extremely positive rate spread
# --------------------------------------------------------------

extreme_positive = df[
    df['rate_spread_clean'] > 10
].copy()

print("\n" + "=" * 70)
print("EXTREME POSITIVE RATE SPREAD (> 10)")
print("=" * 70)

print("Records:", len(extreme_positive))

print(
    extreme_positive[
        [
            'rate_spread',
            'rate_spread_clean',
            'interest_rate_clean',
            'loan_amount',
            'property_value_clean',
            'loan_to_value_ratio_clean',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'lien_status',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'rate_spread_clean',
        ascending=False
    )
    .head(30)
    .to_string(index=False)
)


# --------------------------------------------------------------
# 3. Rate spread distribution by loan product
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("RATE SPREAD BY LOAN PRODUCT")
print("=" * 70)

print(
    df[
        df['rate_spread_clean'].notna()
    ]
    .groupby('derived_loan_product_type')['rate_spread_clean']
    .agg([
        'count',
        'min',
        'median',
        'max'
    ])
    .sort_values('count', ascending=False)
)


# --------------------------------------------------------------
# 4. Count of very unusual values
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("RATE SPREAD THRESHOLD CHECK")
print("=" * 70)

for threshold in [5, 10, 25, 50, 100, 200, 300]:
    count = (
        df['rate_spread_clean'].abs() > threshold
    ).sum()

    print(
        f"|Rate Spread| > {threshold}: "
        f"{count} records "
        f"({count / len(df) * 100:.4f}%)"
    )


# --------------------------------------------------------------
# 5. Check whether extreme rate spread overlaps with
#    extreme LTV
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("RATE SPREAD + EXTREME LTV")
print("=" * 70)

spread_ltv_overlap = df[
    (df['rate_spread_clean'].abs() > 10) &
    (df['extreme_ltv_flag'])
]

print("Records:", len(spread_ltv_overlap))

if len(spread_ltv_overlap) > 0:
    print(
        spread_ltv_overlap[
            [
                'rate_spread_clean',
                'interest_rate_clean',
                'loan_amount',
                'property_value_clean',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'action_taken'
            ]
        ]
        .sort_values(
            'rate_spread_clean'
        )
        .head(20)
        .to_string(index=False)
    )

======================================================================
RATE SPREAD EXTREME VALUE INVESTIGATION
======================================================================

EXTREME NEGATIVE RATE SPREAD (< -10)
----------------------------------------------------------------------
Records: 1
rate_spread  rate_spread_clean  interest_rate_clean  loan_amount  property_value_clean  loan_to_value_ratio_clean derived_loan_product_type            derived_dwelling_category  lien_status  loan_purpose  action_taken
       -385             -385.0                  6.0     325000.0              365000.0                     89.041   Conventional:First Lien Single Family (1-4 Units):Site-Built            1             1             1

======================================================================
EXTREME POSITIVE RATE SPREAD (> 10)
======================================================================
Records: 70
rate_spread  rate_spread_clean  interest_rate_clean  loan_amount  property_value_clean  loan_to_value_ratio_clean derived_loan_product_type derived_dwelling_category  lien_status  loan_purpose  action_taken
      375.0              375.0                9.080    5755000.0            12775000.0                       45.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      375.0              375.0                9.080   37700000.0            47085000.0                       80.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      375.0              375.0                8.531   13000000.0            18575000.0                       70.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      375.0              375.0                9.094   12300000.0            16435000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      287.0              287.0                3.650    5295000.0             8145000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      252.0              252.0                4.290   10500000.0            14005000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      224.0              224.0                4.640    3005000.0             5455000.0                       55.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      221.0              221.0                6.550    1905000.0             2925000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      203.0              203.0                6.350    1405000.0             2165000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      193.0              193.0                4.240    3395000.0             4855000.0                       70.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      193.0              193.0                3.350   38000000.0            54285000.0                       70.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      190.0              190.0                5.540    5365000.0             8245000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      181.0              181.0                5.590   14000000.0            18655000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      181.0              181.0                5.810   17200000.0            22865000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      174.0              174.0                5.550   31100000.0            47845000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      170.0              170.0                6.060   37500000.0            57735000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      162.0              162.0                5.700   12100000.0            16115000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      162.0              162.0                3.440   28000000.0            43105000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      161.0              161.0                2.470   20400000.0            34005000.0                       60.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      160.0              160.0                5.690   24600000.0            35175000.0                       70.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      158.0              158.0                5.380   19700000.0            24685000.0                       80.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      157.0              157.0                5.690   13900000.0            19915000.0                       70.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      154.0              154.0                5.750   43700000.0            67295000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      152.0              152.0                5.410   23300000.0            31065000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      149.0              149.0                4.960   14300000.0            22005000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      139.0              139.0                6.060   53000000.0            81535000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      130.0              130.0                5.550   14400000.0            22165000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1            31             1
      129.0              129.0                4.330   30300000.0            46685000.0                       65.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      117.0              117.0                5.400   47500000.0            67835000.0                       70.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1
      116.0              116.0                5.660   60500000.0            80625000.0                       75.0   Conventional:First Lien    Multifamily:Site-Built            1             4             1

======================================================================
RATE SPREAD BY LOAN PRODUCT
======================================================================
                                count      min  median      max
derived_loan_product_type
Conventional:First Lien        264294 -385.000   0.261  375.000
FHA:First Lien                  97416   -6.880   0.280    3.935
VA:First Lien                   53445   -5.550  -0.588    3.399
Conventional:Subordinate Lien   47267   -8.260   1.205   24.873
FSA/RHS:First Lien               1547   -2.437  -0.017    2.708
FSA/RHS:Subordinate Lien          672   -7.770  -6.650    3.453
FHA:Subordinate Lien               18   -7.050   2.622    7.451

======================================================================
RATE SPREAD THRESHOLD CHECK
======================================================================
|Rate Spread| > 5: 9392 records (1.3224%)
|Rate Spread| > 10: 71 records (0.0100%)
|Rate Spread| > 25: 34 records (0.0048%)
|Rate Spread| > 50: 34 records (0.0048%)
|Rate Spread| > 100: 32 records (0.0045%)
|Rate Spread| > 200: 10 records (0.0014%)
|Rate Spread| > 300: 5 records (0.0007%)

======================================================================
RATE SPREAD + EXTREME LTV
======================================================================
Records: 0

In [53]:
# ==============================================================
# FINAL RATE SPREAD DATA QUALITY TREATMENT
# ==============================================================

# --------------------------------------------------------------
# 1. Preserve original column
# --------------------------------------------------------------

df['rate_spread_original'] = df['rate_spread']


# --------------------------------------------------------------
# 2. Create analysis-ready rate spread
# --------------------------------------------------------------

df['rate_spread_analysis_value'] = df['rate_spread_clean'].copy()


# --------------------------------------------------------------
# 3. Flag extreme rate spreads
# --------------------------------------------------------------

df['extreme_rate_spread_flag'] = (
    df['rate_spread_clean'].abs() > 25
)


# --------------------------------------------------------------
# 4. Flag confirmed anomaly
# --------------------------------------------------------------

df['rate_spread_anomaly_flag'] = (
    df['rate_spread_clean'] == -385
)


# --------------------------------------------------------------
# 5. Exclude confirmed anomaly from analysis field
# --------------------------------------------------------------

df.loc[
    df['rate_spread_anomaly_flag'],
    'rate_spread_analysis_value'
] = np.nan


# --------------------------------------------------------------
# 6. Create quality category
# --------------------------------------------------------------

df['rate_spread_quality_category'] = 'Valid / Usable'

df.loc[
    df['rate_spread_clean'].isna(),
    'rate_spread_quality_category'
] = 'Missing / Non-numeric'

df.loc[
    df['extreme_rate_spread_flag'],
    'rate_spread_quality_category'
] = 'Extreme Value - Retained'

df.loc[
    df['rate_spread_anomaly_flag'],
    'rate_spread_quality_category'
] = 'Confirmed Anomaly - Excluded'


# --------------------------------------------------------------
# 7. Verification
# --------------------------------------------------------------

print("=" * 70)
print("FINAL RATE SPREAD DATA QUALITY TREATMENT")
print("=" * 70)

print("\nRATE SPREAD QUALITY CATEGORY")
print("-" * 70)
print(
    df['rate_spread_quality_category']
    .value_counts()
)


print("\nEXTREME RATE SPREAD FLAG")
print("-" * 70)
print(
    df['extreme_rate_spread_flag']
    .value_counts()
)


print("\nCONFIRMED ANOMALY FLAG")
print("-" * 70)
print(
    df['rate_spread_anomaly_flag']
    .value_counts()
)


print("\nRATE SPREAD ANALYSIS VALUE")
print("-" * 70)
print(
    df['rate_spread_analysis_value'].describe()
)


print("\nORIGINAL RATE SPREAD PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'rate_spread_original',
            'rate_spread_clean',
            'rate_spread_analysis_value',
            'rate_spread_quality_category'
        ]
    ]
    .head(10)
)


print("\nFINAL RATE SPREAD SUMMARY")
print("-" * 70)

print("Total records:", len(df))

print(
    "Numeric rate spread records:",
    df['rate_spread_clean'].notna().sum()
)

print(
    "Missing / non-numeric:",
    df['rate_spread_clean'].isna().sum()
)

print(
    "Extreme rate spread records (|spread| > 25):",
    df['extreme_rate_spread_flag'].sum()
)

print(
    "Confirmed anomaly records:",
    df['rate_spread_anomaly_flag'].sum()
)

print(
    "Analysis-ready rate spread records:",
    df['rate_spread_analysis_value'].notna().sum()
)

print(
    "Excluded from rate-spread analysis:",
    df['rate_spread_analysis_value'].isna().sum()
)

======================================================================
FINAL RATE SPREAD DATA QUALITY TREATMENT
======================================================================

RATE SPREAD QUALITY CATEGORY
----------------------------------------------------------------------
rate_spread_quality_category
Valid / Usable                  464625
Missing / Non-numeric           245547
Extreme Value - Retained            33
Confirmed Anomaly - Excluded         1
Name: count, dtype: int64

EXTREME RATE SPREAD FLAG
----------------------------------------------------------------------
extreme_rate_spread_flag
False    710172
True         34
Name: count, dtype: int64

CONFIRMED ANOMALY FLAG
----------------------------------------------------------------------
rate_spread_anomaly_flag
False    710205
True          1
Name: count, dtype: int64

RATE SPREAD ANALYSIS VALUE
----------------------------------------------------------------------
count    464658.000000
mean          0.352120
std           2.269427
min          -8.260000
25%          -0.355000
50%           0.220000
75%           0.879000
max         375.000000
Name: rate_spread_analysis_value, dtype: float64

ORIGINAL RATE SPREAD PRESERVATION CHECK
----------------------------------------------------------------------
  rate_spread_original  rate_spread_clean  rate_spread_analysis_value  \
0               -0.924             -0.924                      -0.924
1               -0.339             -0.339                      -0.339
2               -0.725             -0.725                      -0.725
3                  NaN                NaN                         NaN
4                0.156              0.156                       0.156
5                  NaN                NaN                         NaN
6               -0.368             -0.368                      -0.368
7               -0.508             -0.508                      -0.508
8                -0.29             -0.290                      -0.290
9                0.493              0.493                       0.493

  rate_spread_quality_category
0               Valid / Usable
1               Valid / Usable
2               Valid / Usable
3        Missing / Non-numeric
4               Valid / Usable
5        Missing / Non-numeric
6               Valid / Usable
7               Valid / Usable
8               Valid / Usable
9               Valid / Usable

FINAL RATE SPREAD SUMMARY
----------------------------------------------------------------------
Total records: 710206
Numeric rate spread records: 464659
Missing / non-numeric: 245547
Extreme rate spread records (|spread| > 25): 34
Confirmed anomaly records: 1
Analysis-ready rate spread records: 464658
Excluded from rate-spread analysis: 245548

In [54]:
# ==============================================================
# PROPERTY VALUE DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("PROPERTY VALUE DATA QUALITY INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Check data type
# --------------------------------------------------------------

print("\nPROPERTY VALUE DTYPE")
print("-" * 70)
print(df['property_value'].dtype)


# --------------------------------------------------------------
# 2. Missing values
# --------------------------------------------------------------

missing_property = df['property_value'].isna().sum()

print("\nMISSING VALUES")
print("-" * 70)
print("Missing:", missing_property)
print(
    "Missing percentage:",
    round(missing_property / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 3. Exempt values
# --------------------------------------------------------------

exempt_property = (
    df['property_value']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print("\nEXEMPT VALUES")
print("-" * 70)
print("Exempt:", exempt_property)
print(
    "Exempt percentage:",
    round(exempt_property / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 4. Numeric property value summary
# --------------------------------------------------------------

print("\nNUMERIC PROPERTY VALUE SUMMARY")
print("-" * 70)

print(
    df['property_value_clean'].describe()
)


# --------------------------------------------------------------
# 5. Negative property values
# --------------------------------------------------------------

negative_property = df[
    df['property_value_clean'] < 0
]

print("\nNEGATIVE PROPERTY VALUES")
print("-" * 70)
print("Records:", len(negative_property))


# --------------------------------------------------------------
# 6. Zero property values
# --------------------------------------------------------------

zero_property = df[
    df['property_value_clean'] == 0
]

print("\nZERO PROPERTY VALUES")
print("-" * 70)
print("Records:", len(zero_property))


# --------------------------------------------------------------
# 7. Very high property values
# --------------------------------------------------------------

high_property = df[
    df['property_value_clean'] > 10_000_000
].copy()

print("\nPROPERTY VALUE > $10 MILLION")
print("-" * 70)
print("Records:", len(high_property))
print(
    "Percentage:",
    round(len(high_property) / len(df) * 100, 4),
    "%"
)

print("\nHighest property values:")

print(
    high_property[
        [
            'property_value_clean',
            'loan_amount',
            'loan_to_value_ratio_clean',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'property_value_clean',
        ascending=False
    )
    .head(30)
    .to_string(index=False)
)


# --------------------------------------------------------------
# 8. Property values above $100 million
# --------------------------------------------------------------

very_high_property = df[
    df['property_value_clean'] > 100_000_000
].copy()

print("\n" + "=" * 70)
print("PROPERTY VALUE > $100 MILLION")
print("=" * 70)

print("Records:", len(very_high_property))

print(
    very_high_property[
        [
            'property_value_clean',
            'loan_amount',
            'loan_to_value_ratio_clean',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'property_value_clean',
        ascending=False
    )
    .head(30)
    .to_string(index=False)
)


# --------------------------------------------------------------
# 9. Property value by dwelling category
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("PROPERTY VALUE BY DWELLING CATEGORY")
print("=" * 70)

print(
    df[
        df['property_value_clean'].notna()
    ]
    .groupby('derived_dwelling_category')['property_value_clean']
    .agg([
        'count',
        'min',
        'median',
        'max'
    ])
    .sort_values(
        'count',
        ascending=False
    )
)


# --------------------------------------------------------------
# 10. Extreme property value + single-family check
# --------------------------------------------------------------

single_family_extreme = df[
    (df['property_value_clean'] > 100_000_000) &
    (
        df['derived_dwelling_category']
        .astype(str)
        .str.contains('Single Family', na=False)
    )
].copy()

print("\n" + "=" * 70)
print("SINGLE-FAMILY PROPERTY VALUE > $100 MILLION")
print("=" * 70)

print("Records:", len(single_family_extreme))

if len(single_family_extreme) > 0:
    print(
        single_family_extreme[
            [
                'property_value_clean',
                'loan_amount',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'total_units_clean',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'property_value_clean',
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 11. Extreme property value + extreme LTV
# --------------------------------------------------------------

property_ltv_overlap = df[
    (df['property_value_clean'] > 10_000_000) &
    (df['extreme_ltv_flag'])
].copy()

print("\n" + "=" * 70)
print("PROPERTY VALUE > $10M + EXTREME LTV")
print("=" * 70)

print("Records:", len(property_ltv_overlap))

if len(property_ltv_overlap) > 0:
    print(
        property_ltv_overlap[
            [
                'property_value_clean',
                'loan_amount',
                'loan_to_value_ratio_clean',
                'calculated_ltv',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'total_units_clean',
                'action_taken'
            ]
        ]
        .sort_values(
            'property_value_clean',
            ascending=False
        )
        .head(20)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 12. Loan-to-property relationship
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOAN / PROPERTY VALUE RELATIONSHIP")
print("=" * 70)

valid_relationship = df[
    (df['loan_amount'] > 0) &
    (df['property_value_clean'] > 0)
].copy()

valid_relationship['calculated_ltv_check'] = (
    valid_relationship['loan_amount']
    / valid_relationship['property_value_clean']
    * 100
)

print(
    valid_relationship['calculated_ltv_check'].describe()
)

======================================================================
PROPERTY VALUE DATA QUALITY INVESTIGATION
======================================================================

PROPERTY VALUE DTYPE
----------------------------------------------------------------------
object

MISSING VALUES
----------------------------------------------------------------------
Missing: 27186
Missing percentage: 3.83 %

EXEMPT VALUES
----------------------------------------------------------------------
Exempt: 16710
Exempt percentage: 2.35 %

NUMERIC PROPERTY VALUE SUMMARY
----------------------------------------------------------------------
count    6.663100e+05
mean     4.777222e+05
std      4.924089e+06
min      5.000000e+03
25%      2.450000e+05
50%      3.350000e+05
75%      4.950000e+05
max      1.838005e+09
Name: property_value_clean, dtype: float64

NEGATIVE PROPERTY VALUES
----------------------------------------------------------------------
Records: 0

ZERO PROPERTY VALUES
----------------------------------------------------------------------
Records: 0

PROPERTY VALUE > $10 MILLION
----------------------------------------------------------------------
Records: 615
Percentage: 0.0866 %

Highest property values:
 property_value_clean  loan_amount  loan_to_value_ratio_clean     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
         1838005000.0  119000000.0                     65.000       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
         1581075000.0   62000000.0                     51.480       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
         1576125000.0   60000000.0                     47.900       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
         1576125000.0   70000000.0                     47.900       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
         1050005000.0       5000.0                        NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 2             1             3
          837155000.0   11200000.0                   7500.000       Conventional:First Lien               Multifamily:Site-Built           100-149             2             3
          734705000.0  148000000.0                     67.210       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
          450005000.0     325000.0                      0.071                 VA:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
          447545000.0  260000000.0                     58.090       Conventional:First Lien               Multifamily:Site-Built              >149             5             1
          439705000.0  238000000.0                     54.070       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          387005000.0     125000.0                      0.031       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
          350885000.0   92000000.0                     52.800       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          350885000.0   28000000.0                      7.994       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          331805000.0  211000000.0                     63.500       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
          313965000.0      75000.0                      0.054 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1            31             3
          300005000.0      95000.0                     80.000       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             1
          300005000.0     305000.0                      0.100       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
          280005000.0      25000.0                      0.060 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
          240005000.0      45000.0                      0.060 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
          186895000.0   14000000.0                     67.280       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
          173795000.0      55000.0                     28.770       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
          162005000.0  101000000.0                     62.100       Conventional:First Lien               Multifamily:Site-Built             50-99             1             1
          161105000.0    1005000.0                     63.900       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          149745000.0   47800000.0                        NaN                FHA:First Lien               Multifamily:Site-Built              >149             1             3
          135405000.0   74600000.0                     55.080       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          131235000.0   58500000.0                     44.604       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          128805000.0   60900000.0                     47.310       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
          126805000.0   11700000.0                     62.300 Conventional:Subordinate Lien               Multifamily:Site-Built              >149             2             1
          119605000.0   70700000.0                     59.120       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          115005000.0   78400000.0                     68.200       Conventional:First Lien               Multifamily:Site-Built              >149            31             1

======================================================================
PROPERTY VALUE > $100 MILLION
======================================================================
Records: 46
 property_value_clean  loan_amount  loan_to_value_ratio_clean     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
         1838005000.0  119000000.0                     65.000       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
         1581075000.0   62000000.0                     51.480       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
         1576125000.0   70000000.0                     47.900       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
         1576125000.0   60000000.0                     47.900       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
         1050005000.0       5000.0                        NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 2             1             3
          837155000.0   11200000.0                   7500.000       Conventional:First Lien               Multifamily:Site-Built           100-149             2             3
          734705000.0  148000000.0                     67.210       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
          450005000.0     325000.0                      0.071                 VA:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
          447545000.0  260000000.0                     58.090       Conventional:First Lien               Multifamily:Site-Built              >149             5             1
          439705000.0  238000000.0                     54.070       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          387005000.0     125000.0                      0.031       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
          350885000.0   92000000.0                     52.800       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          350885000.0   28000000.0                      7.994       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          331805000.0  211000000.0                     63.500       Conventional:First Lien               Multifamily:Site-Built              >149            32             1
          313965000.0      75000.0                      0.054 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1            31             3
          300005000.0      95000.0                     80.000       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             1
          300005000.0     305000.0                      0.100       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
          280005000.0      25000.0                      0.060 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
          240005000.0      45000.0                      0.060 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
          186895000.0   14000000.0                     67.280       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
          173795000.0      55000.0                     28.770       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
          162005000.0  101000000.0                     62.100       Conventional:First Lien               Multifamily:Site-Built             50-99             1             1
          161105000.0    1005000.0                     63.900       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          149745000.0   47800000.0                        NaN                FHA:First Lien               Multifamily:Site-Built              >149             1             3
          135405000.0   74600000.0                     55.080       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          131235000.0   58500000.0                     44.604       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          128805000.0   60900000.0                     47.310       Conventional:First Lien               Multifamily:Site-Built              >149             1             1
          126805000.0   11700000.0                     62.300 Conventional:Subordinate Lien               Multifamily:Site-Built              >149             2             1
          119605000.0   70700000.0                     59.120       Conventional:First Lien               Multifamily:Site-Built              >149            31             1
          115005000.0   78400000.0                     68.200       Conventional:First Lien               Multifamily:Site-Built              >149            31             1

======================================================================
PROPERTY VALUE BY DWELLING CATEGORY
======================================================================
                                         count      min     median  \
derived_dwelling_category
Single Family (1-4 Units):Site-Built    601331   5000.0   355000.0
Single Family (1-4 Units):Manufactured   63612   5000.0   125000.0
Multifamily:Site-Built                    1325   5000.0  5425000.0
Multifamily:Manufactured                    42  85000.0  2325000.0

                                                 max
derived_dwelling_category
Single Family (1-4 Units):Site-Built    1.050005e+09
Single Family (1-4 Units):Manufactured  7.775000e+06
Multifamily:Site-Built                  1.838005e+09
Multifamily:Manufactured                4.260500e+07

======================================================================
SINGLE-FAMILY PROPERTY VALUE > $100 MILLION
======================================================================
Records: 11
 property_value_clean  loan_amount  loan_to_value_ratio_clean     derived_loan_product_type            derived_dwelling_category total_units_clean  loan_purpose  action_taken
         1050005000.0       5000.0                        NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built                 2             1             3
          450005000.0     325000.0                      0.071                 VA:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
          387005000.0     125000.0                      0.031       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             3
          313965000.0      75000.0                      0.054 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1            31             3
          300005000.0     305000.0                      0.100       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             4             3
          300005000.0      95000.0                     80.000       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1             1             1
          280005000.0      25000.0                      0.060 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             2             3
          240005000.0      45000.0                      0.060 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
          173795000.0      55000.0                     28.770       Conventional:First Lien Single Family (1-4 Units):Site-Built                 1            32             1
          100005000.0      55000.0                      0.677 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3
          100005000.0     105000.0                     59.390 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built                 1             4             3

======================================================================
PROPERTY VALUE > $10M + EXTREME LTV
======================================================================
Records: 1
 property_value_clean  loan_amount  loan_to_value_ratio_clean  calculated_ltv derived_loan_product_type derived_dwelling_category total_units_clean  action_taken
          837155000.0   11200000.0                     7500.0        1.337865   Conventional:First Lien    Multifamily:Site-Built           100-149             3

======================================================================
LOAN / PROPERTY VALUE RELATIONSHIP
======================================================================
count    666310.000000
mean         73.131064
std          65.222214
min           0.000476
25%          55.056180
50%          80.281690
75%          96.610169
max       18100.000000
Name: calculated_ltv_check, dtype: float64

In [55]:
# ==============================================================
# FINAL PROPERTY VALUE DATA QUALITY TREATMENT
# ==============================================================

# 1. Preserve original
df['property_value_original'] = df['property_value']


# 2. Create analysis-ready field
df['property_value_analysis_value'] = (
    df['property_value_clean'].copy()
)


# 3. Flag suspicious single-family extreme values
df['property_value_anomaly_flag'] = (
    (df['property_value_clean'] > 100_000_000) &
    (
        df['derived_dwelling_category']
        .astype(str)
        .str.contains('Single Family', na=False)
    )
)


# 4. Exclude suspicious single-family extremes
df.loc[
    df['property_value_anomaly_flag'],
    'property_value_analysis_value'
] = np.nan


# 5. Create quality category
df['property_value_quality_category'] = 'Valid / Usable'

df.loc[
    df['property_value_clean'].isna(),
    'property_value_quality_category'
] = 'Missing / Non-numeric'

df.loc[
    df['property_value_anomaly_flag'],
    'property_value_quality_category'
] = 'Suspicious Extreme - Excluded'


# 6. Verification
print("=" * 70)
print("FINAL PROPERTY VALUE DATA QUALITY TREATMENT")
print("=" * 70)

print("\nPROPERTY VALUE QUALITY CATEGORY")
print("-" * 70)
print(
    df['property_value_quality_category']
    .value_counts()
)

print("\nPROPERTY VALUE ANOMALY FLAG")
print("-" * 70)
print(
    df['property_value_anomaly_flag']
    .value_counts()
)

print("\nPROPERTY VALUE ANALYSIS VALUE")
print("-" * 70)
print(
    df['property_value_analysis_value'].describe()
)

print("\nORIGINAL PROPERTY VALUE PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'property_value_original',
            'property_value_clean',
            'property_value_analysis_value',
            'property_value_quality_category'
        ]
    ].head(10)
)

print("\nFINAL PROPERTY VALUE SUMMARY")
print("-" * 70)

print("Total records:", len(df))

print(
    "Numeric property value records:",
    df['property_value_clean'].notna().sum()
)

print(
    "Missing / non-numeric:",
    df['property_value_clean'].isna().sum()
)

print(
    "Suspicious single-family extremes:",
    df['property_value_anomaly_flag'].sum()
)

print(
    "Analysis-ready property values:",
    df['property_value_analysis_value'].notna().sum()
)

print(
    "Excluded from property-value analysis:",
    df['property_value_analysis_value'].isna().sum()
)

======================================================================
FINAL PROPERTY VALUE DATA QUALITY TREATMENT
======================================================================

PROPERTY VALUE QUALITY CATEGORY
----------------------------------------------------------------------
property_value_quality_category
Valid / Usable                   666299
Missing / Non-numeric             43896
Suspicious Extreme - Excluded        11
Name: count, dtype: int64

PROPERTY VALUE ANOMALY FLAG
----------------------------------------------------------------------
property_value_anomaly_flag
False    710195
True         11
Name: count, dtype: int64

PROPERTY VALUE ANALYSIS VALUE
----------------------------------------------------------------------
count    6.662990e+05
mean     4.721848e+05
std      4.622916e+06
min      5.000000e+03
25%      2.450000e+05
50%      3.350000e+05
75%      4.950000e+05
max      1.838005e+09
Name: property_value_analysis_value, dtype: float64

ORIGINAL PROPERTY VALUE PRESERVATION CHECK
----------------------------------------------------------------------
  property_value_original  property_value_clean  \
0                  335000              335000.0
1                     NaN                   NaN
2                     NaN                   NaN
3                  705000              705000.0
4                     NaN                   NaN
5                     NaN                   NaN
6                     NaN                   NaN
7                     NaN                   NaN
8                     NaN                   NaN
9                  635000              635000.0

   property_value_analysis_value property_value_quality_category
0                       335000.0                  Valid / Usable
1                            NaN           Missing / Non-numeric
2                            NaN           Missing / Non-numeric
3                       705000.0                  Valid / Usable
4                            NaN           Missing / Non-numeric
5                            NaN           Missing / Non-numeric
6                            NaN           Missing / Non-numeric
7                            NaN           Missing / Non-numeric
8                            NaN           Missing / Non-numeric
9                       635000.0                  Valid / Usable

FINAL PROPERTY VALUE SUMMARY
----------------------------------------------------------------------
Total records: 710206
Numeric property value records: 666310
Missing / non-numeric: 43896
Suspicious single-family extremes: 11
Analysis-ready property values: 666299
Excluded from property-value analysis: 43907

In [56]:

# ==============================================================
# DEBT-TO-INCOME RATIO DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("DEBT-TO-INCOME RATIO DATA QUALITY INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Basic information
# --------------------------------------------------------------

print("\nDTI DTYPE")
print("-" * 70)
print(df['debt_to_income_ratio'].dtype)


# --------------------------------------------------------------
# 2. Missing values
# --------------------------------------------------------------

missing_dti = df['debt_to_income_ratio'].isna().sum()

print("\nMISSING VALUES")
print("-" * 70)
print("Missing:", missing_dti)
print(
    "Missing percentage:",
    round(missing_dti / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 3. Exempt values
# --------------------------------------------------------------

exempt_dti = (
    df['debt_to_income_ratio']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print("\nEXEMPT VALUES")
print("-" * 70)
print("Exempt:", exempt_dti)
print(
    "Exempt percentage:",
    round(exempt_dti / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 4. Complete value distribution
# --------------------------------------------------------------

print("\nDTI VALUE DISTRIBUTION")
print("-" * 70)

print(
    df['debt_to_income_ratio']
    .value_counts(dropna=False)
    .to_string()
)


# --------------------------------------------------------------
# 5. Separate exact numeric DTI values
# --------------------------------------------------------------

dti_numeric = pd.to_numeric(
    df['debt_to_income_ratio'],
    errors='coerce'
)

print("\nNUMERIC DTI SUMMARY")
print("-" * 70)

print(
    dti_numeric.describe()
)


# --------------------------------------------------------------
# 6. Negative numeric DTI
# --------------------------------------------------------------

negative_dti = df[
    dti_numeric < 0
]

print("\nNEGATIVE DTI")
print("-" * 70)
print("Records:", len(negative_dti))


# --------------------------------------------------------------
# 7. Numeric DTI above 100
# --------------------------------------------------------------

dti_above_100 = df[
    dti_numeric > 100
]

print("\nNUMERIC DTI > 100")
print("-" * 70)
print("Records:", len(dti_above_100))

if len(dti_above_100) > 0:
    print(
        dti_above_100[
            [
                'debt_to_income_ratio',
                'income',
                'loan_amount',
                'property_value_analysis_value',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'action_taken'
            ]
        ]
        .head(30)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 8. Exact numeric DTI values
# --------------------------------------------------------------

print("\nEXACT NUMERIC DTI VALUES")
print("-" * 70)

print(
    dti_numeric
    .dropna()
    .value_counts()
    .sort_index()
    .to_string()
)


# --------------------------------------------------------------
# 9. Identify DTI range categories
# --------------------------------------------------------------

print("\nDTI RANGE CATEGORIES")
print("-" * 70)

range_values = [
    '<20%',
    '20%-<30%',
    '30%-<36%',
    '50%-60%',
    '>60%'
]

for value in range_values:
    count = (
        df['debt_to_income_ratio']
        .astype(str)
        .eq(value)
        .sum()
    )

    print(
        f"{value:<15} {count:>10,}"
    )


# --------------------------------------------------------------
# 10. DTI distribution by loan product
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("DTI BY LOAN PRODUCT")
print("=" * 70)

print(
    df[
        df['debt_to_income_ratio'].notna()
    ]
    .groupby('derived_loan_product_type')
    ['debt_to_income_ratio']
    .value_counts()
    .groupby(level=0)
    .head(10)
)


# --------------------------------------------------------------
# 11. DTI distribution by action taken
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("DTI BY ACTION TAKEN")
print("=" * 70)

print(
    df[
        df['debt_to_income_ratio'].notna()
    ]
    .groupby('action_taken')
    ['debt_to_income_ratio']
    .value_counts()
    .groupby(level=0)
    .head(10)
)


# --------------------------------------------------------------
# 12. Missing/Exempt DTI with action taken
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING / EXEMPT DTI BY ACTION")
print("=" * 70)

dti_missing_or_exempt = df[
    df['debt_to_income_ratio'].isna() |
    (
        df['debt_to_income_ratio']
        .astype(str)
        .eq('Exempt')
    )
]

print(
    dti_missing_or_exempt['action_taken']
    .value_counts()
)


# --------------------------------------------------------------
# 13. DTI + income relationship
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("DTI + INCOME DATA QUALITY")
print("=" * 70)

dti_income_check = df[
    dti_numeric.notna() &
    df['income'].notna()
].copy()

print("Records with numeric DTI and income:",
      len(dti_income_check))

print("\nIncome summary:")
print(
    dti_income_check['income'].describe()
)


# --------------------------------------------------------------
# 14. DTI + extreme LTV overlap
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("DTI + EXTREME LTV OVERLAP")
print("=" * 70)

dti_ltv_overlap = df[
    dti_numeric.notna() &
    df['extreme_ltv_flag']
]

print("Records:", len(dti_ltv_overlap))

if len(dti_ltv_overlap) > 0:
    print(
        dti_ltv_overlap[
            [
                'debt_to_income_ratio',
                'loan_amount',
                'property_value_analysis_value',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'action_taken'
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

======================================================================
DEBT-TO-INCOME RATIO DATA QUALITY INVESTIGATION
======================================================================

DTI DTYPE
----------------------------------------------------------------------
str

MISSING VALUES
----------------------------------------------------------------------
Missing: 53332
Missing percentage: 7.51 %

EXEMPT VALUES
----------------------------------------------------------------------
Exempt: 16810
Exempt percentage: 2.37 %

DTI VALUE DISTRIBUTION
----------------------------------------------------------------------
debt_to_income_ratio
50%-60%     83713
30%-<36%    83270
20%-<30%    76278
>60%        54057
NaN         53332
<20%        33308
49          31453
44          25959
42          24575
43          23358
48          22480
41          22236
47          22077
45          21436
40          20807
46          20735
39          20353
38          18942
37          17910
36          17117
Exempt      16810

NUMERIC DTI SUMMARY
----------------------------------------------------------------------
count    309438.000000
mean         42.953441
std           3.990969
min          36.000000
25%          40.000000
50%          43.000000
75%          46.000000
max          49.000000
Name: debt_to_income_ratio, dtype: float64

NEGATIVE DTI
----------------------------------------------------------------------
Records: 0

NUMERIC DTI > 100
----------------------------------------------------------------------
Records: 0

EXACT NUMERIC DTI VALUES
----------------------------------------------------------------------
debt_to_income_ratio
36.0    17117
37.0    17910
38.0    18942
39.0    20353
40.0    20807
41.0    22236
42.0    24575
43.0    23358
44.0    25959
45.0    21436
46.0    20735
47.0    22077
48.0    22480
49.0    31453

DTI RANGE CATEGORIES
----------------------------------------------------------------------
<20%                33,308
20%-<30%            76,278
30%-<36%            83,270
50%-60%             83,713
>60%                54,057

======================================================================
DTI BY LOAN PRODUCT
======================================================================
derived_loan_product_type  debt_to_income_ratio
Conventional:First Lien    30%-<36%                56465
                           20%-<30%                56165
                           >60%                    29772
                           <20%                    25904
                           49                      21287
                                                   ...
VA:First Lien              47                       1852
                           48                       1801
                           46                       1667
                           45                       1662
                           43                       1628
Name: count, Length: 70, dtype: int64

======================================================================
DTI BY ACTION TAKEN
======================================================================
action_taken  debt_to_income_ratio
1             30%-<36%                65662
              20%-<30%                57479
              50%-60%                 53344
              49                      26062
              44                      20878
              42                      19716
              <20%                    19481
              43                      18893
              48                      18016
              41                      17788
2             30%-<36%                 3888
              20%-<30%                 3815
              50%-60%                  2223
              <20%                     1669
              44                       1183
              49                       1159
              47                       1059
              43                       1041
              42                       1035
              Exempt                    995
3             >60%                    49122
              50%-60%                 28146
              20%-<30%                14984
              30%-<36%                13720
              <20%                    12158
              49                       4232
              44                       3898
              42                       3824
              48                       3626
              47                       3457
Name: count, dtype: int64

======================================================================
MISSING / EXEMPT DTI BY ACTION
======================================================================
action_taken
1    45673
3    18906
2     5563
Name: count, dtype: int64

======================================================================
DTI + INCOME DATA QUALITY
======================================================================
Records with numeric DTI and income: 308365

Income summary:
count    308365.000000
mean        134.936530
std         419.814913
min          -5.000000
25%          75.000000
50%         109.000000
75%         161.000000
max      224000.000000
Name: income, dtype: float64

======================================================================
DTI + EXTREME LTV OVERLAP
======================================================================
Records: 30
debt_to_income_ratio  loan_amount  property_value_analysis_value  loan_to_value_ratio_clean     derived_loan_product_type  action_taken
                  42     215000.0                        35000.0                    613.803       Conventional:First Lien             3
                  43      75000.0                        45000.0                    590.634 Conventional:Subordinate Lien             3
                  49      65000.0                         5000.0                 113785.806 Conventional:Subordinate Lien             3
                  47      85000.0                        15000.0                    712.638 Conventional:Subordinate Lien             3
                  40     185000.0                        35000.0                    732.539 Conventional:Subordinate Lien             3
                  39      55000.0                        45000.0                    825.455 Conventional:Subordinate Lien             3
                  36      65000.0                        35000.0                    706.532 Conventional:Subordinate Lien             3
                  39      55000.0                        45000.0                    882.107 Conventional:Subordinate Lien             3
                  38      75000.0                        25000.0                    817.232 Conventional:Subordinate Lien             3
                  49      45000.0                        25000.0                    815.528 Conventional:Subordinate Lien             3
                  44      35000.0                         5000.0                 303237.000 Conventional:Subordinate Lien             3
                  36      35000.0                         5000.0                   2692.308       Conventional:First Lien             3
                  46      35000.0                         5000.0                  83743.273 Conventional:Subordinate Lien             3
                  38      35000.0                         5000.0                  46327.222 Conventional:Subordinate Lien             3
                  42     205000.0                         5000.0                  97560.976       Conventional:First Lien             3
                  45     155000.0                         5000.0                  35714.286       Conventional:First Lien             3
                  47      35000.0                         5000.0                   1400.000       Conventional:First Lien             3
                  44      35000.0                         5000.0                  33358.746 Conventional:Subordinate Lien             3
                  42      75000.0                        75000.0                    689.347 Conventional:Subordinate Lien             3
                  37      55000.0                         5000.0                   2127.660       Conventional:First Lien             3

In [57]:
# ==============================================================
# FINAL DEBT-TO-INCOME RATIO DATA QUALITY TREATMENT
# ==============================================================

# --------------------------------------------------------------
# 1. Preserve original DTI
# --------------------------------------------------------------

df['dti_original'] = df['debt_to_income_ratio']


# --------------------------------------------------------------
# 2. Exact numeric DTI helper
# --------------------------------------------------------------

df['debt_to_income_ratio_numeric'] = pd.to_numeric(
    df['debt_to_income_ratio'],
    errors='coerce'
)


# --------------------------------------------------------------
# 3. Create standardized DTI analysis category
# --------------------------------------------------------------

df['dti_analysis_category'] = (
    df['debt_to_income_ratio']
    .astype('string')
    .str.strip()
)


# --------------------------------------------------------------
# 4. Standardize exact numeric values into one category
# --------------------------------------------------------------

numeric_dti_mask = (
    df['debt_to_income_ratio_numeric'].notna()
)

df.loc[
    numeric_dti_mask,
    'dti_analysis_category'
] = '36%-49%'


# --------------------------------------------------------------
# 5. Standardize missing and Exempt
# --------------------------------------------------------------

df.loc[
    df['debt_to_income_ratio'].isna(),
    'dti_analysis_category'
] = 'Missing'

df.loc[
    df['debt_to_income_ratio']
    .astype(str)
    .str.strip()
    .eq('Exempt'),
    'dti_analysis_category'
] = 'Exempt'


# --------------------------------------------------------------
# 6. Create DTI quality category
# --------------------------------------------------------------

df['dti_quality_category'] = 'Valid / Usable'

df.loc[
    df['debt_to_income_ratio'].isna(),
    'dti_quality_category'
] = 'Missing'

df.loc[
    df['debt_to_income_ratio']
    .astype(str)
    .str.strip()
    .eq('Exempt'),
    'dti_quality_category'
] = 'Exempt'


# --------------------------------------------------------------
# 7. Verification
# --------------------------------------------------------------

print("=" * 70)
print("FINAL DTI DATA QUALITY TREATMENT")
print("=" * 70)


print("\nDTI ANALYSIS CATEGORY")
print("-" * 70)

print(
    df['dti_analysis_category']
    .value_counts(dropna=False)
)


print("\nDTI QUALITY CATEGORY")
print("-" * 70)

print(
    df['dti_quality_category']
    .value_counts(dropna=False)
)


print("\nEXACT NUMERIC DTI")
print("-" * 70)

print(
    df['debt_to_income_ratio_numeric']
    .describe()
)


print("\nORIGINAL DTI PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'dti_original',
            'debt_to_income_ratio_numeric',
            'dti_analysis_category',
            'dti_quality_category'
        ]
    ]
    .head(15)
)


print("\nDTI CATEGORY CHECK")
print("-" * 70)

print(
    pd.crosstab(
        df['dti_analysis_category'],
        df['action_taken']
    )
)


print("\nFINAL DTI SUMMARY")
print("-" * 70)

print(
    "Total records:",
    len(df)
)

print(
    "Exact numeric DTI records:",
    df['debt_to_income_ratio_numeric'].notna().sum()
)

print(
    "Range/category DTI records:",
    df['dti_analysis_category'].isin([
        '<20%',
        '20%-<30%',
        '30%-<36%',
        '50%-60%',
        '>60%'
    ]).sum()
)

print(
    "Missing DTI:",
    (df['dti_analysis_category'] == 'Missing').sum()
)

print(
    "Exempt DTI:",
    (df['dti_analysis_category'] == 'Exempt').sum()
)

======================================================================
FINAL DTI DATA QUALITY TREATMENT
======================================================================

DTI ANALYSIS CATEGORY
----------------------------------------------------------------------
dti_analysis_category
36%-49%     309438
50%-60%      83713
30%-<36%     83270
20%-<30%     76278
>60%         54057
Missing      53332
<20%         33308
Exempt       16810
Name: count, dtype: Int64

DTI QUALITY CATEGORY
----------------------------------------------------------------------
dti_quality_category
Valid / Usable    640064
Missing            53332
Exempt             16810
Name: count, dtype: int64

EXACT NUMERIC DTI
----------------------------------------------------------------------
count    309438.000000
mean         42.953441
std           3.990969
min          36.000000
25%          40.000000
50%          43.000000
75%          46.000000
max          49.000000
Name: debt_to_income_ratio_numeric, dtype: float64

ORIGINAL DTI PRESERVATION CHECK
----------------------------------------------------------------------
   dti_original  debt_to_income_ratio_numeric dti_analysis_category  \
0      20%-<30%                           NaN              20%-<30%
1           NaN                           NaN               Missing
2           NaN                           NaN               Missing
3            43                          43.0               36%-49%
4           NaN                           NaN               Missing
5           NaN                           NaN               Missing
6           NaN                           NaN               Missing
7           NaN                           NaN               Missing
8           NaN                           NaN               Missing
9            49                          49.0               36%-49%
10          NaN                           NaN               Missing
11           44                          44.0               36%-49%
12           47                          47.0               36%-49%
13           48                          48.0               36%-49%
14           43                          43.0               36%-49%

   dti_quality_category
0        Valid / Usable
1               Missing
2               Missing
3        Valid / Usable
4               Missing
5               Missing
6               Missing
7               Missing
8               Missing
9        Valid / Usable
10              Missing
11       Valid / Usable
12       Valid / Usable
13       Valid / Usable
14       Valid / Usable

DTI CATEGORY CHECK
----------------------------------------------------------------------
action_taken                1      2      3
dti_analysis_category
20%-<30%                57479   3815  14984
30%-<36%                65662   3888  13720
36%-49%                248545  13456  47437
50%-60%                 53344   2223  28146
<20%                    19481   1669  12158
>60%                     4472    463  49122
Exempt                  13130    995   2685
Missing                 32543   4568  16221

FINAL DTI SUMMARY
----------------------------------------------------------------------
Total records: 710206
Exact numeric DTI records: 309438
Range/category DTI records: 330626
Missing DTI: 53332
Exempt DTI: 16810

In [58]:
# ==============================================================
# LOAN AMOUNT DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("LOAN AMOUNT DATA QUALITY INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Basic information
# --------------------------------------------------------------

print("\nLOAN AMOUNT DTYPE")
print("-" * 70)
print(df['loan_amount'].dtype)


# --------------------------------------------------------------
# 2. Missing values
# --------------------------------------------------------------

missing_loan = df['loan_amount'].isna().sum()

print("\nMISSING VALUES")
print("-" * 70)
print("Missing:", missing_loan)
print(
    "Missing percentage:",
    round(missing_loan / len(df) * 100, 2),
    "%"
)


# --------------------------------------------------------------
# 3. Basic statistical summary
# --------------------------------------------------------------

print("\nLOAN AMOUNT SUMMARY")
print("-" * 70)

print(
    df['loan_amount'].describe()
)


# --------------------------------------------------------------
# 4. Negative loan amounts
# --------------------------------------------------------------

negative_loan = df[
    df['loan_amount'] < 0
]

print("\nNEGATIVE LOAN AMOUNTS")
print("-" * 70)
print("Records:", len(negative_loan))


# --------------------------------------------------------------
# 5. Zero loan amounts
# --------------------------------------------------------------

zero_loan = df[
    df['loan_amount'] == 0
]

print("\nZERO LOAN AMOUNTS")
print("-" * 70)
print("Records:", len(zero_loan))


# --------------------------------------------------------------
# 6. Loan amount percentiles
# --------------------------------------------------------------

print("\nLOAN AMOUNT PERCENTILES")
print("-" * 70)

percentiles = [
    0.01,
    0.05,
    0.25,
    0.50,
    0.75,
    0.90,
    0.95,
    0.99,
    0.995,
    0.999
]

print(
    df['loan_amount']
    .quantile(percentiles)
)


# --------------------------------------------------------------
# 7. Extreme loan amount thresholds
# --------------------------------------------------------------

thresholds = [
    1_000_000,
    5_000_000,
    10_000_000,
    25_000_000,
    50_000_000,
    100_000_000
]

print("\nEXTREME LOAN AMOUNT THRESHOLDS")
print("-" * 70)

for threshold in thresholds:

    count = (
        df['loan_amount'] > threshold
    ).sum()

    percentage = (
        count / len(df) * 100
    )

    print(
        f">${threshold:,.0f}: "
        f"{count:,} records "
        f"({percentage:.4f}%)"
    )


# --------------------------------------------------------------
# 8. Largest loan amounts
# --------------------------------------------------------------

print("\nTOP 30 LARGEST LOAN AMOUNTS")
print("-" * 70)

top_loans = (
    df[
        df['loan_amount'].notna()
    ]
    .sort_values(
        'loan_amount',
        ascending=False
    )
    [
        [
            'loan_amount',
            'property_value_analysis_value',
            'loan_to_value_ratio_clean',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units_clean',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .head(30)
)

print(
    top_loans.to_string(index=False)
)


# --------------------------------------------------------------
# 9. Large loans by dwelling category
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOANS > $10 MILLION BY DWELLING CATEGORY")
print("=" * 70)

large_loans = df[
    df['loan_amount'] > 10_000_000
]

print(
    large_loans[
        'derived_dwelling_category'
    ]
    .value_counts()
)


# --------------------------------------------------------------
# 10. Large loans by total units
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOANS > $10 MILLION BY TOTAL UNITS")
print("=" * 70)

print(
    large_loans[
        'total_units_clean'
    ]
    .value_counts()
)


# --------------------------------------------------------------
# 11. Large loans by loan product
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOANS > $10 MILLION BY LOAN PRODUCT")
print("=" * 70)

print(
    large_loans[
        'derived_loan_product_type'
    ]
    .value_counts()
)


# --------------------------------------------------------------
# 12. Large loans by action taken
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOANS > $10 MILLION BY ACTION TAKEN")
print("=" * 70)

print(
    large_loans[
        'action_taken'
    ]
    .value_counts()
)


# --------------------------------------------------------------
# 13. Large single-family loans
# --------------------------------------------------------------

single_family_large = df[
    (df['loan_amount'] > 10_000_000) &
    (
        df['derived_dwelling_category']
        .astype(str)
        .str.contains(
            'Single Family',
            na=False
        )
    )
]

print("\n" + "=" * 70)
print("LOANS > $10 MILLION + SINGLE FAMILY")
print("=" * 70)

print(
    "Records:",
    len(single_family_large)
)

if len(single_family_large) > 0:

    print(
        single_family_large[
            [
                'loan_amount',
                'property_value_analysis_value',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'total_units_clean',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'loan_amount',
            ascending=False
        )
        .head(50)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 14. Loan amount + property value relationship
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOAN AMOUNT + PROPERTY VALUE RELATIONSHIP")
print("=" * 70)

loan_property = df[
    df['loan_amount'].notna() &
    df['property_value_analysis_value'].notna() &
    (df['property_value_analysis_value'] > 0)
].copy()

loan_property['calculated_ltv_from_analysis'] = (
    loan_property['loan_amount'] /
    loan_property['property_value_analysis_value']
) * 100

print(
    loan_property[
        'calculated_ltv_from_analysis'
    ].describe()
)


# --------------------------------------------------------------
# 15. Loan amount > property value
# --------------------------------------------------------------

loan_greater_property = loan_property[
    loan_property['loan_amount'] >
    loan_property['property_value_analysis_value']
]

print("\nLOAN AMOUNT > PROPERTY VALUE")
print("-" * 70)

print(
    "Records:",
    len(loan_greater_property)
)

print(
    "Percentage:",
    round(
        len(loan_greater_property) /
        len(loan_property) * 100,
        2
    ),
    "%"
)


# --------------------------------------------------------------
# 16. Extreme loan amount + extreme LTV overlap
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LARGE LOAN + EXTREME LTV OVERLAP")
print("=" * 70)

large_loan_extreme_ltv = df[
    (df['loan_amount'] > 10_000_000) &
    (df['extreme_ltv_flag'])
]

print(
    "Records:",
    len(large_loan_extreme_ltv)
)

if len(large_loan_extreme_ltv) > 0:

    print(
        large_loan_extreme_ltv[
            [
                'loan_amount',
                'property_value_analysis_value',
                'loan_to_value_ratio_clean',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'total_units_clean',
                'action_taken'
            ]
        ]
        .sort_values(
            'loan_amount',
            ascending=False
        )
        .head(30)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 17. Extreme loan amount + property anomaly overlap
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LARGE LOAN + PROPERTY ANOMALY OVERLAP")
print("=" * 70)

large_loan_property_anomaly = df[
    (df['loan_amount'] > 10_000_000) &
    (df['property_value_anomaly_flag'])
]

print(
    "Records:",
    len(large_loan_property_anomaly)
)

if len(large_loan_property_anomaly) > 0:

    print(
        large_loan_property_anomaly[
            [
                'loan_amount',
                'property_value_original',
                'property_value_analysis_value',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'total_units_clean',
                'action_taken'
            ]
        ]
        .to_string(index=False)
    )

======================================================================
LOAN AMOUNT DATA QUALITY INVESTIGATION
======================================================================

LOAN AMOUNT DTYPE
----------------------------------------------------------------------
float64

MISSING VALUES
----------------------------------------------------------------------
Missing: 0
Missing percentage: 0.0 %

LOAN AMOUNT SUMMARY
----------------------------------------------------------------------
count    7.102060e+05
mean     3.135370e+05
std      2.111020e+06
min      5.000000e+03
25%      1.250000e+05
50%      2.450000e+05
75%      3.550000e+05
max      6.450000e+08
Name: loan_amount, dtype: float64

NEGATIVE LOAN AMOUNTS
----------------------------------------------------------------------
Records: 0

ZERO LOAN AMOUNTS
----------------------------------------------------------------------
Records: 0

LOAN AMOUNT PERCENTILES
----------------------------------------------------------------------
0.010      15000.0
0.050      45000.0
0.250     125000.0
0.500     245000.0
0.750     355000.0
0.900     515000.0
0.950     655000.0
0.990    1245000.0
0.995    1755000.0
0.999    7355000.0
Name: loan_amount, dtype: float64

EXTREME LOAN AMOUNT THRESHOLDS
----------------------------------------------------------------------
>$1,000,000: 10,909 records (1.5360%)
>$5,000,000: 898 records (0.1264%)
>$10,000,000: 593 records (0.0835%)
>$25,000,000: 284 records (0.0400%)
>$50,000,000: 72 records (0.0101%)
>$100,000,000: 24 records (0.0034%)

TOP 30 LARGEST LOAN AMOUNTS
----------------------------------------------------------------------
 loan_amount  property_value_analysis_value  loan_to_value_ratio_clean derived_loan_product_type derived_dwelling_category total_units_clean  loan_purpose  action_taken
 645000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 581000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 550000000.0                     92695000.0                      67.20   Conventional:First Lien    Multifamily:Site-Built              >149            31             1
 344000000.0                     38205000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built              >149            32             1
 344000000.0                      2495000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0                      8645000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0                     22705000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             50-99            32             1
 344000000.0                      3705000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0                      6935000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0                      2825000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             25-49            32             1
 344000000.0                     53305000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built           100-149            32             1
 344000000.0                      6605000.0                      67.00   Conventional:First Lien    Multifamily:Site-Built             50-99            32             1
 262000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 260000000.0                    447545000.0                      58.09   Conventional:First Lien    Multifamily:Site-Built              >149             5             1
 238000000.0                    439705000.0                      54.07   Conventional:First Lien    Multifamily:Site-Built              >149            31             1
 211000000.0                    331805000.0                      63.50   Conventional:First Lien    Multifamily:Site-Built              >149            32             1
 186000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            32             3
 178000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 163000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 148000000.0                    734705000.0                      67.21   Conventional:First Lien    Multifamily:Site-Built              >149             1             1
 144000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
 119000000.0                   1838005000.0                      65.00   Conventional:First Lien    Multifamily:Site-Built              >149             1             1
 119000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149             1             3
 101000000.0                    162005000.0                      62.10   Conventional:First Lien    Multifamily:Site-Built             50-99             1             1
  94000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
  92000000.0                    350885000.0                      52.80   Conventional:First Lien    Multifamily:Site-Built              >149            31             1
  89800000.0                     75105000.0                      84.00   Conventional:First Lien    Multifamily:Site-Built              >149             1             1
  88500000.0                    110005000.0                      80.49   Conventional:First Lien    Multifamily:Site-Built              >149             1             1
  86000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3
  85000000.0                            NaN                        NaN   Conventional:First Lien    Multifamily:Site-Built              >149            31             3

======================================================================
LOANS > $10 MILLION BY DWELLING CATEGORY
======================================================================
derived_dwelling_category
Multifamily:Site-Built                    568
Single Family (1-4 Units):Site-Built       18
Multifamily:Manufactured                    6
Single Family (1-4 Units):Manufactured      1
Name: count, dtype: int64

======================================================================
LOANS > $10 MILLION BY TOTAL UNITS
======================================================================
total_units_clean
>149       475
100-149     63
50-99       24
1           18
25-49        9
5-24         3
2            1
Name: count, dtype: int64

======================================================================
LOANS > $10 MILLION BY LOAN PRODUCT
======================================================================
derived_loan_product_type
Conventional:First Lien          553
FHA:First Lien                    38
Conventional:Subordinate Lien      2
Name: count, dtype: int64

======================================================================
LOANS > $10 MILLION BY ACTION TAKEN
======================================================================
action_taken
1    496
3     91
2      6
Name: count, dtype: int64

======================================================================
LOANS > $10 MILLION + SINGLE FAMILY
======================================================================
Records: 19
 loan_amount  property_value_analysis_value  loan_to_value_ratio_clean derived_loan_product_type              derived_dwelling_category total_units_clean  loan_purpose  action_taken
  24100000.0                       555000.0                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             3
  22300000.0                     27905000.0                  80.043011   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             3
  22100000.0                     40005000.0                  55.300000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1
  21900000.0                       195000.0                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            31             1
  21600000.0                     33305000.0                  65.000000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1
  19000000.0                     34005000.0                  55.882000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            31             1
  18400000.0                       265000.0                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            31             1
  18000000.0                            NaN                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             3
  17700000.0                     27255000.0                  64.954000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            32             1
  16600000.0                       325000.0                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            31             1
  15000000.0                            NaN                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 2             1             1
  14000000.0                            NaN                  58.630000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            31             3
  12000000.0                     22005000.0                  54.545000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1
  12000000.0                       125000.0                        NaN   Conventional:First Lien Single Family (1-4 Units):Manufactured                 1             1             3
  11600000.0                     16505000.0                  70.300000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1            31             1
  11400000.0                     16275000.0                  69.980000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1
  11000000.0                            NaN                        NaN   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1
  10700000.0                     13355000.0                  80.000000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1
  10500000.0                     15005000.0                  70.000000   Conventional:First Lien   Single Family (1-4 Units):Site-Built                 1             1             1

======================================================================
LOAN AMOUNT + PROPERTY VALUE RELATIONSHIP
======================================================================
count    666299.000000
mean         73.132270
std          65.222077
min           0.019227
25%          55.056180
50%          80.281690
75%          96.610169
max       18100.000000
Name: calculated_ltv_from_analysis, dtype: float64

LOAN AMOUNT > PROPERTY VALUE
----------------------------------------------------------------------
Records: 20915
Percentage: 3.14 %

======================================================================
LARGE LOAN + EXTREME LTV OVERLAP
======================================================================
Records: 1
 loan_amount  property_value_analysis_value  loan_to_value_ratio_clean derived_loan_product_type derived_dwelling_category total_units_clean  action_taken
  11200000.0                    837155000.0                     7500.0   Conventional:First Lien    Multifamily:Site-Built           100-149             3

======================================================================
LARGE LOAN + PROPERTY ANOMALY OVERLAP
======================================================================
Records: 0

In [59]:
# ==============================================================
# FINAL LOAN AMOUNT DATA QUALITY TREATMENT
# ==============================================================

# Preserve original loan amount
df['loan_amount_original'] = df['loan_amount']


# Analysis value
df['loan_amount_analysis_value'] = df['loan_amount'].copy()


# Extreme loan flag
df['extreme_loan_amount_flag'] = (
    df['loan_amount'] > 10_000_000
)


# Quality category
df['loan_amount_quality_category'] = 'Valid / Usable'

df.loc[
    df['loan_amount'].isna(),
    'loan_amount_quality_category'
] = 'Missing'

df.loc[
    df['loan_amount'] < 0,
    'loan_amount_quality_category'
] = 'Invalid Negative'

df.loc[
    df['extreme_loan_amount_flag'],
    'loan_amount_quality_category'
] = 'Extreme Value - Retained'


# --------------------------------------------------------------
# VERIFICATION
# --------------------------------------------------------------

print("=" * 70)
print("FINAL LOAN AMOUNT DATA QUALITY TREATMENT")
print("=" * 70)


print("\nLOAN AMOUNT QUALITY CATEGORY")
print("-" * 70)

print(
    df['loan_amount_quality_category']
    .value_counts(dropna=False)
)


print("\nEXTREME LOAN AMOUNT FLAG")
print("-" * 70)

print(
    df['extreme_loan_amount_flag']
    .value_counts()
)


print("\nANALYSIS LOAN AMOUNT SUMMARY")
print("-" * 70)

print(
    df['loan_amount_analysis_value']
    .describe()
)


print("\nORIGINAL LOAN AMOUNT PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'loan_amount_original',
            'loan_amount_analysis_value',
            'extreme_loan_amount_flag',
            'loan_amount_quality_category'
        ]
    ].head(15)
)


print("\nFINAL LOAN AMOUNT SUMMARY")
print("-" * 70)

print(
    "Total records:",
    len(df)
)

print(
    "Missing:",
    df['loan_amount'].isna().sum()
)

print(
    "Negative:",
    (df['loan_amount'] < 0).sum()
)

print(
    "Zero:",
    (df['loan_amount'] == 0).sum()
)

print(
    "Extreme > $10M:",
    df['extreme_loan_amount_flag'].sum()
)

print(
    "Analysis-ready:",
    df['loan_amount_analysis_value'].notna().sum()
)

======================================================================
FINAL LOAN AMOUNT DATA QUALITY TREATMENT
======================================================================

LOAN AMOUNT QUALITY CATEGORY
----------------------------------------------------------------------
loan_amount_quality_category
Valid / Usable              709613
Extreme Value - Retained       593
Name: count, dtype: int64

EXTREME LOAN AMOUNT FLAG
----------------------------------------------------------------------
extreme_loan_amount_flag
False    709613
True        593
Name: count, dtype: int64

ANALYSIS LOAN AMOUNT SUMMARY
----------------------------------------------------------------------
count    7.102060e+05
mean     3.135370e+05
std      2.111020e+06
min      5.000000e+03
25%      1.250000e+05
50%      2.450000e+05
75%      3.550000e+05
max      6.450000e+08
Name: loan_amount_analysis_value, dtype: float64

ORIGINAL LOAN AMOUNT PRESERVATION CHECK
----------------------------------------------------------------------
    loan_amount_original  loan_amount_analysis_value  \
0               135000.0                    135000.0
1               445000.0                    445000.0
2               435000.0                    435000.0
3               715000.0                    715000.0
4               215000.0                    215000.0
5               175000.0                    175000.0
6               255000.0                    255000.0
7               275000.0                    275000.0
8               475000.0                    475000.0
9               605000.0                    605000.0
10              225000.0                    225000.0
11              485000.0                    485000.0
12              255000.0                    255000.0
13              375000.0                    375000.0
14              485000.0                    485000.0

    extreme_loan_amount_flag loan_amount_quality_category
0                      False               Valid / Usable
1                      False               Valid / Usable
2                      False               Valid / Usable
3                      False               Valid / Usable
4                      False               Valid / Usable
5                      False               Valid / Usable
6                      False               Valid / Usable
7                      False               Valid / Usable
8                      False               Valid / Usable
9                      False               Valid / Usable
10                     False               Valid / Usable
11                     False               Valid / Usable
12                     False               Valid / Usable
13                     False               Valid / Usable
14                     False               Valid / Usable

FINAL LOAN AMOUNT SUMMARY
----------------------------------------------------------------------
Total records: 710206
Missing: 0
Negative: 0
Zero: 0
Extreme > $10M: 593
Analysis-ready: 710206

In [60]:
# ==============================================================
# LOAN TERM DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("LOAN TERM DATA QUALITY INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Basic information
# --------------------------------------------------------------

print("\nLOAN TERM DTYPE")
print("-" * 70)
print(df['loan_term'].dtype)


# --------------------------------------------------------------
# 2. Missing values
# --------------------------------------------------------------

missing_loan_term = df['loan_term'].isna().sum()

print("\nMISSING VALUES")
print("-" * 70)

print("Missing:", missing_loan_term)

print(
    "Missing percentage:",
    round(
        missing_loan_term / len(df) * 100,
        2
    ),
    "%"
)


# --------------------------------------------------------------
# 3. Unique values
# --------------------------------------------------------------

print("\nMOST COMMON LOAN TERM VALUES")
print("-" * 70)

print(
    df['loan_term']
    .value_counts(dropna=False)
    .head(30)
)


# --------------------------------------------------------------
# 4. Numeric conversion
# --------------------------------------------------------------

loan_term_numeric = pd.to_numeric(
    df['loan_term'],
    errors='coerce'
)

print("\nNUMERIC LOAN TERM SUMMARY")
print("-" * 70)

print(
    loan_term_numeric.describe()
)


# --------------------------------------------------------------
# 5. Negative values
# --------------------------------------------------------------

negative_loan_term = (
    loan_term_numeric < 0
).sum()

print("\nNEGATIVE LOAN TERMS")
print("-" * 70)

print(
    "Records:",
    negative_loan_term
)


# --------------------------------------------------------------
# 6. Zero values
# --------------------------------------------------------------

zero_loan_term = (
    loan_term_numeric == 0
).sum()

print("\nZERO LOAN TERMS")
print("-" * 70)

print(
    "Records:",
    zero_loan_term
)


# --------------------------------------------------------------
# 7. Extremely large loan terms
# --------------------------------------------------------------

print("\nLOAN TERM THRESHOLDS")
print("-" * 70)

for threshold in [60, 120, 180, 240, 360, 480, 600]:

    count = (
        loan_term_numeric > threshold
    ).sum()

    print(
        f">{threshold} months: {count:,} records"
    )


# --------------------------------------------------------------
# 8. Percentiles
# --------------------------------------------------------------

print("\nLOAN TERM PERCENTILES")
print("-" * 70)

print(
    loan_term_numeric.quantile(
        [
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.999
        ]
    )
)


# --------------------------------------------------------------
# 9. Loan term by loan product
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOAN TERM BY LOAN PRODUCT")
print("=" * 70)

print(
    df.groupby(
        'derived_loan_product_type',
        dropna=False
    )['loan_term']
    .agg(
        ['count', 'min', 'median', 'max']
    )
    .sort_values(
        'count',
        ascending=False
    )
)


# --------------------------------------------------------------
# 10. Loan term by action taken
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOAN TERM BY ACTION TAKEN")
print("=" * 70)

print(
    df.groupby(
        'action_taken',
        dropna=False
    )['loan_term']
    .agg(
        ['count', 'min', 'median', 'max']
    )
)


# --------------------------------------------------------------
# 11. Non-standard / suspicious values
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOAN TERM VALUES OUTSIDE COMMON RANGE")
print("=" * 70)

unusual_loan_term = df[
    loan_term_numeric.notna() &
    (
        (loan_term_numeric <= 0) |
        (loan_term_numeric > 600)
    )
]

print(
    "Records:",
    len(unusual_loan_term)
)

if len(unusual_loan_term) > 0:

    print(
        unusual_loan_term[
            [
                'loan_term',
                'loan_amount',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'loan_term',
            ascending=False
        )
        .head(50)
        .to_string(index=False)
    )

======================================================================
LOAN TERM DATA QUALITY INVESTIGATION
======================================================================

LOAN TERM DTYPE
----------------------------------------------------------------------
object

MISSING VALUES
----------------------------------------------------------------------
Missing: 12464
Missing percentage: 1.75 %

MOST COMMON LOAN TERM VALUES
----------------------------------------------------------------------
loan_term
360       276035
360.0     213371
240        29496
300        27447
180        24693
300.0      22084
Exempt     16578
180.0      15601
240.0      14136
NaN        12464
120         9941
120.0       5634
480         4026
1           3954
480.0       3329
276.0       2940
60          2553
372         2313
36          2291
12.0        2164
276         2121
12          2120
84          1069
60.0        1067
36.0         791
6            618
48           443
84.0         297
324.0        255
6.0          239
Name: count, dtype: int64

NUMERIC LOAN TERM SUMMARY
----------------------------------------------------------------------
count    681164.000000
mean        322.084099
std          80.473256
min           1.000000
25%         300.000000
50%         360.000000
75%         360.000000
max        3292.000000
Name: loan_term, dtype: float64

NEGATIVE LOAN TERMS
----------------------------------------------------------------------
Records: 0

ZERO LOAN TERMS
----------------------------------------------------------------------
Records: 0

LOAN TERM THRESHOLDS
----------------------------------------------------------------------
>60 months: 663,596 records
>120 months: 646,058 records
>180 months: 604,933 records
>240 months: 559,819 records
>360 months: 10,822 records
>480 months: 7 records
>600 months: 1 records

LOAN TERM PERCENTILES
----------------------------------------------------------------------
0.010     12.0
0.050    120.0
0.250    300.0
0.500    360.0
0.750    360.0
0.900    360.0
0.950    360.0
0.990    480.0
0.999    480.0
Name: loan_term, dtype: float64

======================================================================
LOAN TERM BY LOAN PRODUCT
======================================================================

TypeError: agg function failed [how->min,dtype->object]

In [61]:
# ==============================================================
# CORRECTED LOAN TERM ANALYSIS
# ==============================================================

print("=" * 70)
print("LOAN TERM BY LOAN PRODUCT")
print("=" * 70)

loan_term_product_summary = (
    df.assign(loan_term_numeric=loan_term_numeric)
    .groupby(
        'derived_loan_product_type',
        dropna=False
    )['loan_term_numeric']
    .agg(
        ['count', 'min', 'median', 'max']
    )
    .sort_values(
        'count',
        ascending=False
    )
)

print(loan_term_product_summary)


# --------------------------------------------------------------
# Loan term by action taken
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("LOAN TERM BY ACTION TAKEN")
print("=" * 70)

loan_term_action_summary = (
    df.assign(loan_term_numeric=loan_term_numeric)
    .groupby(
        'action_taken',
        dropna=False
    )['loan_term_numeric']
    .agg(
        ['count', 'min', 'median', 'max']
    )
)

print(loan_term_action_summary)


# --------------------------------------------------------------
# Investigate unusual loan terms
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("UNUSUAL LOAN TERM VALUES")
print("=" * 70)

unusual_loan_term = df[
    loan_term_numeric.notna() &
    (
        (loan_term_numeric <= 0) |
        (loan_term_numeric > 600)
    )
].copy()

print(
    "Records:",
    len(unusual_loan_term)
)


# --------------------------------------------------------------
# Show unusual records
# --------------------------------------------------------------

if len(unusual_loan_term) > 0:

    unusual_loan_term['loan_term_numeric'] = (
        loan_term_numeric.loc[
            unusual_loan_term.index
        ]
    )

    print("\nUNUSUAL RECORDS")
    print("-" * 70)

    print(
        unusual_loan_term[
            [
                'loan_term',
                'loan_term_numeric',
                'loan_amount',
                'property_value',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'total_units',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .sort_values(
            'loan_term_numeric',
            ascending=False
        )
        .to_string(index=False)
    )

======================================================================
LOAN TERM BY LOAN PRODUCT
======================================================================
                                count    min  median     max
derived_loan_product_type
Conventional:First Lien        409407    1.0   360.0   480.0
FHA:First Lien                 114815   21.0   360.0   507.0
Conventional:Subordinate Lien   92839    1.0   240.0   480.0
VA:First Lien                   61356   30.0   360.0  3292.0
FSA/RHS:First Lien               1827  226.0   360.0   480.0
FSA/RHS:Subordinate Lien          885   36.0    36.0   360.0
FHA:Subordinate Lien               35   36.0   240.0   360.0

======================================================================
LOAN TERM BY ACTION TAKEN
======================================================================
               count  min  median     max
action_taken
1             478890  1.0   360.0  3292.0
2              29829  1.0   360.0   480.0
3             172445  1.0   360.0   480.0

======================================================================
UNUSUAL LOAN TERM VALUES
======================================================================
Records: 1

UNUSUAL RECORDS
----------------------------------------------------------------------
loan_term  loan_term_numeric  loan_amount property_value derived_loan_product_type            derived_dwelling_category total_units  loan_purpose  action_taken
     3292             3292.0     375000.0            NaN             VA:First Lien Single Family (1-4 Units):Site-Built           1             1             1

In [62]:
# ==============================================================
# FINAL LOAN TERM DATA QUALITY TREATMENT
# ==============================================================

print("=" * 70)
print("FINAL LOAN TERM DATA QUALITY TREATMENT")
print("=" * 70)


# --------------------------------------------------------------
# 1. Preserve original column
# --------------------------------------------------------------

df['loan_term_original'] = df['loan_term']


# --------------------------------------------------------------
# 2. Create numeric analysis column
# --------------------------------------------------------------

df['loan_term_analysis_value'] = pd.to_numeric(
    df['loan_term'],
    errors='coerce'
)


# --------------------------------------------------------------
# 3. Create anomaly flag
# --------------------------------------------------------------

df['loan_term_anomaly_flag'] = (
    df['loan_term_analysis_value'] > 600
)


# --------------------------------------------------------------
# 4. Exclude confirmed extreme anomaly from analysis
# --------------------------------------------------------------

df.loc[
    df['loan_term_anomaly_flag'],
    'loan_term_analysis_value'
] = np.nan


# --------------------------------------------------------------
# 5. Create quality category
# --------------------------------------------------------------

df['loan_term_quality_category'] = 'Valid / Usable'

df.loc[
    df['loan_term'].isna(),
    'loan_term_quality_category'
] = 'Missing'

df.loc[
    df['loan_term'].astype(str).str.strip().eq('Exempt'),
    'loan_term_quality_category'
] = 'Exempt'

df.loc[
    df['loan_term_anomaly_flag'],
    'loan_term_quality_category'
] = 'Extreme Anomaly - Excluded'


# --------------------------------------------------------------
# 6. Verification
# --------------------------------------------------------------

print("\nLOAN TERM QUALITY CATEGORY")
print("-" * 70)

print(
    df['loan_term_quality_category']
    .value_counts(dropna=False)
)


print("\nLOAN TERM ANOMALY FLAG")
print("-" * 70)

print(
    df['loan_term_anomaly_flag']
    .value_counts()
)


print("\nANALYSIS LOAN TERM SUMMARY")
print("-" * 70)

print(
    df['loan_term_analysis_value']
    .describe()
)


print("\nFINAL LOAN TERM SUMMARY")
print("-" * 70)

print(
    "Total records:",
    len(df)
)

print(
    "Missing:",
    df['loan_term'].isna().sum()
)

print(
    "Exempt:",
    df['loan_term']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print(
    "Extreme anomaly >600 months:",
    df['loan_term_anomaly_flag'].sum()
)

print(
    "Analysis-ready:",
    df['loan_term_analysis_value'].notna().sum()
)


# --------------------------------------------------------------
# 7. Preservation check
# --------------------------------------------------------------

print("\nORIGINAL LOAN TERM PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'loan_term_original',
            'loan_term_analysis_value',
            'loan_term_anomaly_flag',
            'loan_term_quality_category'
        ]
    ]
    .head(15)
)

======================================================================
FINAL LOAN TERM DATA QUALITY TREATMENT
======================================================================

LOAN TERM QUALITY CATEGORY
----------------------------------------------------------------------
loan_term_quality_category
Valid / Usable                681163
Exempt                         16578
Missing                        12464
Extreme Anomaly - Excluded         1
Name: count, dtype: int64

LOAN TERM ANOMALY FLAG
----------------------------------------------------------------------
loan_term_anomaly_flag
False    710205
True          1
Name: count, dtype: int64

ANALYSIS LOAN TERM SUMMARY
----------------------------------------------------------------------
count    681163.000000
mean        322.079739
std          80.392819
min           1.000000
25%         300.000000
50%         360.000000
75%         360.000000
max         507.000000
Name: loan_term_analysis_value, dtype: float64

FINAL LOAN TERM SUMMARY
----------------------------------------------------------------------
Total records: 710206
Missing: 12464
Exempt: 16578
Extreme anomaly >600 months: 1
Analysis-ready: 681163

ORIGINAL LOAN TERM PRESERVATION CHECK
----------------------------------------------------------------------
   loan_term_original  loan_term_analysis_value  loan_term_anomaly_flag  \
0                 360                     360.0                   False
1                 360                     360.0                   False
2                 360                     360.0                   False
3                 360                     360.0                   False
4                 360                     360.0                   False
5                 360                     360.0                   False
6                 360                     360.0                   False
7                 360                     360.0                   False
8                 344                     344.0                   False
9                 360                     360.0                   False
10                351                     351.0                   False
11                360                     360.0                   False
12                312                     312.0                   False
13                360                     360.0                   False
14                360                     360.0                   False

   loan_term_quality_category
0              Valid / Usable
1              Valid / Usable
2              Valid / Usable
3              Valid / Usable
4              Valid / Usable
5              Valid / Usable
6              Valid / Usable
7              Valid / Usable
8              Valid / Usable
9              Valid / Usable
10             Valid / Usable
11             Valid / Usable
12             Valid / Usable
13             Valid / Usable
14             Valid / Usable

In [63]:

# ==============================================================
# TOTAL LOAN COSTS - DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("TOTAL LOAN COSTS - DATA QUALITY INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Basic information
# --------------------------------------------------------------

print("\n1. DATA TYPE")
print("-" * 70)

print("Original dtype:", df['total_loan_costs'].dtype)


print("\n2. MISSING VALUES")
print("-" * 70)

missing_count = df['total_loan_costs'].isna().sum()
missing_pct = missing_count / len(df) * 100

print("Missing:", missing_count)
print("Missing %:", round(missing_pct, 2))


# --------------------------------------------------------------
# 2. Most common raw values
# --------------------------------------------------------------

print("\n3. MOST COMMON VALUES")
print("-" * 70)

print(
    df['total_loan_costs']
    .value_counts(dropna=False)
    .head(20)
)


# --------------------------------------------------------------
# 3. Exempt values
# --------------------------------------------------------------

print("\n4. EXEMPT VALUES")
print("-" * 70)

exempt_mask = (
    df['total_loan_costs']
    .astype(str)
    .str.strip()
    .eq('Exempt')
)

print("Exempt count:", exempt_mask.sum())
print("Exempt %:", round(exempt_mask.mean() * 100, 2))


# --------------------------------------------------------------
# 4. Numeric conversion
# --------------------------------------------------------------

print("\n5. NUMERIC CONVERSION")
print("-" * 70)

total_loan_costs_numeric = pd.to_numeric(
    df['total_loan_costs'],
    errors='coerce'
)

print(
    total_loan_costs_numeric.describe()
)


# --------------------------------------------------------------
# 5. Invalid / unusual numerical values
# --------------------------------------------------------------

print("\n6. NEGATIVE AND ZERO VALUES")
print("-" * 70)

negative_count = (
    total_loan_costs_numeric < 0
).sum()

zero_count = (
    total_loan_costs_numeric == 0
).sum()

print("Negative values:", negative_count)
print("Zero values:", zero_count)


# --------------------------------------------------------------
# 6. Percentiles
# --------------------------------------------------------------

print("\n7. PERCENTILES")
print("-" * 70)

percentiles = total_loan_costs_numeric.quantile(
    [0.01, 0.05, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 0.995, 0.999]
)

print(percentiles)


# --------------------------------------------------------------
# 7. Extreme value thresholds
# --------------------------------------------------------------

print("\n8. EXTREME VALUE THRESHOLDS")
print("-" * 70)

thresholds = [
    1000,
    5000,
    10000,
    25000,
    50000,
    100000,
    500000
]

for threshold in thresholds:
    count = (
        total_loan_costs_numeric > threshold
    ).sum()

    pct = count / len(df) * 100

    print(
        f">{threshold:>8,}: {count:>7,} records "
        f"({pct:.4f}%)"
    )


# --------------------------------------------------------------
# 8. Negative value records
# --------------------------------------------------------------

print("\n9. NEGATIVE VALUE RECORDS")
print("-" * 70)

negative_costs = df[
    total_loan_costs_numeric < 0
].copy()

print("Records:", len(negative_costs))

if len(negative_costs) > 0:

    negative_costs['total_loan_costs_numeric'] = (
        total_loan_costs_numeric.loc[negative_costs.index]
    )

    print(
        negative_costs[
            [
                'total_loan_costs',
                'total_loan_costs_numeric',
                'loan_amount',
                'property_value',
                'derived_loan_product_type',
                'derived_dwelling_category',
                'loan_purpose',
                'action_taken'
            ]
        ]
        .head(20)
        .to_string(index=False)
    )


# --------------------------------------------------------------
# 9. Highest values
# --------------------------------------------------------------

print("\n10. HIGHEST TOTAL LOAN COSTS")
print("-" * 70)

highest_costs = df[
    total_loan_costs_numeric.notna()
].copy()

highest_costs['total_loan_costs_numeric'] = (
    total_loan_costs_numeric.loc[highest_costs.index]
)

print(
    highest_costs[
        [
            'total_loan_costs',
            'total_loan_costs_numeric',
            'loan_amount',
            'property_value',
            'loan_to_value_ratio',
            'interest_rate',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'total_loan_costs_numeric',
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)


# --------------------------------------------------------------
# 10. By loan product
# --------------------------------------------------------------

print("\n11. TOTAL LOAN COSTS BY LOAN PRODUCT")
print("-" * 70)

product_summary = (
    df.assign(
        total_loan_costs_numeric=total_loan_costs_numeric
    )
    .groupby(
        'derived_loan_product_type',
        dropna=False
    )['total_loan_costs_numeric']
    .agg(
        ['count', 'min', 'median', 'mean', 'max']
    )
    .sort_values(
        'count',
        ascending=False
    )
)

print(product_summary)


# --------------------------------------------------------------
# 11. By action taken
# --------------------------------------------------------------

print("\n12. TOTAL LOAN COSTS BY ACTION TAKEN")
print("-" * 70)

action_summary = (
    df.assign(
        total_loan_costs_numeric=total_loan_costs_numeric
    )
    .groupby(
        'action_taken',
        dropna=False
    )['total_loan_costs_numeric']
    .agg(
        ['count', 'min', 'median', 'mean', 'max']
    )
)

print(action_summary)


# --------------------------------------------------------------
# 12. Cost relative to loan amount
# --------------------------------------------------------------

print("\n13. LOAN COST AS % OF LOAN AMOUNT")
print("-" * 70)

cost_ratio = (
    total_loan_costs_numeric /
    df['loan_amount'] * 100
)

print(
    cost_ratio.describe()
)

print("\nCost ratio percentiles:")

print(
    cost_ratio.quantile(
        [0.01, 0.05, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99, 0.999]
    )
)


# --------------------------------------------------------------
# 13. Extremely high cost-to-loan ratios
# --------------------------------------------------------------

print("\n14. EXTREME COST-TO-LOAN RATIOS")
print("-" * 70)

for threshold in [5, 10, 25, 50, 100]:

    count = (
        cost_ratio > threshold
    ).sum()

    pct = count / len(df) * 100

    print(
        f">{threshold}% of loan amount: "
        f"{count:,} records ({pct:.4f}%)"
    )


# --------------------------------------------------------------
# Final investigation summary
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("INVESTIGATION SUMMARY")
print("=" * 70)

print("Total records:", len(df))
print("Missing:", missing_count)
print("Exempt:", exempt_mask.sum())
print(
    "Numeric values:",
    total_loan_costs_numeric.notna().sum()
)
print("Negative:", negative_count)
print("Zero:", zero_count)
print(
    "Maximum:",
    total_loan_costs_numeric.max()
)

======================================================================
TOTAL LOAN COSTS - DATA QUALITY INVESTIGATION
======================================================================

1. DATA TYPE
----------------------------------------------------------------------
Original dtype: object

2. MISSING VALUES
----------------------------------------------------------------------
Missing: 288541
Missing %: 40.63

3. MOST COMMON VALUES
----------------------------------------------------------------------
total_loan_costs
NaN       288541
Exempt     16759
0           9762
0.0         8018
34           763
158.4        588
500          456
795          305
500.0        265
5915         232
307          222
158.4        208
311.5        190
300          186
695.0        154
635          144
90           136
180          120
275          113
800          109
Name: count, dtype: int64

4. EXEMPT VALUES
----------------------------------------------------------------------
Exempt count: 16759
Exempt %: 2.36

5. NUMERIC CONVERSION
----------------------------------------------------------------------
count    404906.000000
mean       8343.419203
std        6135.631028
min           0.000000
25%        4499.740000
50%        7479.290000
75%       11080.177500
max      697328.350000
Name: total_loan_costs, dtype: float64

6. NEGATIVE AND ZERO VALUES
----------------------------------------------------------------------
Negative values: 0
Zero values: 17780

7. PERCENTILES
----------------------------------------------------------------------
0.010        0.00000
0.050       98.72000
0.250     4499.74000
0.500     7479.29000
0.750    11080.17750
0.900    15472.19500
0.950    18729.02500
0.990    27066.59650
0.995    31326.13300
0.999    45590.96505
Name: total_loan_costs, dtype: float64

8. EXTREME VALUE THRESHOLDS
----------------------------------------------------------------------
>   1,000: 370,031 records (52.1019%)
>   5,000: 287,027 records (40.4146%)
>  10,000: 125,834 records (17.7180%)
>  25,000:   5,883 records (0.8284%)
>  50,000:     288 records (0.0406%)
> 100,000:      17 records (0.0024%)
> 500,000:       2 records (0.0003%)

9. NEGATIVE VALUE RECORDS
----------------------------------------------------------------------
Records: 0

10. HIGHEST TOTAL LOAN COSTS
----------------------------------------------------------------------
total_loan_costs  total_loan_costs_numeric  loan_amount property_value loan_to_value_ratio interest_rate     derived_loan_product_type            derived_dwelling_category total_units  loan_purpose  action_taken
       697328.35                 697328.35     685000.0         865000                  80         6.625       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       590452.36                 590452.36     575000.0         605000              93.917         6.375                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       464248.36                 464248.36     455000.0         455000                96.5          6.49                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       304086.04                 304086.04     295000.0         295000                96.5          5.99                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       254062.97                 254062.97    1115000.0        1435000              77.762          5.98       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       163349.22                 163349.22    4555000.0      6505000.0                70.0         5.375       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       147919.56                 147919.56    1705000.0        2135000                80.0           5.0       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       143689.85                 143689.85    3005000.0      5255000.0              57.143         8.625       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       133879.16                 133879.16    6635000.0        7805000                  85          7.25       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             2             1
       116431.75                 116431.75    3945000.0      8805000.0               44.86         7.875       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            31             1
          113522                 113522.00     485000.0         415000             116.659         3.375       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            31             1
       111453.14                 111453.14     495000.0       785000.0              63.264          6.99       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       109603.28                 109603.28    2035000.0        2205000              90.909          5.75                 VA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       107559.19                 107559.19    3175000.0        3175000                 100          6.25                 VA:First Lien Single Family (1-4 Units):Site-Built           1            32             1
        106052.5                 106052.50    1895000.0        1835000                 100          7.25                 VA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       101332.96                 101332.96    7485000.0     23915000.0                70.4         5.825 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
        100222.0                 100222.00    2405000.0      3005000.0                80.0         6.875       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
        96905.88                  96905.88    2405000.0        3005000                  80         7.875       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
         96676.1                  96676.10    2245000.0        2805000                  80         7.125       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
        95136.08                  95136.08    3365000.0      4205000.0                80.0         8.375       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1

11. TOTAL LOAN COSTS BY LOAN PRODUCT
----------------------------------------------------------------------
                                count  min     median          mean        max
derived_loan_product_type
Conventional:First Lien        233592  0.0   6643.855   7703.730604  697328.35
FHA:First Lien                  93496  0.0  11036.485  12127.605590  590452.36
VA:First Lien                   51192  0.0   6494.545   8081.322679  109603.28
Conventional:Subordinate Lien   24690  0.0    158.400    778.441656  101332.96
FSA/RHS:First Lien               1488  0.0   7386.875   8032.897937   29594.80
FSA/RHS:Subordinate Lien          432  0.0      0.000      0.578704     250.00
FHA:Subordinate Lien               16  0.0   1532.000   1002.946250    1549.00

12. TOTAL LOAN COSTS BY ACTION TAKEN
----------------------------------------------------------------------
               count  min   median         mean        max
action_taken
1             404906  0.0  7479.29  8343.419203  697328.35
2                  0  NaN      NaN          NaN        NaN
3                  0  NaN      NaN          NaN        NaN

13. LOAN COST AS % OF LOAN AMOUNT
----------------------------------------------------------------------
count    404906.000000
mean          2.803016
std           1.906389
min           0.000000
25%           1.446446
50%           2.662745
75%           3.883457
max         140.000000
dtype: float64

Cost ratio percentiles:
0.010     0.000000
0.050     0.058065
0.250     1.446446
0.500     2.662745
0.750     3.883457
0.900     5.148721
0.950     5.873073
0.990     7.488304
0.999    10.727681
dtype: float64

14. EXTREME COST-TO-LOAN RATIOS
----------------------------------------------------------------------
>5% of loan amount: 45,851 records (6.4560%)
>10% of loan amount: 628 records (0.0884%)
>25% of loan amount: 48 records (0.0068%)
>50% of loan amount: 30 records (0.0042%)
>100% of loan amount: 8 records (0.0011%)

======================================================================
INVESTIGATION SUMMARY
======================================================================
Total records: 710206
Missing: 288541
Exempt: 16759
Numeric values: 404906
Negative: 0
Zero: 17780
Maximum: 697328.35

In [64]:
# ==============================================================
# TOTAL LOAN COSTS - EXTREME RATIO INVESTIGATION
# ==============================================================

print("=" * 70)
print("TOTAL LOAN COSTS - EXTREME RATIO INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Create cost-to-loan ratio
# --------------------------------------------------------------

cost_to_loan_ratio = (
    total_loan_costs_numeric /
    df['loan_amount'] * 100
)


# --------------------------------------------------------------
# 2. Inspect records where costs exceed 25% of loan amount
# --------------------------------------------------------------

high_ratio_records = df[
    total_loan_costs_numeric.notna() &
    df['loan_amount'].notna() &
    (cost_to_loan_ratio > 25)
].copy()

high_ratio_records['total_loan_costs_numeric'] = (
    total_loan_costs_numeric.loc[high_ratio_records.index]
)

high_ratio_records['cost_to_loan_ratio'] = (
    cost_to_loan_ratio.loc[high_ratio_records.index]
)


print("\n1. COST > 25% OF LOAN AMOUNT")
print("-" * 70)

print("Records:", len(high_ratio_records))

print(
    high_ratio_records[
        [
            'total_loan_costs',
            'total_loan_costs_numeric',
            'cost_to_loan_ratio',
            'loan_amount',
            'property_value',
            'loan_to_value_ratio',
            'interest_rate',
            'rate_spread',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'cost_to_loan_ratio',
        ascending=False
    )
    .to_string(index=False)
)


# --------------------------------------------------------------
# 3. Inspect records where costs exceed 100%
# --------------------------------------------------------------

extreme_ratio_records = df[
    total_loan_costs_numeric.notna() &
    df['loan_amount'].notna() &
    (cost_to_loan_ratio > 100)
].copy()

extreme_ratio_records['total_loan_costs_numeric'] = (
    total_loan_costs_numeric.loc[extreme_ratio_records.index]
)

extreme_ratio_records['cost_to_loan_ratio'] = (
    cost_to_loan_ratio.loc[extreme_ratio_records.index]
)


print("\n" + "=" * 70)
print("2. COST > 100% OF LOAN AMOUNT")
print("-" * 70)

print("Records:", len(extreme_ratio_records))

print(
    extreme_ratio_records[
        [
            'total_loan_costs',
            'total_loan_costs_numeric',
            'cost_to_loan_ratio',
            'loan_amount',
            'property_value',
            'loan_to_value_ratio',
            'interest_rate',
            'rate_spread',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'cost_to_loan_ratio',
        ascending=False
    )
    .to_string(index=False)
)


# --------------------------------------------------------------
# 4. Very high absolute costs
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("3. COST > $100,000")
print("-" * 70)

very_high_costs = df[
    total_loan_costs_numeric > 100_000
].copy()

very_high_costs['total_loan_costs_numeric'] = (
    total_loan_costs_numeric.loc[very_high_costs.index]
)

very_high_costs['cost_to_loan_ratio'] = (
    cost_to_loan_ratio.loc[very_high_costs.index]
)

print("Records:", len(very_high_costs))

print(
    very_high_costs[
        [
            'total_loan_costs',
            'total_loan_costs_numeric',
            'cost_to_loan_ratio',
            'loan_amount',
            'property_value',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units',
            'action_taken'
        ]
    ]
    .sort_values(
        'total_loan_costs_numeric',
        ascending=False
    )
    .to_string(index=False)
)


# --------------------------------------------------------------
# 5. Zero-cost records
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("4. ZERO TOTAL LOAN COSTS")
print("-" * 70)

zero_cost_records = df[
    total_loan_costs_numeric == 0
]

print("Records:", len(zero_cost_records))

print("\nBy loan product:")

print(
    zero_cost_records[
        'derived_loan_product_type'
    ]
    .value_counts(dropna=False)
)


print("\nBy loan purpose:")

print(
    zero_cost_records[
        'loan_purpose'
    ]
    .value_counts(dropna=False)
)


# --------------------------------------------------------------
# 6. Check relationship between cost and loan amount
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("5. COST RATIO BY LOAN PRODUCT")
print("-" * 70)

ratio_product_summary = (
    df.assign(
        cost_to_loan_ratio=cost_to_loan_ratio
    )
    .groupby(
        'derived_loan_product_type',
        dropna=False
    )['cost_to_loan_ratio']
    .agg(
        ['count', 'min', 'median', 'mean', 'max']
    )
    .sort_values(
        'count',
        ascending=False
    )
)

print(ratio_product_summary)


# --------------------------------------------------------------
# 7. Final summary
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("INVESTIGATION SUMMARY")
print("=" * 70)

print("Numeric cost records:", total_loan_costs_numeric.notna().sum())
print("Zero cost records:", zero_count)
print("Negative cost records:", negative_count)
print("Cost > 25% of loan:", (cost_to_loan_ratio > 25).sum())
print("Cost > 50% of loan:", (cost_to_loan_ratio > 50).sum())
print("Cost > 100% of loan:", (cost_to_loan_ratio > 100).sum())
print("Cost > $100,000:", (total_loan_costs_numeric > 100_000).sum())

======================================================================
TOTAL LOAN COSTS - EXTREME RATIO INVESTIGATION
======================================================================

1. COST > 25% OF LOAN AMOUNT
----------------------------------------------------------------------
Records: 48
total_loan_costs  total_loan_costs_numeric  cost_to_loan_ratio  loan_amount property_value loan_to_value_ratio interest_rate rate_spread     derived_loan_product_type            derived_dwelling_category total_units  loan_purpose  action_taken
            7000                   7000.00          140.000000       5000.0         435000            100.1524             0       -6.69 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         5643.75                   5643.75          112.875000       5000.0         325000            100.7671             0       -6.78 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            5250                   5250.00          105.000000       5000.0         285000             101.134             0       -7.12 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          5162.5                   5162.50          103.250000       5000.0         285000            100.1525             0       -6.65 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
       304086.04                 304086.04          103.080014     295000.0         295000                96.5          5.99      -0.117                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       590452.36                 590452.36          102.687367     575000.0         605000              93.917         6.375       0.239                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       464248.36                 464248.36          102.032607     455000.0         455000                96.5          6.49       0.501                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       697328.35                 697328.35          101.799759     685000.0         865000                  80         6.625      -0.031       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
          4812.5                   4812.50           96.250000       5000.0         275000            100.1524             0       -7.12 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          4497.5                   4497.50           89.950000       5000.0         245000            101.1343             0       -7.13 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            4375                   4375.00           87.500000       5000.0         255000             100.152             0        -6.9 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            4375                   4375.00           87.500000       5000.0         215000            102.1158             0       -6.85 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            4375                   4375.00           87.500000       5000.0         255000             101.134             0       -6.43 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            4375                   4375.00           87.500000       5000.0         265000            101.1342             0       -6.65 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
        47823.65                  47823.65           86.952091      55000.0         235000               79.66             9       3.394 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             4             1
            4200                   4200.00           84.000000       5000.0         255000             99.5617             0       -6.68 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            3911                   3911.00           78.220000       5000.0         205000              100.43             0         NaN Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          3867.5                   3867.50           77.350000       5000.0         225000            101.1339             0       -6.66 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          3762.5                   3762.50           75.250000       5000.0         215000            100.1521             0       -6.66 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            3500                   3500.00           70.000000       5000.0         205000            102.1163             0       -6.55 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            3500                   3500.00           70.000000       5000.0         185000            101.1339             0       -6.06 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            3465                   3465.00           69.300000       5000.0         195000            100.1517             0       -6.88 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         3361.45                   3361.45           67.229000       5000.0         245000            102.1163             0       -6.06 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            3325                   3325.00           66.500000       5000.0         225000             84.8395             0       -6.06 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         3164.95                   3164.95           63.299000       5000.0         335000            187.2033             0       -6.66 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            3150                   3150.00           63.000000       5000.0         205000             102.116             0       -7.13 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         3135.36                   3135.36           62.707200       5000.0         205000             101.134             0       -6.66 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         3044.59                   3044.59           60.891800       5000.0         285000              99.446         7.125       4.701 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         2976.45                   2976.45           59.529000       5000.0         305000             93.4633             0       -7.05 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          2502.5                   2502.50           50.050000       5000.0         145000            102.1154             0       -6.85 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            2310                   2310.00           46.200000       5000.0         145000             94.2608             0       -7.42 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         2181.55                   2181.55           43.631000       5000.0         325000              99.446             0      -5.717 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            6125                   6125.00           40.833333      15000.0         335000            100.2653             0       -6.51 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
        71426.58                  71426.58           40.815189     175000.0         235000                  75          6.99       0.471       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
            5740                   5740.00           38.266667      15000.0         365000            102.1162             0       -6.53 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          5232.5                   5232.50           34.883333      15000.0         305000            102.1163             0       -6.68 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
        85551.13                  85551.13           33.549463     255000.0         275000                  95         6.625      -0.222       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
        62197.15                  62197.15           31.895974     195000.0         285000              78.367           6.5         NaN                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
            1549                   1549.00           30.980000       5000.0         215000              99.445             0       -6.96 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            1549                   1549.00           30.980000       5000.0         275000              99.445             0       -7.05          FHA:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            1549                   1549.00           30.980000       5000.0         285000                97.9             0       -6.69 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            1549                   1549.00           30.980000       5000.0         315000              99.445             0       -7.19 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            1549                   1549.00           30.980000       5000.0         285000              99.445             0       -6.95 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            4550                   4550.00           30.333333      15000.0         275000             100.996             0       -6.54 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         1515.15                   1515.15           30.303000       5000.0         125000            104.0394             0       -6.93 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         4060.24                   4060.24           27.068267      15000.0         305000              101.41             0         NaN Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          3937.5                   3937.50           26.250000      15000.0         305000             103.098             0          -7 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
        79360.34                  79360.34           25.193759     315000.0        1365000              23.954           6.5         NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1

======================================================================
2. COST > 100% OF LOAN AMOUNT
----------------------------------------------------------------------
Records: 8
total_loan_costs  total_loan_costs_numeric  cost_to_loan_ratio  loan_amount property_value loan_to_value_ratio interest_rate rate_spread     derived_loan_product_type            derived_dwelling_category total_units  loan_purpose  action_taken
            7000                   7000.00          140.000000       5000.0         435000            100.1524             0       -6.69 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
         5643.75                   5643.75          112.875000       5000.0         325000            100.7671             0       -6.78 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
            5250                   5250.00          105.000000       5000.0         285000             101.134             0       -7.12 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
          5162.5                   5162.50          103.250000       5000.0         285000            100.1525             0       -6.65 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
       304086.04                 304086.04          103.080014     295000.0         295000                96.5          5.99      -0.117                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       590452.36                 590452.36          102.687367     575000.0         605000              93.917         6.375       0.239                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       464248.36                 464248.36          102.032607     455000.0         455000                96.5          6.49       0.501                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1             1
       697328.35                 697328.35          101.799759     685000.0         865000                  80         6.625      -0.031       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1

======================================================================
3. COST > $100,000
----------------------------------------------------------------------
Records: 17
total_loan_costs  total_loan_costs_numeric  cost_to_loan_ratio  loan_amount property_value     derived_loan_product_type            derived_dwelling_category total_units  action_taken
       697328.35                 697328.35          101.799759     685000.0         865000       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       590452.36                 590452.36          102.687367     575000.0         605000                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1
       464248.36                 464248.36          102.032607     455000.0         455000                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1
       304086.04                 304086.04          103.080014     295000.0         295000                FHA:First Lien Single Family (1-4 Units):Site-Built           1             1
       254062.97                 254062.97           22.785917    1115000.0        1435000       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       163349.22                 163349.22            3.586152    4555000.0      6505000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       147919.56                 147919.56            8.675634    1705000.0        2135000       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       143689.85                 143689.85            4.781692    3005000.0      5255000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       133879.16                 133879.16            2.017772    6635000.0        7805000       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       116431.75                 116431.75            2.951375    3945000.0      8805000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
          113522                 113522.00           23.406598     485000.0         415000       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       111453.14                 111453.14           22.515786     495000.0       785000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1
       109603.28                 109603.28            5.385911    2035000.0        2205000                 VA:First Lien Single Family (1-4 Units):Site-Built           1             1
       107559.19                 107559.19            3.387691    3175000.0        3175000                 VA:First Lien Single Family (1-4 Units):Site-Built           1             1
        106052.5                 106052.50            5.596438    1895000.0        1835000                 VA:First Lien Single Family (1-4 Units):Site-Built           1             1
       101332.96                 101332.96            1.353814    7485000.0     23915000.0 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1
        100222.0                 100222.00            4.167235    2405000.0      3005000.0       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1

======================================================================
4. ZERO TOTAL LOAN COSTS
----------------------------------------------------------------------
Records: 17780

By loan product:
derived_loan_product_type
Conventional:Subordinate Lien    10404
Conventional:First Lien           5840
VA:First Lien                     1035
FSA/RHS:Subordinate Lien           431
FHA:First Lien                      64
FHA:Subordinate Lien                 4
FSA/RHS:First Lien                   2
Name: count, dtype: int64

By loan purpose:
loan_purpose
1     6933
4     3628
2     3096
32    3054
31    1069
Name: count, dtype: int64

======================================================================
5. COST RATIO BY LOAN PRODUCT
----------------------------------------------------------------------
                                count  min    median      mean         max
derived_loan_product_type
Conventional:First Lien        233592  0.0  2.294416  2.541200  101.799759
FHA:First Lien                  93496  0.0  4.028121  4.205178  103.080014
VA:First Lien                   51192  0.0  1.925425  2.270847   16.006436
Conventional:Subordinate Lien   24690  0.0  0.193548  1.068325  140.000000
FSA/RHS:First Lien               1488  0.0  3.530473  3.670720    9.711447
FSA/RHS:Subordinate Lien          432  0.0  0.000000  0.011574    5.000000
FHA:Subordinate Lien               16  0.0  6.128000  5.840870   30.980000

======================================================================
INVESTIGATION SUMMARY
======================================================================
Numeric cost records: 404906
Zero cost records: 17780
Negative cost records: 0
Cost > 25% of loan: 48
Cost > 50% of loan: 30
Cost > 100% of loan: 8
Cost > $100,000: 17

In [65]:


# ==============================================================
# FINAL TOTAL LOAN COSTS DATA QUALITY TREATMENT
# ==============================================================

print("=" * 70)
print("FINAL TOTAL LOAN COSTS DATA QUALITY TREATMENT")
print("=" * 70)


# --------------------------------------------------------------
# 1. Preserve original column
# --------------------------------------------------------------

df['total_loan_costs_original'] = df['total_loan_costs']


# --------------------------------------------------------------
# 2. Create numeric analysis column
# --------------------------------------------------------------

df['total_loan_costs_analysis_value'] = pd.to_numeric(
    df['total_loan_costs'],
    errors='coerce'
)


# --------------------------------------------------------------
# 3. Create cost-to-loan ratio
# --------------------------------------------------------------

df['total_loan_cost_ratio'] = (
    df['total_loan_costs_analysis_value'] /
    df['loan_amount'] * 100
)


# --------------------------------------------------------------
# 4. Create unusual-value flags
# --------------------------------------------------------------

df['total_loan_costs_high_ratio_flag'] = (
    df['total_loan_cost_ratio'] > 25
)

df['total_loan_costs_extreme_ratio_flag'] = (
    df['total_loan_cost_ratio'] > 100
)

df['total_loan_costs_high_absolute_flag'] = (
    df['total_loan_costs_analysis_value'] > 100_000
)


# --------------------------------------------------------------
# 5. Create quality category
# --------------------------------------------------------------

df['total_loan_costs_quality_category'] = 'Valid / Usable'

df.loc[
    df['total_loan_costs'].isna(),
    'total_loan_costs_quality_category'
] = 'Missing'

df.loc[
    df['total_loan_costs'].astype(str).str.strip().eq('Exempt'),
    'total_loan_costs_quality_category'
] = 'Exempt'

df.loc[
    df['total_loan_costs_high_ratio_flag'],
    'total_loan_costs_quality_category'
] = 'High Ratio - Retained'


# --------------------------------------------------------------
# 6. Verification
# --------------------------------------------------------------

print("\nTOTAL LOAN COSTS QUALITY CATEGORY")
print("-" * 70)

print(
    df['total_loan_costs_quality_category']
    .value_counts(dropna=False)
)


print("\nHIGH RATIO FLAG")
print("-" * 70)

print(
    df['total_loan_costs_high_ratio_flag']
    .value_counts()
)


print("\nEXTREME RATIO FLAG (>100%)")
print("-" * 70)

print(
    df['total_loan_costs_extreme_ratio_flag']
    .value_counts()
)


print("\nHIGH ABSOLUTE COST FLAG (> $100,000)")
print("-" * 70)

print(
    df['total_loan_costs_high_absolute_flag']
    .value_counts()
)


# --------------------------------------------------------------
# 7. Final numerical summary
# --------------------------------------------------------------

print("\nFINAL ANALYSIS SUMMARY")
print("-" * 70)

print(
    df['total_loan_costs_analysis_value']
    .describe()
)


# --------------------------------------------------------------
# 8. Final record counts
# --------------------------------------------------------------

print("\nFINAL TOTAL LOAN COSTS SUMMARY")
print("-" * 70)

print("Total records:", len(df))

print(
    "Missing:",
    df['total_loan_costs'].isna().sum()
)

print(
    "Exempt:",
    df['total_loan_costs']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print(
    "Numeric analysis values:",
    df['total_loan_costs_analysis_value'].notna().sum()
)

print(
    "Zero costs:",
    (df['total_loan_costs_analysis_value'] == 0).sum()
)

print(
    "Negative costs:",
    (df['total_loan_costs_analysis_value'] < 0).sum()
)

print(
    "High ratio >25%:",
    df['total_loan_costs_high_ratio_flag'].sum()
)

print(
    "Extreme ratio >100%:",
    df['total_loan_costs_extreme_ratio_flag'].sum()
)

print(
    "High absolute cost >$100,000:",
    df['total_loan_costs_high_absolute_flag'].sum()
)


# --------------------------------------------------------------
# 9. Preservation check
# --------------------------------------------------------------

print("\nORIGINAL VALUE PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'total_loan_costs_original',
            'total_loan_costs_analysis_value',
            'total_loan_cost_ratio',
            'total_loan_costs_high_ratio_flag',
            'total_loan_costs_quality_category'
        ]
    ]
    .head(15)
)

======================================================================
FINAL TOTAL LOAN COSTS DATA QUALITY TREATMENT
======================================================================

TOTAL LOAN COSTS QUALITY CATEGORY
----------------------------------------------------------------------
total_loan_costs_quality_category
Valid / Usable           404858
Missing                  288541
Exempt                    16759
High Ratio - Retained        48
Name: count, dtype: int64

HIGH RATIO FLAG
----------------------------------------------------------------------
total_loan_costs_high_ratio_flag
False    710158
True         48
Name: count, dtype: int64

EXTREME RATIO FLAG (>100%)
----------------------------------------------------------------------
total_loan_costs_extreme_ratio_flag
False    710198
True          8
Name: count, dtype: int64

HIGH ABSOLUTE COST FLAG (> $100,000)
----------------------------------------------------------------------
total_loan_costs_high_absolute_flag
False    710189
True         17
Name: count, dtype: int64

FINAL ANALYSIS SUMMARY
----------------------------------------------------------------------
count    404906.000000
mean       8343.419203
std        6135.631028
min           0.000000
25%        4499.740000
50%        7479.290000
75%       11080.177500
max      697328.350000
Name: total_loan_costs_analysis_value, dtype: float64

FINAL TOTAL LOAN COSTS SUMMARY
----------------------------------------------------------------------
Total records: 710206
Missing: 288541
Exempt: 16759
Numeric analysis values: 404906
Zero costs: 17780
Negative costs: 0
High ratio >25%: 48
Extreme ratio >100%: 8
High absolute cost >$100,000: 17

ORIGINAL VALUE PRESERVATION CHECK
----------------------------------------------------------------------
   total_loan_costs_original  total_loan_costs_analysis_value  \
0                       3137                          3137.00
1                    7969.86                          7969.86
2                    8832.65                          8832.65
3                        NaN                              NaN
4                    3789.31                          3789.31
5                        NaN                              NaN
6                        NaN                              NaN
7                    4726.06                          4726.06
8                        NaN                              NaN
9                   22038.03                         22038.03
10                   2799.24                          2799.24
11                  25447.42                         25447.42
12                   4010.44                          4010.44
13                  20188.11                         20188.11
14                   12876.5                         12876.50

    total_loan_cost_ratio  total_loan_costs_high_ratio_flag  \
0                2.323704                             False
1                1.790980                             False
2                2.030494                             False
3                     NaN                             False
4                1.762470                             False
5                     NaN                             False
6                     NaN                             False
7                1.718567                             False
8                     NaN                             False
9                3.642650                             False
10               1.244107                             False
11               5.246891                             False
12               1.572722                             False
13               5.383496                             False
14               2.654948                             False

   total_loan_costs_quality_category
0                     Valid / Usable
1                     Valid / Usable
2                     Valid / Usable
3                            Missing
4                     Valid / Usable
5                            Missing
6                            Missing
7                     Valid / Usable
8                            Missing
9                     Valid / Usable
10                    Valid / Usable
11                    Valid / Usable
12                    Valid / Usable
13                    Valid / Usable
14                    Valid / Usable

In [66]:
# ==============================================================
# TOTAL POINTS AND FEES - DATA QUALITY INVESTIGATION
# ==============================================================

print("=" * 70)
print("TOTAL POINTS AND FEES - DATA QUALITY INVESTIGATION")
print("=" * 70)


# --------------------------------------------------------------
# 1. Basic information
# --------------------------------------------------------------

print("\n1. BASIC INFORMATION")
print("-" * 70)

print("Data type:", df['total_points_and_fees'].dtype)
print("Missing:", df['total_points_and_fees'].isna().sum())
print("Total records:", len(df))


# --------------------------------------------------------------
# 2. Most common raw values
# --------------------------------------------------------------

print("\n2. MOST COMMON RAW VALUES")
print("-" * 70)

print(
    df['total_points_and_fees']
    .value_counts(dropna=False)
    .head(30)
)


# --------------------------------------------------------------
# 3. Exempt values
# --------------------------------------------------------------

print("\n3. EXEMPT VALUES")
print("-" * 70)

exempt_mask = (
    df['total_points_and_fees']
    .astype(str)
    .str.strip()
    .eq('Exempt')
)

print("Exempt count:", exempt_mask.sum())


# --------------------------------------------------------------
# 4. Numeric conversion
# --------------------------------------------------------------

total_points_and_fees_numeric = pd.to_numeric(
    df['total_points_and_fees'],
    errors='coerce'
)

print("\n4. NUMERIC VALUES")
print("-" * 70)

print(
    total_points_and_fees_numeric
    .describe()
)


# --------------------------------------------------------------
# 5. Negative and zero values
# --------------------------------------------------------------

print("\n5. NEGATIVE / ZERO VALUES")
print("-" * 70)

print(
    "Negative:",
    (total_points_and_fees_numeric < 0).sum()
)

print(
    "Zero:",
    (total_points_and_fees_numeric == 0).sum()
)


# --------------------------------------------------------------
# 6. Percentiles
# --------------------------------------------------------------

print("\n6. PERCENTILES")
print("-" * 70)

print(
    total_points_and_fees_numeric
    .quantile([
        0.01,
        0.05,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
        0.995,
        0.999
    ])
)


# --------------------------------------------------------------
# 7. Extreme-value thresholds
# --------------------------------------------------------------

print("\n7. EXTREME VALUE THRESHOLDS")
print("-" * 70)

for threshold in [1000, 5000, 10000, 25000, 50000, 100000, 500000]:

    count = (
        total_points_and_fees_numeric > threshold
    ).sum()

    percentage = count / len(df) * 100

    print(
        f">{threshold:>7,}: "
        f"{count:>8,} records "
        f"({percentage:.4f}%)"
    )


# --------------------------------------------------------------
# 8. Points & fees as percentage of loan amount
# --------------------------------------------------------------

points_fees_ratio = (
    total_points_and_fees_numeric /
    df['loan_amount'] * 100
)

print("\n8. POINTS & FEES AS % OF LOAN AMOUNT")
print("-" * 70)

print(
    points_fees_ratio
    .describe()
)


print("\nRatio percentiles:")

print(
    points_fees_ratio
    .quantile([
        0.01,
        0.05,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
        0.995,
        0.999
    ])
)


# --------------------------------------------------------------
# 9. High ratio thresholds
# --------------------------------------------------------------

print("\n9. HIGH POINTS & FEES RATIO")
print("-" * 70)

for threshold in [5, 10, 25, 50, 100]:

    count = (
        points_fees_ratio > threshold
    ).sum()

    percentage = count / len(df) * 100

    print(
        f">{threshold:>3}%: "
        f"{count:>8,} records "
        f"({percentage:.4f}%)"
    )


# --------------------------------------------------------------
# 10. Highest values
# --------------------------------------------------------------

print("\n10. HIGHEST POINTS & FEES VALUES")
print("-" * 70)

highest_records = df[
    total_points_and_fees_numeric.notna()
].copy()

highest_records['total_points_and_fees_numeric'] = (
    total_points_and_fees_numeric.loc[highest_records.index]
)

highest_records['points_fees_ratio'] = (
    points_fees_ratio.loc[highest_records.index]
)

print(
    highest_records[
        [
            'total_points_and_fees',
            'total_points_and_fees_numeric',
            'points_fees_ratio',
            'loan_amount',
            'property_value',
            'loan_to_value_ratio',
            'interest_rate',
            'rate_spread',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'total_points_and_fees_numeric',
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)


# --------------------------------------------------------------
# 11. Highest ratio records
# --------------------------------------------------------------

print("\n11. HIGHEST POINTS & FEES RATIO RECORDS")
print("-" * 70)

high_ratio_records = df[
    total_points_and_fees_numeric.notna()
].copy()

high_ratio_records['total_points_and_fees_numeric'] = (
    total_points_and_fees_numeric.loc[high_ratio_records.index]
)

high_ratio_records['points_fees_ratio'] = (
    points_fees_ratio.loc[high_ratio_records.index]
)

print(
    high_ratio_records[
        [
            'total_points_and_fees',
            'total_points_and_fees_numeric',
            'points_fees_ratio',
            'loan_amount',
            'property_value',
            'loan_to_value_ratio',
            'interest_rate',
            'rate_spread',
            'derived_loan_product_type',
            'derived_dwelling_category',
            'total_units',
            'loan_purpose',
            'action_taken'
        ]
    ]
    .sort_values(
        'points_fees_ratio',
        ascending=False
    )
    .head(20)
    .to_string(index=False)
)


# --------------------------------------------------------------
# 12. Product-level summary
# --------------------------------------------------------------

print("\n12. POINTS & FEES BY LOAN PRODUCT")
print("-" * 70)

product_summary = (
    df.assign(
        points_fees_numeric=total_points_and_fees_numeric,
        points_fees_ratio=points_fees_ratio
    )
    .groupby(
        'derived_loan_product_type',
        dropna=False
    )[
        'points_fees_numeric'
    ]
    .agg([
        'count',
        'min',
        'median',
        'mean',
        'max'
    ])
    .sort_values(
        'count',
        ascending=False
    )
)

print(product_summary)


# --------------------------------------------------------------
# 13. Action-level summary
# --------------------------------------------------------------

print("\n13. POINTS & FEES BY ACTION")
print("-" * 70)

print(
    df.assign(
        points_fees_numeric=total_points_and_fees_numeric
    )
    .groupby('action_taken')['points_fees_numeric']
    .agg([
        'count',
        'min',
        'median',
        'mean',
        'max'
    ])
)


# --------------------------------------------------------------
# 14. Final investigation summary
# --------------------------------------------------------------

print("\n" + "=" * 70)
print("INVESTIGATION SUMMARY")
print("=" * 70)

print(
    "Numeric records:",
    total_points_and_fees_numeric.notna().sum()
)

print(
    "Missing:",
    df['total_points_and_fees'].isna().sum()
)

print(
    "Exempt:",
    exempt_mask.sum()
)

print(
    "Zero:",
    (total_points_and_fees_numeric == 0).sum()
)

print(
    "Negative:",
    (total_points_and_fees_numeric < 0).sum()
)

======================================================================
TOTAL POINTS AND FEES - DATA QUALITY INVESTIGATION
======================================================================

1. BASIC INFORMATION
----------------------------------------------------------------------
Data type: object
Missing: 679709
Total records: 710206

2. MOST COMMON RAW VALUES
----------------------------------------------------------------------
total_points_and_fees
NaN       679709
Exempt     16759
0           3151
3914.0      1479
4500.0       461
3914         389
3730         221
4500         202
2400         191
499          157
799           93
3730.0        89
97            80
1350          54
400           35
2240          32
1096          30
113.75        28
1500          25
1191          22
295           20
744           17
1018          16
2000          15
2300          15
950.0         12
3000.0        11
2997          11
1240          10
3195          10
Name: count, dtype: int64

3. EXEMPT VALUES
----------------------------------------------------------------------
Exempt count: 16759

4. NUMERIC VALUES
----------------------------------------------------------------------
count    13738.000000
mean      2719.769854
std       2769.410547
min          0.000000
25%        499.000000
50%       2731.190000
75%       3914.000000
max      74403.060000
Name: total_points_and_fees, dtype: float64

5. NEGATIVE / ZERO VALUES
----------------------------------------------------------------------
Negative: 0
Zero: 3159

6. PERCENTILES
----------------------------------------------------------------------
0.010        0.0000
0.050        0.0000
0.250      499.0000
0.500     2731.1900
0.750     3914.0000
0.900     4500.0000
0.950     5866.6865
0.990    11020.4469
0.995    16226.0907
0.999    29831.5983
Name: total_points_and_fees, dtype: float64

7. EXTREME VALUE THRESHOLDS
----------------------------------------------------------------------
>  1,000:    9,937 records (1.3992%)
>  5,000:      990 records (0.1394%)
> 10,000:      179 records (0.0252%)
> 25,000:       22 records (0.0031%)
> 50,000:        3 records (0.0004%)
>100,000:        0 records (0.0000%)
>500,000:        0 records (0.0000%)

8. POINTS & FEES AS % OF LOAN AMOUNT
----------------------------------------------------------------------
count    13738.000000
mean         2.390662
std          1.695185
min          0.000000
25%          0.475238
50%          2.701380
75%          3.727619
max         13.287760
dtype: float64

Ratio percentiles:
0.010    0.000000
0.050    0.000000
0.250    0.475238
0.500    2.701380
0.750    3.727619
0.900    4.604706
0.950    4.779906
0.990    5.047849
0.995    5.314164
0.999    8.191863
dtype: float64

9. HIGH POINTS & FEES RATIO
----------------------------------------------------------------------
>  5%:      172 records (0.0242%)
> 10%:        4 records (0.0006%)
> 25%:        0 records (0.0000%)
> 50%:        0 records (0.0000%)
>100%:        0 records (0.0000%)

10. HIGHEST POINTS & FEES VALUES
----------------------------------------------------------------------
total_points_and_fees  total_points_and_fees_numeric  points_fees_ratio  loan_amount property_value loan_to_value_ratio interest_rate rate_spread     derived_loan_product_type            derived_dwelling_category total_units  loan_purpose  action_taken
             74403.06                       74403.06          13.168683     565000.0         705000                  80          6.49      -0.062       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
             67724.04                       67724.04           6.607223    1025000.0        5505000               18.64          8.25       2.107       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
             65192.36                       65192.36           3.097024    2105000.0            NaN                 NaN            12         NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
             43634.57                       43634.57           6.018561     725000.0        1075000                  75          6.99       0.076       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
                42195                       42195.00           5.241615     805000.0        3105000               25.81           7.5       0.988       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
             39156.25                       39156.25           2.911245    1345000.0            NaN                 NaN         13.25         NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
             36894.85                       36894.85           5.308612     695000.0            NaN                 NaN            12         NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            31             1
             36541.34                       36541.34          13.287760     275000.0         365000                  75          7.25       0.383       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
                35545                       35545.00          10.610448     335000.0         495000                  70         7.875       1.297       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
                35535                       35535.00           4.205325     845000.0        1345000               64.11         7.875       1.956       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
             34370.44                       34370.44           5.681064     605000.0        1115000                53.9         5.625      -0.932       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
              34336.8                       34336.80           3.107403    1105000.0            NaN                 NaN          12.5         NaN       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
                29981                       29981.00           2.815117    1065000.0        1425000                  75         8.875       2.662       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
              29864.1                       29864.10           3.452497     865000.0        1085000                  80         9.125       2.996       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
                29820                       29820.00           7.016471     425000.0         595000                  75          7.25       1.159       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
              29722.8                       29722.80          10.808291     275000.0         375000                  75          8.75           2       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1
              28782.5                       28782.50           7.675333     375000.0         505000                  75         7.375       0.723       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
                28350                       28350.00           9.000000     315000.0        1255000                  90            13       6.485 Conventional:Subordinate Lien Single Family (1-4 Units):Site-Built           1             1             1
             27579.74                       27579.74           3.225701     855000.0        1135000               74.98             8        1.97       Conventional:First Lien Single Family (1-4 Units):Site-Built           1            32             1
                26695                       26695.00           7.519718     355000.0         485000               72.16           7.5       0.915       Conventional:First Lien Single Family (1-4 Units):Site-Built           1             1             1

11. HIGHEST POINTS & FEES RATIO RECORDS
----------------------------------------------------------------------
total_points_and_fees  total_points_and_fees_numeric  points_fees_ratio  loan_amount property_value loan_to_value_ratio interest_rate rate_spread     derived_loan_product_type              derived_dwelling_category total_units  loan_purpose  action_taken
             36541.34                       36541.34          13.287760     275000.0         365000                  75          7.25       0.383       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
             74403.06                       74403.06          13.168683     565000.0         705000                  80          6.49      -0.062       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
              29722.8                       29722.80          10.808291     275000.0         375000                  75          8.75           2       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
                35545                       35545.00          10.610448     335000.0         495000                  70         7.875       1.297       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
             25570.21                       25570.21           9.649136     265000.0            NaN               77.83         7.375       0.953       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             2             1
             11372.73                       11372.73           9.098184     125000.0         195000                  65          7.25       0.324       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             2             1
                17685                       17685.00           9.069231     195000.0         265000               72.49           6.5       0.569       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1            32             1
             16768.44                       16768.44           9.064022     185000.0         245000                  75          8.75       2.347       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
                28350                       28350.00           9.000000     315000.0        1255000                  90            13       6.485 Conventional:Subordinate Lien   Single Family (1-4 Units):Site-Built           1             1             1
             23550.88                       23550.88           8.563956     275000.0         425000                  65         7.625       1.194       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1            32             1
                18115                       18115.00           8.425581     215000.0         295000                  75         7.125       1.363       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
                13845                       13845.00           8.390909     165000.0         345000                  50             7       0.672       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
             19431.01                       19431.01           8.268515     235000.0         335000                  70         7.875       1.629       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
              18564.5                       18564.50           8.250889     225000.0         315000                  75         6.875       0.535       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
              1225.62                        1225.62           8.170800      15000.0        25000.0                 NaN         13.19       8.449       Conventional:First Lien Single Family (1-4 Units):Manufactured           1             1             1
              1212.25                        1212.25           8.081667      15000.0        35000.0                 NaN         11.86       7.291       Conventional:First Lien Single Family (1-4 Units):Manufactured           1             1             1
                18757                       18757.00           7.981702     235000.0         365000               64.91         7.125       0.474       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
                 9175                        9175.00           7.978261     115000.0         145000                  80         6.625       0.451       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
              17109.2                       17109.20           7.957767     215000.0         315000               68.73         7.125       0.826       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1
              17082.5                       17082.50           7.945349     215000.0         285000                  75         7.125       0.722       Conventional:First Lien   Single Family (1-4 Units):Site-Built           1             1             1

12. POINTS & FEES BY LOAN PRODUCT
----------------------------------------------------------------------
                               count       min    median          mean  \
derived_loan_product_type
Conventional:First Lien        10366      0.00   3708.00   3468.965281
Conventional:Subordinate Lien   3344      0.00      0.00    376.059767
FHA:First Lien                    15      0.00   3825.41   4496.990667
VA:First Lien                     11     41.00   4259.60   5183.650000
FHA:Subordinate Lien               1  21690.28  21690.28  21690.280000
FSA/RHS:First Lien                 1   1195.00   1195.00   1195.000000
FSA/RHS:Subordinate Lien           0       NaN       NaN           NaN

                                    max
derived_loan_product_type
Conventional:First Lien        74403.06
Conventional:Subordinate Lien  28350.00
FHA:First Lien                 13726.30
VA:First Lien                  10897.10
FHA:Subordinate Lien           21690.28
FSA/RHS:First Lien              1195.00
FSA/RHS:Subordinate Lien            NaN

13. POINTS & FEES BY ACTION
----------------------------------------------------------------------
              count  min   median         mean       max
action_taken
1             13738  0.0  2731.19  2719.769854  74403.06
2                 0  NaN      NaN          NaN       NaN
3                 0  NaN      NaN          NaN       NaN

======================================================================
INVESTIGATION SUMMARY
======================================================================
Numeric records: 13738
Missing: 679709
Exempt: 16759
Zero: 3159
Negative: 0

In [76]:
# ==============================================================
# FINAL TOTAL POINTS AND FEES DATA QUALITY TREATMENT
# ==============================================================

print("=" * 70)
print("FINAL TOTAL POINTS AND FEES DATA QUALITY TREATMENT")
print("=" * 70)


# --------------------------------------------------------------
# 1. Preserve original value
# --------------------------------------------------------------

df['total_points_and_fees_original'] = (
    df['total_points_and_fees']
)


# --------------------------------------------------------------
# 2. Numeric analysis value
# --------------------------------------------------------------

df['total_points_and_fees_analysis_value'] = pd.to_numeric(
    df['total_points_and_fees'],
    errors='coerce'
)


# --------------------------------------------------------------
# 3. Points & fees as percentage of loan amount
# --------------------------------------------------------------

df['points_fees_ratio'] = (
    df['total_points_and_fees_analysis_value']
    / df['loan_amount'] * 100
)


# --------------------------------------------------------------
# 4. Flags
# --------------------------------------------------------------

df['points_fees_high_ratio_flag'] = (
    df['points_fees_ratio'] > 5
)

df['points_fees_extreme_ratio_flag'] = (
    df['points_fees_ratio'] > 10
)

df['points_fees_high_absolute_flag'] = (
    df['total_points_and_fees_analysis_value'] > 50_000
)


# --------------------------------------------------------------
# 5. Quality category
# --------------------------------------------------------------

df['total_points_and_fees_quality_category'] = (
    'Valid / Usable'
)

df.loc[
    df['total_points_and_fees'].isna(),
    'total_points_and_fees_quality_category'
] = 'Missing'

df.loc[
    df['total_points_and_fees']
    .astype(str)
    .str.strip()
    .eq('Exempt'),
    'total_points_and_fees_quality_category'
] = 'Exempt'

df.loc[
    df['points_fees_high_ratio_flag'],
    'total_points_and_fees_quality_category'
] = 'High Ratio - Retained'


# --------------------------------------------------------------
# 6. Verification
# --------------------------------------------------------------

print("\nTOTAL POINTS AND FEES QUALITY CATEGORY")
print("-" * 70)

print(
    df['total_points_and_fees_quality_category']
    .value_counts(dropna=False)
)


print("\nHIGH RATIO FLAG (>5%)")
print("-" * 70)

print(
    df['points_fees_high_ratio_flag']
    .value_counts()
)


print("\nEXTREME RATIO FLAG (>10%)")
print("-" * 70)

print(
    df['points_fees_extreme_ratio_flag']
    .value_counts()
)


print("\nHIGH ABSOLUTE VALUE FLAG (> $50,000)")
print("-" * 70)

print(
    df['points_fees_high_absolute_flag']
    .value_counts()
)


print("\nFINAL ANALYSIS SUMMARY")
print("-" * 70)

print(
    df['total_points_and_fees_analysis_value']
    .describe()
)


print("\nFINAL TOTAL POINTS AND FEES SUMMARY")
print("-" * 70)

print("Total records:", len(df))

print(
    "Missing:",
    df['total_points_and_fees'].isna().sum()
)

print(
    "Exempt:",
    df['total_points_and_fees']
    .astype(str)
    .str.strip()
    .eq('Exempt')
    .sum()
)

print(
    "Numeric analysis values:",
    df['total_points_and_fees_analysis_value']
    .notna()
    .sum()
)

print(
    "Zero values:",
    (
        df['total_points_and_fees_analysis_value'] == 0
    ).sum()
)

print(
    "Negative values:",
    (
        df['total_points_and_fees_analysis_value'] < 0
    ).sum()
)

print(
    "High ratio >5%:",
    df['points_fees_high_ratio_flag'].sum()
)

print(
    "Extreme ratio >10%:",
    df['points_fees_extreme_ratio_flag'].sum()
)

print(
    "High absolute >$50,000:",
    df['points_fees_high_absolute_flag'].sum()
)


print("\nORIGINAL VALUE PRESERVATION CHECK")
print("-" * 70)

print(
    df[
        [
            'total_points_and_fees_original',
            'total_points_and_fees_analysis_value',
            'points_fees_ratio',
            'points_fees_high_ratio_flag',
            'points_fees_extreme_ratio_flag',
            'total_points_and_fees_quality_category'
        ]
    ]
    .head(15)
)

======================================================================
FINAL TOTAL POINTS AND FEES DATA QUALITY TREATMENT
======================================================================

TOTAL POINTS AND FEES QUALITY CATEGORY
----------------------------------------------------------------------
total_points_and_fees_quality_category
Missing                  678770
Exempt                    16611
Valid / Usable            13566
High Ratio - Retained       172
Name: count, dtype: int64

HIGH RATIO FLAG (>5%)
----------------------------------------------------------------------
points_fees_high_ratio_flag
False    708947
True        172
Name: count, dtype: int64

EXTREME RATIO FLAG (>10%)
----------------------------------------------------------------------
points_fees_extreme_ratio_flag
False    709115
True          4
Name: count, dtype: int64

HIGH ABSOLUTE VALUE FLAG (> $50,000)
----------------------------------------------------------------------
points_fees_high_absolute_flag
False    709116
True          3
Name: count, dtype: int64

FINAL ANALYSIS SUMMARY
----------------------------------------------------------------------
count    13738.000000
mean      2719.769854
std       2769.410547
min          0.000000
25%        499.000000
50%       2731.190000
75%       3914.000000
max      74403.060000
Name: total_points_and_fees_analysis_value, dtype: float64

FINAL TOTAL POINTS AND FEES SUMMARY
----------------------------------------------------------------------
Total records: 709119
Missing: 678770
Exempt: 16611
Numeric analysis values: 13738
Zero values: 3159
Negative values: 0
High ratio >5%: 172
Extreme ratio >10%: 4
High absolute >$50,000: 3

ORIGINAL VALUE PRESERVATION CHECK
----------------------------------------------------------------------
   total_points_and_fees_original  total_points_and_fees_analysis_value  \
0                             NaN                                   NaN
1                             NaN                                   NaN
2                             NaN                                   NaN
3                             NaN                                   NaN
4                             NaN                                   NaN
5                             NaN                                   NaN
6                             NaN                                   NaN
7                             NaN                                   NaN
8                             NaN                                   NaN
9                             NaN                                   NaN
10                            NaN                                   NaN
11                            NaN                                   NaN
12                            NaN                                   NaN
13                            NaN                                   NaN
14                            NaN                                   NaN

    points_fees_ratio  points_fees_high_ratio_flag  \
0                 NaN                        False
1                 NaN                        False
2                 NaN                        False
3                 NaN                        False
4                 NaN                        False
5                 NaN                        False
6                 NaN                        False
7                 NaN                        False
8                 NaN                        False
9                 NaN                        False
10                NaN                        False
11                NaN                        False
12                NaN                        False
13                NaN                        False
14                NaN                        False

    points_fees_extreme_ratio_flag total_points_and_fees_quality_category
0                            False                                Missing
1                            False                                Missing
2                            False                                Missing
3                            False                                Missing
4                            False                                Missing
5                            False                                Missing
6                            False                                Missing
7                            False                                Missing
8                            False                                Missing
9                            False                                Missing
10                           False                                Missing
11                           False                                Missing
12                           False                                Missing
13                           False                                Missing
14                           False                                Missing

In [77]:
# ================================================================
# FINAL REMAINING DATA QUALITY INVESTIGATION
# ================================================================

import pandas as pd
import numpy as np

print("=" * 80)
print("FINAL REMAINING DATA QUALITY INVESTIGATION")
print("=" * 80)


# ----------------------------------------------------------------
# 1. ORIGINATION CHARGES
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("1. ORIGINATION CHARGES")
print("=" * 80)

orig = pd.to_numeric(df['origination_charges'], errors='coerce')

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['origination_charges'].isna().sum())
print("Exempt:", df['origination_charges'].astype(str).str.strip().eq('Exempt').sum())
print("Numeric:", orig.notna().sum())
print("Negative:", (orig < 0).sum())
print("Zero:", (orig == 0).sum())

print("\nNumeric Description")
print("-" * 80)
print(orig.describe())

orig_ratio = orig / df['loan_amount'] * 100

print("\nOrigination Charges / Loan Amount (%)")
print("-" * 80)
print(orig_ratio.describe())

print("\nHigh Ratio Checks")
print("-" * 80)
print(">5% :", (orig_ratio > 5).sum())
print(">10%:", (orig_ratio > 10).sum())
print(">25%:", (orig_ratio > 25).sum())
print(">50%:", (orig_ratio > 50).sum())
print(">100%:", (orig_ratio > 100).sum())

print("\nHigh Absolute Values")
print("-" * 80)
print(">$50,000 :", (orig > 50_000).sum())
print(">$100,000:", (orig > 100_000).sum())

print("\nTop 10 Origination Charges")
print("-" * 80)
print(
    df.loc[orig.nlargest(10).index,
           ['origination_charges', 'loan_amount',
            'property_value_clean', 'derived_loan_product_type',
            'derived_dwelling_category', 'action_taken']]
)


# ----------------------------------------------------------------
# 2. DISCOUNT POINTS
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("2. DISCOUNT POINTS")
print("=" * 80)

discount = pd.to_numeric(df['discount_points'], errors='coerce')

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['discount_points'].isna().sum())
print("Exempt:", df['discount_points'].astype(str).str.strip().eq('Exempt').sum())
print("Numeric:", discount.notna().sum())
print("Negative:", (discount < 0).sum())
print("Zero:", (discount == 0).sum())

print("\nNumeric Description")
print("-" * 80)
print(discount.describe())

discount_ratio = discount / df['loan_amount'] * 100

print("\nDiscount Points / Loan Amount (%)")
print("-" * 80)
print(discount_ratio.describe())

print("\nHigh Ratio Checks")
print("-" * 80)
print(">5% :", (discount_ratio > 5).sum())
print(">10%:", (discount_ratio > 10).sum())
print(">25%:", (discount_ratio > 25).sum())
print(">50%:", (discount_ratio > 50).sum())

print("\nHigh Absolute Values")
print("-" * 80)
print(">$25,000:", (discount > 25_000).sum())
print(">$50,000:", (discount > 50_000).sum())

print("\nTop 10 Discount Points")
print("-" * 80)
print(
    df.loc[discount.nlargest(10).index,
           ['discount_points', 'loan_amount',
            'property_value_clean', 'derived_loan_product_type',
            'action_taken']]
)


# ----------------------------------------------------------------
# 3. LENDER CREDITS
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("3. LENDER CREDITS")
print("=" * 80)

credits = pd.to_numeric(df['lender_credits'], errors='coerce')

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['lender_credits'].isna().sum())
print("Exempt:", df['lender_credits'].astype(str).str.strip().eq('Exempt').sum())
print("Numeric:", credits.notna().sum())
print("Negative:", (credits < 0).sum())
print("Zero:", (credits == 0).sum())

print("\nNumeric Description")
print("-" * 80)
print(credits.describe())

credits_ratio = credits / df['loan_amount'] * 100

print("\nLender Credits / Loan Amount (%)")
print("-" * 80)
print(credits_ratio.describe())

print("\nAbsolute Value Checks")
print("-" * 80)
print("Abs >$25,000:", (credits.abs() > 25_000).sum())
print("Abs >$50,000:", (credits.abs() > 50_000).sum())
print("Abs >$100,000:", (credits.abs() > 100_000).sum())

print("\nTop 10 Absolute Lender Credits")
print("-" * 80)

top_credit_idx = credits.abs().nlargest(10).index

print(
    df.loc[top_credit_idx,
           ['lender_credits', 'loan_amount',
            'property_value_clean',
            'derived_loan_product_type',
            'action_taken']]
)


# ----------------------------------------------------------------
# 4. PREPAYMENT PENALTY TERM
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("4. PREPAYMENT PENALTY TERM")
print("=" * 80)

ppt = pd.to_numeric(df['prepayment_penalty_term'], errors='coerce')

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['prepayment_penalty_term'].isna().sum())
print("Exempt:", df['prepayment_penalty_term'].astype(str).str.strip().eq('Exempt').sum())
print("Numeric:", ppt.notna().sum())
print("Negative:", (ppt < 0).sum())
print("Zero:", (ppt == 0).sum())

print("\nNumeric Description")
print("-" * 80)
print(ppt.describe())

print("\nValues > 60 months:", (ppt > 60).sum())
print("Values > 120 months:", (ppt > 120).sum())
print("Values > 240 months:", (ppt > 240).sum())

print("\nMost Common Numeric Values")
print("-" * 80)
print(ppt.value_counts().head(20))


# ----------------------------------------------------------------
# 5. INTRO RATE PERIOD
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("5. INTRO RATE PERIOD")
print("=" * 80)

intro = pd.to_numeric(df['intro_rate_period'], errors='coerce')

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['intro_rate_period'].isna().sum())
print("Exempt:", df['intro_rate_period'].astype(str).str.strip().eq('Exempt').sum())
print("Numeric:", intro.notna().sum())
print("Negative:", (intro < 0).sum())
print("Zero:", (intro == 0).sum())

print("\nNumeric Description")
print("-" * 80)
print(intro.describe())

print("\nValues > 60 months:", (intro > 60).sum())
print("Values > 120 months:", (intro > 120).sum())
print("Values > 240 months:", (intro > 240).sum())
print("Values > 360 months:", (intro > 360).sum())

print("\nMost Common Numeric Values")
print("-" * 80)
print(intro.value_counts().head(20))


# ----------------------------------------------------------------
# 6. MULTIFAMILY AFFORDABLE UNITS
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("6. MULTIFAMILY AFFORDABLE UNITS")
print("=" * 80)

affordable = pd.to_numeric(
    df['multifamily_affordable_units'],
    errors='coerce'
)

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['multifamily_affordable_units'].isna().sum())
print("Exempt:", df['multifamily_affordable_units']
      .astype(str).str.strip().eq('Exempt').sum())
print("Numeric:", affordable.notna().sum())
print("Negative:", (affordable < 0).sum())
print("Zero:", (affordable == 0).sum())

print("\nNumeric Description")
print("-" * 80)
print(affordable.describe())

print("\nTop 20 Values")
print("-" * 80)
print(affordable.value_counts().head(20))


# ----------------------------------------------------------------
# 7. INCOME FINAL INVESTIGATION
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("7. INCOME")
print("=" * 80)

income = pd.to_numeric(df['income'], errors='coerce')

print("\nBasic Summary")
print("-" * 80)
print("Missing:", df['income'].isna().sum())
print("Numeric:", income.notna().sum())
print("Negative:", (income < 0).sum())
print("Zero:", (income == 0).sum())

print("\nIncome Description")
print("-" * 80)
print(income.describe())

print("\nNegative Income by Action")
print("-" * 80)
print(
    df.loc[income < 0, 'action_taken']
      .value_counts()
      .sort_index()
)

print("\nNegative Income by Loan Product")
print("-" * 80)
print(
    df.loc[income < 0, 'derived_loan_product_type']
      .value_counts()
)

print("\nExtreme Income")
print("-" * 80)
print("> $500,000:", (income > 500_000).sum())
print("> $1,000,000:", (income > 1_000_000).sum())

print("\nLowest 10 Income Values")
print("-" * 80)
print(income.nsmallest(10))

print("\nHighest 10 Income Values")
print("-" * 80)
print(income.nlargest(10))


# ----------------------------------------------------------------
# 8. APPLICANT / CO-APPLICANT AGE
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("8. APPLICANT / CO-APPLICANT AGE")
print("=" * 80)

app_age = pd.to_numeric(df['applicant_age'], errors='coerce')
co_age = pd.to_numeric(df['co-applicant_age'], errors='coerce')

print("\nApplicant Age")
print("-" * 80)
print("Missing:", df['applicant_age'].isna().sum())
print("Numeric:", app_age.notna().sum())
print("8888:", (app_age == 8888).sum())
print("9999:", (app_age == 9999).sum())
print("Below 18:", (app_age < 18).sum())
print("Above 100:", (app_age > 100).sum())
print(app_age.describe())

print("\nCo-Applicant Age")
print("-" * 80)
print("Missing:", df['co-applicant_age'].isna().sum())
print("Numeric:", co_age.notna().sum())
print("8888:", (co_age == 8888).sum())
print("9999:", (co_age == 9999).sum())
print("Below 18:", (co_age < 18).sum())
print("Above 100:", (co_age > 100).sum())
print(co_age.describe())


# ----------------------------------------------------------------
# 9. SPECIAL VALUE AUDIT
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("9. SPECIAL VALUE AUDIT")
print("=" * 80)

special_columns = [
    'property_value',
    'loan_to_value_ratio',
    'interest_rate',
    'rate_spread',
    'total_loan_costs',
    'total_points_and_fees',
    'origination_charges',
    'discount_points',
    'lender_credits',
    'loan_term',
    'prepayment_penalty_term',
    'intro_rate_period',
    'multifamily_affordable_units',
    'income',
    'debt_to_income_ratio',
    'applicant_age',
    'co-applicant_age'
]

special_summary = []

for col in special_columns:

    s = df[col].astype(str).str.strip()

    special_summary.append({
        'column': col,
        'Missing': df[col].isna().sum(),
        'Exempt': s.eq('Exempt').sum(),
        '8888': s.eq('8888').sum(),
        '9999': s.eq('9999').sum(),
        'Unique': df[col].nunique(dropna=True)
    })

special_summary_df = pd.DataFrame(special_summary)

print(special_summary_df.to_string(index=False))


# ----------------------------------------------------------------
# 10. DUPLICATE INVESTIGATION
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("10. DUPLICATE INVESTIGATION")
print("=" * 80)

duplicate_count = df.duplicated().sum()

print("Duplicate rows excluding first occurrence:", duplicate_count)

duplicate_groups = (
    df[df.duplicated(keep=False)]
    .value_counts()
    .value_counts()
    .sort_index()
)

print("\nDuplicate Group Size Distribution")
print("-" * 80)
print(duplicate_groups)


# ----------------------------------------------------------------
# 11. OVERALL MISSINGNESS
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("11. OVERALL MISSINGNESS")
print("=" * 80)

missing_summary = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

missing_percentage = (
    df.isna()
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

overall_missing = pd.DataFrame({
    'Missing_Count': missing_summary,
    'Missing_Percentage': missing_percentage
})

print(overall_missing.to_string())


# ----------------------------------------------------------------
# FINAL SUMMARY
# ----------------------------------------------------------------

print("\n" + "=" * 80)
print("FINAL INVESTIGATION COMPLETE")
print("=" * 80)

print("\nDataset Shape:", df.shape)

print("\nKey Fields Investigated:")
print("""
1. Origination Charges
2. Discount Points
3. Lender Credits
4. Prepayment Penalty Term
5. Intro Rate Period
6. Multifamily Affordable Units
7. Income
8. Applicant Age
9. Co-Applicant Age
10. Special Values
11. Duplicates
12. Overall Missingness
""")

print("=" * 80)

================================================================================
FINAL REMAINING DATA QUALITY INVESTIGATION
================================================================================

================================================================================
1. ORIGINATION CHARGES
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 284436
Exempt: 16663
Numeric: 408020
Negative: 0
Zero: 83643

Numeric Description
--------------------------------------------------------------------------------
count    408020.000000
mean       3400.027448
std        4225.846553
min           0.000000
25%         529.475000
50%        2074.000000
75%        5000.000000
max      690995.000000
Name: origination_charges, dtype: float64

Origination Charges / Loan Amount (%)
--------------------------------------------------------------------------------
count    408020.000000
mean          1.134057
std           1.188861
min           0.000000
25%           0.178626
50%           0.825641
75%           1.794549
max         107.804000
dtype: float64

High Ratio Checks
--------------------------------------------------------------------------------
>5% : 1443
>10%: 21
>25%: 14
>50%: 7
>100%: 2

High Absolute Values
--------------------------------------------------------------------------------
>$50,000 : 68
>$100,000: 8

Top 10 Origination Charges
--------------------------------------------------------------------------------
       origination_charges  loan_amount  property_value_clean  \
484585              690995     685000.0              865000.0
484587              574756     575000.0              605000.0
484530              452081     455000.0              455000.0
484596              294979     295000.0              295000.0
88246             139117.0    4555000.0             6505000.0
211884           135063.56    1705000.0             2135000.0
352901            125140.0    3005000.0             5255000.0
699570            101445.0    3945000.0             8805000.0
459326               99450    6635000.0             7805000.0
349552             85213.0    2405000.0             3005000.0

       derived_loan_product_type             derived_dwelling_category  \
484585   Conventional:First Lien  Single Family (1-4 Units):Site-Built
484587            FHA:First Lien  Single Family (1-4 Units):Site-Built
484530            FHA:First Lien  Single Family (1-4 Units):Site-Built
484596            FHA:First Lien  Single Family (1-4 Units):Site-Built
88246    Conventional:First Lien  Single Family (1-4 Units):Site-Built
211884   Conventional:First Lien  Single Family (1-4 Units):Site-Built
352901   Conventional:First Lien  Single Family (1-4 Units):Site-Built
699570   Conventional:First Lien  Single Family (1-4 Units):Site-Built
459326   Conventional:First Lien  Single Family (1-4 Units):Site-Built
349552   Conventional:First Lien  Single Family (1-4 Units):Site-Built

        action_taken
484585             1
484587             1
484530             1
484596             1
88246              1
211884             1
352901             1
699570             1
459326             1
349552             1

================================================================================
2. DISCOUNT POINTS
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 449143
Exempt: 16663
Numeric: 243313
Negative: 0
Zero: 0

Numeric Description
--------------------------------------------------------------------------------
count    243313.000000
mean       4743.267218
std        4963.966018
min           0.010000
25%        1649.000000
50%        3510.360000
75%        6450.000000
max      689600.000000
Name: discount_points, dtype: float64

Discount Points / Loan Amount (%)
--------------------------------------------------------------------------------
count    243313.000000
mean          1.507325
std           1.278821
min           0.000002
25%           0.615574
50%           1.209776
75%           2.093063
max         100.671533
dtype: float64

High Ratio Checks
--------------------------------------------------------------------------------
>5% : 4006
>10%: 58
>25%: 4
>50%: 4

High Absolute Values
--------------------------------------------------------------------------------
>$25,000: 1119
>$50,000: 42

Top 10 Discount Points
--------------------------------------------------------------------------------
       discount_points  loan_amount  property_value_clean  \
484585          689600     685000.0              865000.0
484587          573361     575000.0              605000.0
484530          450686     455000.0              455000.0
484596          293584     295000.0              295000.0
88246         136605.0    4555000.0             6505000.0
211884       133868.56    1705000.0             2135000.0
352901        123750.0    3005000.0             5255000.0
20664            95077    1555000.0             2305000.0
349552         83568.0    2405000.0             3005000.0
658549           77616    2245000.0             2805000.0

       derived_loan_product_type  action_taken
484585   Conventional:First Lien             1
484587            FHA:First Lien             1
484530            FHA:First Lien             1
484596            FHA:First Lien             1
88246    Conventional:First Lien             1
211884   Conventional:First Lien             1
352901   Conventional:First Lien             1
20664    Conventional:First Lien             1
349552   Conventional:First Lien             1
658549   Conventional:First Lien             1

================================================================================
3. LENDER CREDITS
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 558204
Exempt: 16663
Numeric: 134252
Negative: 0
Zero: 0

Numeric Description
--------------------------------------------------------------------------------
count    134252.000000
mean       1357.669976
std        2223.541056
min           0.010000
25%          55.000000
50%         329.840000
75%        1866.162500
max       60000.000000
Name: lender_credits, dtype: float64

Lender Credits / Loan Amount (%)
--------------------------------------------------------------------------------
count    134252.000000
mean          0.410464
std           0.686411
min           0.000001
25%           0.019149
50%           0.124373
75%           0.587539
max          76.000000
dtype: float64

Absolute Value Checks
--------------------------------------------------------------------------------
Abs >$25,000: 36
Abs >$50,000: 3
Abs >$100,000: 0

Top 10 Absolute Lender Credits
--------------------------------------------------------------------------------
       lender_credits  loan_amount  property_value_clean  \
8760          60000.0    2005000.0             3505000.0
163766       55382.34    2765000.0             5035000.0
8761          55000.0    2005000.0             3115000.0
508940        49183.9    2455000.0             3275000.0
349436       46469.63    3115000.0             4155000.0
179661       45661.34    1545000.0             2205000.0
400722          41172     485000.0              645000.0
234047       40820.61     515000.0              635000.0
303619          38750    4005000.0             5005000.0
686840       38747.33    1775000.0             2635000.0

       derived_loan_product_type  action_taken
8760     Conventional:First Lien             1
163766   Conventional:First Lien             1
8761     Conventional:First Lien             1
508940   Conventional:First Lien             1
349436   Conventional:First Lien             1
179661   Conventional:First Lien             1
400722   Conventional:First Lien             1
234047   Conventional:First Lien             1
303619   Conventional:First Lien             1
686840   Conventional:First Lien             1

================================================================================
4. PREPAYMENT PENALTY TERM
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 691354
Exempt: 16669
Numeric: 1096
Negative: 0
Zero: 78

Numeric Description
--------------------------------------------------------------------------------
count    1096.000000
mean       27.145073
std        44.358501
min         0.000000
25%         2.000000
50%        12.000000
75%        36.000000
max       360.000000
Name: prepayment_penalty_term, dtype: float64

Values > 60 months: 18
Values > 120 months: 17
Values > 240 months: 15

Most Common Numeric Values
--------------------------------------------------------------------------------
prepayment_penalty_term
36.0     291
12.0     251
2.0      226
60.0     120
24.0      94
0.0       78
360.0     15
48.0       9
1.0        7
6.0        2
84.0       1
180.0      1
240.0      1
Name: count, dtype: int64

================================================================================
5. INTRO RATE PERIOD
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 617913
Exempt: 16669
Numeric: 74537
Negative: 0
Zero: 0

Numeric Description
--------------------------------------------------------------------------------
count    74537.000000
mean        21.954050
std         42.532452
min          1.000000
25%          1.000000
50%          1.000000
75%         12.000000
max        360.000000
Name: intro_rate_period, dtype: float64

Values > 60 months: 9058
Values > 120 months: 1289
Values > 240 months: 357
Values > 360 months: 0

Most Common Numeric Values
--------------------------------------------------------------------------------
intro_rate_period
1.0      40121
12.0      7612
60.0      6410
6.0       5237
84.0      4427
3.0       2588
120.0     2077
36.0      1651
2.0       1329
180.0      845
72.0       434
360.0      357
78.0       183
24.0       119
66.0       118
96.0       102
61.0        87
63.0        83
73.0        83
11.0        71
Name: count, dtype: int64

================================================================================
6. MULTIFAMILY AFFORDABLE UNITS
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 691161
Exempt: 16667
Numeric: 1291
Negative: 0
Zero: 1100

Numeric Description
--------------------------------------------------------------------------------
count    1291.000000
mean       12.745933
std        32.238124
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       100.000000
Name: multifamily_affordable_units, dtype: float64

Top 20 Values
--------------------------------------------------------------------------------
multifamily_affordable_units
0.0      1100
100.0     135
50.0       10
90.0        5
75.0        3
35.0        3
51.0        3
10.0        2
43.0        2
94.0        2
6.0         2
8.0         2
63.0        2
96.0        1
85.0        1
4.0         1
54.0        1
21.0        1
57.0        1
17.0        1
Name: count, dtype: int64

================================================================================
7. INCOME
================================================================================

Basic Summary
--------------------------------------------------------------------------------
Missing: 43023
Numeric: 666096
Negative: 648
Zero: 10367

Income Description
--------------------------------------------------------------------------------
count    6.660960e+05
mean     1.569396e+02
std      2.873329e+03
min     -1.020900e+04
25%      7.100000e+01
50%      1.090000e+02
75%      1.680000e+02
max      1.620000e+06
Name: income, dtype: float64

Negative Income by Action
--------------------------------------------------------------------------------
action_taken
1     22
2      6
3    620
Name: count, dtype: int64

Negative Income by Loan Product
--------------------------------------------------------------------------------
derived_loan_product_type
Conventional:First Lien          381
Conventional:Subordinate Lien    212
FHA:First Lien                    40
VA:First Lien                     15
Name: count, dtype: int64

Extreme Income
--------------------------------------------------------------------------------
> $500,000: 3
> $1,000,000: 2

Lowest 10 Income Values
--------------------------------------------------------------------------------
148001   -10209.0
28597     -4737.0
492063    -3937.0
492068    -3937.0
493386    -3834.0
635693    -2916.0
509943    -2655.0
633844    -2118.0
288496    -2052.0
81437     -1887.0
Name: income, dtype: float64

Highest 10 Income Values
--------------------------------------------------------------------------------
681602    1620000.0
681580    1316000.0
69317     1000000.0
501448     224000.0
67414      150000.0
642049     100408.0
414217      52000.0
445673      50000.0
460722      46080.0
22949       42741.0
Name: income, dtype: float64

================================================================================
8. APPLICANT / CO-APPLICANT AGE
================================================================================

Applicant Age
--------------------------------------------------------------------------------
Missing: 0
Numeric: 15375
8888: 15375
9999: 0
Below 18: 0
Above 100: 15375
count    15375.0
mean      8888.0
std          0.0
min       8888.0
25%       8888.0
50%       8888.0
75%       8888.0
max       8888.0
Name: applicant_age, dtype: float64

Co-Applicant Age
--------------------------------------------------------------------------------
Missing: 0
Numeric: 411521
8888: 5049
9999: 406472
Below 18: 0
Above 100: 411521
count    411521.000000
mean       9985.369009
std         122.303979
min        8888.000000
25%        9999.000000
50%        9999.000000
75%        9999.000000
max        9999.000000
Name: co-applicant_age, dtype: float64

================================================================================
9. SPECIAL VALUE AUDIT
================================================================================
                      column  Missing  Exempt  8888   9999  Unique
              property_value    26961   16567     0      0    1715
         loan_to_value_ratio    81144   16571     0      0   99735
               interest_rate   182999   16669     0      0    4832
                 rate_spread   228301   16202     0      0   28377
            total_loan_costs   287622   16611     1      0  345740
       total_points_and_fees   678770   16611     0      0    5976
         origination_charges   284436   16663     0      0  187567
             discount_points   449143   16663     0      0  185584
              lender_credits   558204   16663     0      0   64654
                   loan_term    12447   16435     0      0     652
     prepayment_penalty_term   691354   16669     0      0      20
           intro_rate_period   617913   16669     0      0     114
multifamily_affordable_units   691161   16667     0      0      42
                      income    43023       0     0      0    3069
        debt_to_income_ratio    52698   16667     0      0      20
               applicant_age        0       0 15375      0       8
            co-applicant_age        0       0  5049 406472       9

================================================================================
10. DUPLICATE INVESTIGATION
================================================================================
Duplicate rows excluding first occurrence: 0

Duplicate Group Size Distribution
--------------------------------------------------------------------------------
Series([], Name: count, dtype: int64)

================================================================================
11. OVERALL MISSINGNESS
================================================================================
                                               Missing_Count  Missing_Percentage
co_applicant_age_analysis_value                       709119          100.000000
applicant_age_analysis_value                          709119          100.000000
co-applicant_ethnicity-5                              709116           99.999577
co-applicant_ethnicity-4                              709108           99.998449
applicant_ethnicity-5                                 709107           99.998308
applicant_ethnicity-4                                 709069           99.992949
co-applicant_race-5                                   709063           99.992103
applicant_race-5                                      708982           99.980680
co-applicant_race-4                                   708970           99.978988
applicant_race-4                                      708680           99.938092
co-applicant_ethnicity-3                              708525           99.916234
prepayment_penalty_term_clean                         708023           99.845442
prepayment_penalty_term_analysis_value                708023           99.845442
co-applicant_race-3                                   707992           99.841070
multifamily_affordable_units_clean                    707828           99.817943
multifamily_affordable_units_analysis_value           707828           99.817943
applicant_ethnicity-3                                 707413           99.759420
denial_reason-4                                       706750           99.665923
applicant_race-3                                      705871           99.541967
aus-5                                                 703347           99.186032
aus-4                                                 702640           99.086331
denial_reason-3                                       700349           98.763254
points_fees_ratio                                     695381           98.062666
total_points_and_fees_analysis_value                  695381           98.062666
total_points_and_fees_clean                           695381           98.062666
aus-3                                                 693535           97.802343
prepayment_penalty_term                               691354           97.494779
prepayment_penalty_term_original                      691354           97.494779
multifamily_affordable_units_original                 691161           97.467562
multifamily_affordable_units                          691161           97.467562
co-applicant_race-2                                   688670           97.116281
total_points_and_fees                                 678770           95.720182
total_points_and_fees_original                        678770           95.720182
co-applicant_ethnicity-2                              668106           94.216345
denial_reason-2                                       664887           93.762401
aus-2                                                 657301           92.692623
applicant_race-2                                      654450           92.290575
intro_rate_period_clean                               634582           89.488788
intro_rate_period_analysis_value                      634582           89.488788
intro_rate_period_original                            617913           87.138125
intro_rate_period                                     617913           87.138125
applicant_ethnicity-2                                 605549           85.394553
lender_credits_analysis_value                         574867           81.067776

In [78]:
# ================================================================
# FINAL REMAINING DATA QUALITY TREATMENT
# ================================================================

print("=" * 80)
print("FINAL REMAINING DATA QUALITY TREATMENT")
print("=" * 80)


# ================================================================
# 1. ORIGINATION CHARGES
# ================================================================

df['origination_charges_original'] = df['origination_charges']

df['origination_charges_analysis_value'] = pd.to_numeric(
    df['origination_charges'],
    errors='coerce'
)

df['origination_charges_ratio'] = (
    df['origination_charges_analysis_value']
    / df['loan_amount'] * 100
)

df['origination_charges_high_ratio_flag'] = (
    df['origination_charges_ratio'] > 5
)

df['origination_charges_extreme_ratio_flag'] = (
    df['origination_charges_ratio'] > 10
)

df['origination_charges_high_absolute_flag'] = (
    df['origination_charges_analysis_value'] > 50_000
)

df['origination_charges_quality_category'] = 'Valid / Usable'

df.loc[
    df['origination_charges'].isna(),
    'origination_charges_quality_category'
] = 'Missing'

df.loc[
    df['origination_charges'].astype(str).str.strip().eq('Exempt'),
    'origination_charges_quality_category'
] = 'Exempt'

df.loc[
    df['origination_charges_high_ratio_flag'],
    'origination_charges_quality_category'
] = 'High Ratio - Retained'


# ================================================================
# 2. DISCOUNT POINTS
# ================================================================

df['discount_points_original'] = df['discount_points']

df['discount_points_analysis_value'] = pd.to_numeric(
    df['discount_points'],
    errors='coerce'
)

df['discount_points_ratio'] = (
    df['discount_points_analysis_value']
    / df['loan_amount'] * 100
)

df['discount_points_high_ratio_flag'] = (
    df['discount_points_ratio'] > 5
)

df['discount_points_extreme_ratio_flag'] = (
    df['discount_points_ratio'] > 10
)

df['discount_points_high_absolute_flag'] = (
    df['discount_points_analysis_value'] > 50_000
)

df['discount_points_quality_category'] = 'Valid / Usable'

df.loc[
    df['discount_points'].isna(),
    'discount_points_quality_category'
] = 'Missing'

df.loc[
    df['discount_points'].astype(str).str.strip().eq('Exempt'),
    'discount_points_quality_category'
] = 'Exempt'

df.loc[
    df['discount_points_high_ratio_flag'],
    'discount_points_quality_category'
] = 'High Ratio - Retained'


# ================================================================
# 3. LENDER CREDITS
# ================================================================

df['lender_credits_original'] = df['lender_credits']

df['lender_credits_analysis_value'] = pd.to_numeric(
    df['lender_credits'],
    errors='coerce'
)

df['lender_credits_ratio'] = (
    df['lender_credits_analysis_value']
    / df['loan_amount'] * 100
)

df['lender_credits_high_ratio_flag'] = (
    df['lender_credits_ratio'] > 5
)

df['lender_credits_high_absolute_flag'] = (
    df['lender_credits_analysis_value'] > 25_000
)

df['lender_credits_quality_category'] = 'Valid / Usable'

df.loc[
    df['lender_credits'].isna(),
    'lender_credits_quality_category'
] = 'Missing'

df.loc[
    df['lender_credits'].astype(str).str.strip().eq('Exempt'),
    'lender_credits_quality_category'
] = 'Exempt'

df.loc[
    df['lender_credits_high_ratio_flag'],
    'lender_credits_quality_category'
] = 'High Ratio - Retained'


# ================================================================
# 4. PREPAYMENT PENALTY TERM
# ================================================================

df['prepayment_penalty_term_original'] = (
    df['prepayment_penalty_term']
)

df['prepayment_penalty_term_analysis_value'] = pd.to_numeric(
    df['prepayment_penalty_term'],
    errors='coerce'
)

df['prepayment_penalty_term_flag'] = (
    df['prepayment_penalty_term_analysis_value'] > 60
)

df['prepayment_penalty_term_quality_category'] = 'Valid / Usable'

df.loc[
    df['prepayment_penalty_term'].isna(),
    'prepayment_penalty_term_quality_category'
] = 'Missing'

df.loc[
    df['prepayment_penalty_term'].astype(str).str.strip().eq('Exempt'),
    'prepayment_penalty_term_quality_category'
] = 'Exempt'

df.loc[
    df['prepayment_penalty_term_flag'],
    'prepayment_penalty_term_quality_category'
] = 'Long Term - Retained'


# ================================================================
# 5. INTRO RATE PERIOD
# ================================================================

df['intro_rate_period_original'] = df['intro_rate_period']

df['intro_rate_period_analysis_value'] = pd.to_numeric(
    df['intro_rate_period'],
    errors='coerce'
)

df['intro_rate_period_quality_category'] = 'Valid / Usable'

df.loc[
    df['intro_rate_period'].isna(),
    'intro_rate_period_quality_category'
] = 'Missing'

df.loc[
    df['intro_rate_period'].astype(str).str.strip().eq('Exempt'),
    'intro_rate_period_quality_category'
] = 'Exempt'


# ================================================================
# 6. MULTIFAMILY AFFORDABLE UNITS
# ================================================================

df['multifamily_affordable_units_original'] = (
    df['multifamily_affordable_units']
)

df['multifamily_affordable_units_analysis_value'] = pd.to_numeric(
    df['multifamily_affordable_units'],
    errors='coerce'
)

df['multifamily_affordable_units_quality_category'] = (
    'Valid / Usable'
)

df.loc[
    df['multifamily_affordable_units'].isna(),
    'multifamily_affordable_units_quality_category'
] = 'Missing'

df.loc[
    df['multifamily_affordable_units']
      .astype(str).str.strip().eq('Exempt'),
    'multifamily_affordable_units_quality_category'
] = 'Exempt'


# ================================================================
# 7. INCOME
# ================================================================

df['income_original'] = df['income']

df['income_analysis_value'] = pd.to_numeric(
    df['income'],
    errors='coerce'
)

df['negative_income_flag'] = df['income_analysis_value'] < 0

df['zero_income_flag'] = df['income_analysis_value'] == 0

df['extreme_income_flag'] = (
    df['income_analysis_value'] > 500_000
)

df['income_quality_category'] = 'Valid / Usable'

df.loc[
    df['income'].isna(),
    'income_quality_category'
] = 'Missing'

df.loc[
    df['negative_income_flag'],
    'income_quality_category'
] = 'Negative Income - Retained'

df.loc[
    df['extreme_income_flag'],
    'income_quality_category'
] = 'Extreme Value - Retained'


# ================================================================
# 8. APPLICANT AGE
# ================================================================

df['applicant_age_original'] = df['applicant_age']

df['applicant_age_analysis_value'] = pd.to_numeric(
    df['applicant_age'],
    errors='coerce'
)

# HMDA special code 8888 -> missing for analysis
df.loc[
    df['applicant_age_analysis_value'].isin([8888, 9999]),
    'applicant_age_analysis_value'
] = np.nan

df['applicant_age_quality_category'] = 'Valid / Usable'

df.loc[
    df['applicant_age'].astype(str).str.strip().eq('8888'),
    'applicant_age_quality_category'
] = 'Special Code - Excluded from Age Analysis'

df.loc[
    df['applicant_age'].isna(),
    'applicant_age_quality_category'
] = 'Missing'


# ================================================================
# 9. CO-APPLICANT AGE
# ================================================================

df['co_applicant_age_original'] = df['co-applicant_age']

df['co_applicant_age_analysis_value'] = pd.to_numeric(
    df['co-applicant_age'],
    errors='coerce'
)

# HMDA special codes 8888 / 9999 -> missing for analysis
df.loc[
    df['co_applicant_age_analysis_value'].isin([8888, 9999]),
    'co_applicant_age_analysis_value'
] = np.nan

df['co_applicant_age_quality_category'] = 'Valid / Usable'

df.loc[
    df['co-applicant_age'].astype(str).str.strip().isin(['8888', '9999']),
    'co_applicant_age_quality_category'
] = 'Special Code - Excluded from Age Analysis'

df.loc[
    df['co-applicant_age'].isna(),
    'co_applicant_age_quality_category'
] = 'Missing'


# ================================================================
# 10. REMOVE EXACT DUPLICATE ROWS
# ================================================================

duplicate_count_before = df.duplicated().sum()

print("\nDuplicate rows before removal:", duplicate_count_before)

df = df.drop_duplicates().copy()

duplicate_count_after = df.duplicated().sum()

print("Duplicate rows after removal:", duplicate_count_after)


# ================================================================
# 11. FINAL VERIFICATION
# ================================================================

print("\n" + "=" * 80)
print("FINAL TREATMENT VERIFICATION")
print("=" * 80)

print("\nFinal Dataset Shape:", df.shape)

print("\nRemaining Duplicates:", df.duplicated().sum())

print("\nNegative Income:")
print(df['negative_income_flag'].sum())

print("\nZero Income:")
print(df['zero_income_flag'].sum())

print("\nApplicant Age Special Codes:")
print(
    df['applicant_age']
      .astype(str).str.strip()
      .eq('8888')
      .sum()
)

print("\nCo-Applicant Age Special Codes:")
print(
    df['co-applicant_age']
      .astype(str).str.strip()
      .isin(['8888', '9999'])
      .sum()
)

print("\nNumeric Analysis Counts")
print("-" * 80)

analysis_columns = [
    'origination_charges_analysis_value',
    'discount_points_analysis_value',
    'lender_credits_analysis_value',
    'prepayment_penalty_term_analysis_value',
    'intro_rate_period_analysis_value',
    'multifamily_affordable_units_analysis_value',
    'income_analysis_value',
    'applicant_age_analysis_value',
    'co_applicant_age_analysis_value'
]

for col in analysis_columns:
    print(f"{col}: {df[col].notna().sum():,}")

print("\n" + "=" * 80)
print("FINAL REMAINING TREATMENT COMPLETE")
print("=" * 80)

================================================================================
FINAL REMAINING DATA QUALITY TREATMENT
================================================================================

Duplicate rows before removal: 0
Duplicate rows after removal: 0

================================================================================
FINAL TREATMENT VERIFICATION
================================================================================

Final Dataset Shape: (709119, 204)

Remaining Duplicates: 0

Negative Income:
648

Zero Income:
10367

Applicant Age Special Codes:
15375

Co-Applicant Age Special Codes:
411521

Numeric Analysis Counts
--------------------------------------------------------------------------------
origination_charges_analysis_value: 408,020
discount_points_analysis_value: 243,313
lender_credits_analysis_value: 134,252
prepayment_penalty_term_analysis_value: 1,096
intro_rate_period_analysis_value: 74,537
multifamily_affordable_units_analysis_value: 1,291
income_analysis_value: 666,096
applicant_age_analysis_value: 0
co_applicant_age_analysis_value: 0

================================================================================
FINAL REMAINING TREATMENT COMPLETE
================================================================================

In [79]:
# ================================================================
# FIX APPLICANT AND CO-APPLICANT AGE ANALYSIS COLUMNS
# ================================================================

# Convert age columns safely
applicant_age_numeric = pd.to_numeric(
    df['applicant_age'].astype(str).str.strip(),
    errors='coerce'
)

co_applicant_age_numeric = pd.to_numeric(
    df['co-applicant_age'].astype(str).str.strip(),
    errors='coerce'
)

# Preserve actual ages and remove HMDA special codes from analysis
df['applicant_age_analysis_value'] = applicant_age_numeric
df['applicant_age_analysis_value'] = df[
    'applicant_age_analysis_value'
].where(
    ~df['applicant_age_analysis_value'].isin([8888, 9999]),
    np.nan
)

df['co_applicant_age_analysis_value'] = co_applicant_age_numeric
df['co_applicant_age_analysis_value'] = df[
    'co_applicant_age_analysis_value'
].where(
    ~df['co_applicant_age_analysis_value'].isin([8888, 9999]),
    np.nan
)

# Quality categories
df['applicant_age_quality_category'] = 'Valid / Usable'

df.loc[
    df['applicant_age_analysis_value'].isna(),
    'applicant_age_quality_category'
] = 'Missing / Special Code'

df['co_applicant_age_quality_category'] = 'Valid / Usable'

df.loc[
    df['co_applicant_age_analysis_value'].isna(),
    'co_applicant_age_quality_category'
] = 'Missing / Special Code'


# ================================================================
# VERIFICATION
# ================================================================

print("=" * 70)
print("AGE ANALYSIS VERIFICATION")
print("=" * 70)

print("\nApplicant Age")
print("-" * 70)
print("Original non-null:", df['applicant_age'].notna().sum())
print("Usable ages:", df['applicant_age_analysis_value'].notna().sum())
print("Special/missing:", df['applicant_age_analysis_value'].isna().sum())
print(df['applicant_age_analysis_value'].describe())

print("\nCo-Applicant Age")
print("-" * 70)
print("Original non-null:", df['co-applicant_age'].notna().sum())
print("Usable ages:", df['co_applicant_age_analysis_value'].notna().sum())
print("Special/missing:", df['co_applicant_age_analysis_value'].isna().sum())
print(df['co_applicant_age_analysis_value'].describe())

print("\nFinal Dataset Shape:", df.shape)
print("Remaining duplicates:", df.duplicated().sum())

======================================================================
AGE ANALYSIS VERIFICATION
======================================================================

Applicant Age
----------------------------------------------------------------------
Original non-null: 709119
Usable ages: 0
Special/missing: 709119
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: applicant_age_analysis_value, dtype: float64

Co-Applicant Age
----------------------------------------------------------------------
Original non-null: 709119
Usable ages: 0
Special/missing: 709119
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: co_applicant_age_analysis_value, dtype: float64

Final Dataset Shape: (709119, 204)
Remaining duplicates: 0

In [80]:
print("Applicant Age dtype:", df['applicant_age'].dtype)
print("\nApplicant Age sample values:")
print(df['applicant_age'].value_counts(dropna=False).head(20))

print("\nCo-Applicant Age dtype:", df['co-applicant_age'].dtype)
print("\nCo-Applicant Age sample values:")
print(df['co-applicant_age'].value_counts(dropna=False).head(20))

Applicant Age dtype: str

Applicant Age sample values:
applicant_age
35-44    189537
25-34    168007
45-54    145968
55-64     94512
65-74     47764
<25       30610
>74       17346
8888      15375
Name: count, dtype: int64

Co-Applicant Age dtype: str

Co-Applicant Age sample values:
co-applicant_age
9999     406472
35-44     77959
25-34     77060
45-54     58671
55-64     40043
65-74     22082
<25       14671
>74        7112
8888       5049
Name: count, dtype: int64

In [81]:
# ================================================================
# CORRECT AGE TREATMENT — CATEGORICAL AGE GROUPS
# ================================================================

# Preserve original values
df['applicant_age_original'] = df['applicant_age']
df['co_applicant_age_original'] = df['co-applicant_age']

# Create analysis categories
df['applicant_age_analysis_category'] = (
    df['applicant_age'].astype(str).str.strip()
)

df['co_applicant_age_analysis_category'] = (
    df['co-applicant_age'].astype(str).str.strip()
)

# Treat HMDA special codes as missing for age-group analysis
df.loc[
    df['applicant_age_analysis_category'].isin(['8888', '9999']),
    'applicant_age_analysis_category'
] = np.nan

df.loc[
    df['co_applicant_age_analysis_category'].isin(['8888', '9999']),
    'co_applicant_age_analysis_category'
] = np.nan

# Quality categories
df['applicant_age_quality_category'] = 'Valid / Usable'
df.loc[
    df['applicant_age_analysis_category'].isna(),
    'applicant_age_quality_category'
] = 'Special Code / Missing'

df['co_applicant_age_quality_category'] = 'Valid / Usable'
df.loc[
    df['co_applicant_age_analysis_category'].isna(),
    'co_applicant_age_quality_category'
] = 'Special Code / Missing'


# ================================================================
# VERIFICATION
# ================================================================

print("=" * 70)
print("CORRECTED AGE VERIFICATION")
print("=" * 70)

print("\nApplicant Age Analysis Categories:")
print(
    df['applicant_age_analysis_category']
    .value_counts(dropna=False)
)

print("\nCo-Applicant Age Analysis Categories:")
print(
    df['co_applicant_age_analysis_category']
    .value_counts(dropna=False)
)

print("\nUsable Applicant Age Groups:",
      df['applicant_age_analysis_category'].notna().sum())

print("Usable Co-Applicant Age Groups:",
      df['co_applicant_age_analysis_category'].notna().sum())

print("\nFinal Dataset Shape:", df.shape)
print("Remaining Duplicates:", df.duplicated().sum())

======================================================================
CORRECTED AGE VERIFICATION
======================================================================

Applicant Age Analysis Categories:
applicant_age_analysis_category
35-44    189537
25-34    168007
45-54    145968
55-64     94512
65-74     47764
<25       30610
>74       17346
NaN       15375
Name: count, dtype: int64

Co-Applicant Age Analysis Categories:
co_applicant_age_analysis_category
NaN      411521
35-44     77959
25-34     77060
45-54     58671
55-64     40043
65-74     22082
<25       14671
>74        7112
Name: count, dtype: int64

Usable Applicant Age Groups: 693744
Usable Co-Applicant Age Groups: 297598

Final Dataset Shape: (709119, 204)
Remaining Duplicates: 0

In [82]:
# ================================================================
# FINAL DATA QUALITY AUDIT
# ================================================================

print("=" * 80)
print("FINAL DATA QUALITY AUDIT")
print("=" * 80)

# 1. Dataset structure
print("\n1. DATASET STRUCTURE")
print("-" * 80)
print("Rows:", f"{len(df):,}")
print("Columns:", df.shape[1])

# 2. Duplicate check
print("\n2. DUPLICATES")
print("-" * 80)
print("Duplicate rows:", df.duplicated().sum())

# 3. Missing values
print("\n3. MISSING VALUES")
print("-" * 80)
total_missing = df.isna().sum().sum()
total_cells = df.shape[0] * df.shape[1]
missing_pct = total_missing / total_cells * 100

print("Total missing cells:", f"{total_missing:,}")
print("Overall missing percentage:", f"{missing_pct:.2f}%")

# 4. Negative values in important numeric fields
print("\n4. IMPORTANT NUMERIC VALIDATION")
print("-" * 80)

checks = {
    'loan_amount_negative': (df['loan_amount_analysis_value'] < 0).sum(),
    'income_negative': (df['income_analysis_value'] < 0).sum(),
    'property_value_negative': (df['property_value_analysis_value'] < 0).sum(),
    'ltv_negative': (df['ltv_analysis_value'] < 0).sum(),
    'interest_rate_negative': (df['interest_rate_analysis_value'] < 0).sum(),
    'total_loan_costs_negative': (df['total_loan_costs_analysis_value'] < 0).sum(),
    'origination_charges_negative': (df['origination_charges_analysis_value'] < 0).sum(),
    'discount_points_negative': (df['discount_points_analysis_value'] < 0).sum(),
    'lender_credits_negative': (df['lender_credits_analysis_value'] < 0).sum()
}

for name, value in checks.items():
    print(f"{name}: {value:,}")

# 5. Important anomaly counts
print("\n5. ANOMALY FLAGS")
print("-" * 80)

anomaly_checks = {
    'property_value_anomaly': 'property_value_anomaly_flag',
    'extreme_ltv': 'extreme_ltv_flag',
    'ltv_consistency_anomaly': 'ltv_consistency_flag',
    'high_interest_rate': 'high_interest_rate_flag',
    'extreme_rate_spread': 'extreme_rate_spread_flag',
    'rate_spread_confirmed_anomaly': 'rate_spread_anomaly_flag',
    'extreme_loan_amount': 'extreme_loan_amount_flag',
    'negative_income': 'negative_income_flag',
    'zero_income': 'zero_income_flag',
    'high_origination_ratio': 'origination_charges_high_ratio_flag',
    'high_discount_points_ratio': 'discount_points_high_ratio_flag',
    'high_lender_credit_ratio': 'lender_credits_high_ratio_flag'
}

for name, column in anomaly_checks.items():
    print(f"{name}: {df[column].sum():,}")

# 6. Special values
print("\n6. SPECIAL VALUES")
print("-" * 80)

print(
    "Applicant age 8888:",
    df['applicant_age'].astype(str).str.strip().eq('8888').sum()
)

print(
    "Co-applicant age 8888:",
    df['co-applicant_age'].astype(str).str.strip().eq('8888').sum()
)

print(
    "Co-applicant age 9999:",
    df['co-applicant_age'].astype(str).str.strip().eq('9999').sum()
)

# 7. Key categorical columns
print("\n7. KEY CATEGORICAL COLUMNS")
print("-" * 80)

for column in [
    'action_taken',
    'derived_loan_product_type',
    'loan_purpose',
    'lien_status',
    'occupancy_type',
    'derived_dwelling_category'
]:
    print(f"\n{column}:")
    print(df[column].value_counts(dropna=False).head(10))

# 8. Final verification
print("\n" + "=" * 80)
print("FINAL AUDIT RESULT")
print("=" * 80)

print("Rows:", f"{len(df):,}")
print("Columns:", df.shape[1])
print("Duplicates:", df.duplicated().sum())

print("\nDATA QUALITY AUDIT COMPLETE")

================================================================================
FINAL DATA QUALITY AUDIT
================================================================================

1. DATASET STRUCTURE
--------------------------------------------------------------------------------
Rows: 709,119
Columns: 204

2. DUPLICATES
--------------------------------------------------------------------------------
Duplicate rows: 0

3. MISSING VALUES
--------------------------------------------------------------------------------
Total missing cells: 41,357,288
Overall missing percentage: 28.59%

4. IMPORTANT NUMERIC VALIDATION
--------------------------------------------------------------------------------
loan_amount_negative: 0
income_negative: 648
property_value_negative: 0
ltv_negative: 0
interest_rate_negative: 0
total_loan_costs_negative: 0
origination_charges_negative: 0
discount_points_negative: 0
lender_credits_negative: 0

5. ANOMALY FLAGS
--------------------------------------------------------------------------------
property_value_anomaly: 11
extreme_ltv: 188
ltv_consistency_anomaly: 1,101
high_interest_rate: 84
extreme_rate_spread: 34
rate_spread_confirmed_anomaly: 1
extreme_loan_amount: 593
negative_income: 648
zero_income: 10,367
high_origination_ratio: 1,443
high_discount_points_ratio: 4,006
high_lender_credit_ratio: 181

6. SPECIAL VALUES
--------------------------------------------------------------------------------
Applicant age 8888: 15375
Co-applicant age 8888: 5049
Co-applicant age 9999: 406472

7. KEY CATEGORICAL COLUMNS
--------------------------------------------------------------------------------

action_taken:
action_taken
1    494053
3    184047
2     31019
Name: count, dtype: int64

derived_loan_product_type:
derived_loan_product_type
Conventional:First Lien          426272
FHA:First Lien                   117703
Conventional:Subordinate Lien    100897
VA:First Lien                     61491
FSA/RHS:First Lien                 1835
FSA/RHS:Subordinate Lien            886
FHA:Subordinate Lien                 35
Name: count, dtype: int64

loan_purpose:
loan_purpose
1     464122
32     78903
31     62782
4      60171
2      42810
5        331
Name: count, dtype: int64

lien_status:
lien_status
1    607301
2    101818
Name: count, dtype: int64

occupancy_type:
occupancy_type
1    639680
3     60920
2      8519
Name: count, dtype: int64

derived_dwelling_category:
derived_dwelling_category
Single Family (1-4 Units):Site-Built      636597
Single Family (1-4 Units):Manufactured     70548
Multifamily:Site-Built                      1896
Multifamily:Manufactured                      78
Name: count, dtype: int64

================================================================================
FINAL AUDIT RESULT
================================================================================
Rows: 709,119
Columns: 204
Duplicates: 0

DATA QUALITY AUDIT COMPLETE

In [83]:
# ================================================================
# CREATE FINAL ANALYSIS DATASET
# ================================================================

analysis_columns = [
    # Identification / geography
    'activity_year',
    'lei',
    'derived_msa_md',
    'state_code',
    'county_code',
    'census_tract',

    # Loan characteristics
    'derived_loan_product_type',
    'loan_type',
    'loan_purpose',
    'lien_status',
    'purchaser_type',
    'preapproval',
    'reverse_mortgage',
    'open_end_line_of_credit',
    'business_or_commercial_purpose',

    # Loan financials
    'loan_amount_analysis_value',
    'property_value_analysis_value',
    'ltv_analysis_value',
    'debt_to_income_ratio_numeric',
    'interest_rate_analysis_value',
    'rate_spread_analysis_value',
    'loan_term_analysis_value',

    # Loan cost information
    'total_loan_costs_analysis_value',
    'total_points_and_fees_analysis_value',
    'origination_charges_analysis_value',
    'discount_points_analysis_value',
    'lender_credits_analysis_value',

    # Property characteristics
    'derived_dwelling_category',
    'occupancy_type',
    'construction_method',
    'total_units_clean',

    # Borrower characteristics
    'income_analysis_value',
    'applicant_age_analysis_category',
    'co_applicant_age_analysis_category',
    'derived_ethnicity',
    'derived_race',
    'derived_sex',

    # Loan outcome
    'action_taken',

    # Quality / anomaly flags
    'negative_income_flag',
    'zero_income_flag',
    'extreme_income_flag',
    'property_value_anomaly_flag',
    'extreme_ltv_flag',
    'ltv_consistency_flag',
    'high_interest_rate_flag',
    'extreme_rate_spread_flag',
    'rate_spread_anomaly_flag',
    'extreme_loan_amount_flag'
]

df_analysis = df[analysis_columns].copy()

print("=" * 80)
print("ANALYSIS DATASET CREATED")
print("=" * 80)

print("\nRows:", f"{df_analysis.shape[0]:,}")
print("Columns:", df_analysis.shape[1])

print("\nDuplicate rows:", df_analysis.duplicated().sum())

print("\nColumns:")
for i, column in enumerate(df_analysis.columns, start=1):
    print(f"{i:02d}. {column}")

KeyError: "['derived_msa_md', 'open_end_line_of_credit'] not in index"

In [84]:
# ================================================================
# CREATE FINAL ANALYSIS DATASET
# ================================================================

analysis_columns = [
    # Identification / geography
    'activity_year',
    'lei',
    'state_code',
    'county_code',
    'census_tract',

    # Loan characteristics
    'derived_loan_product_type',
    'loan_type',
    'loan_purpose',
    'lien_status',
    'purchaser_type',
    'preapproval',
    'reverse_mortgage',
    'business_or_commercial_purpose',

    # Loan financials
    'loan_amount_analysis_value',
    'property_value_analysis_value',
    'ltv_analysis_value',
    'debt_to_income_ratio_numeric',
    'interest_rate_analysis_value',
    'rate_spread_analysis_value',
    'loan_term_analysis_value',

    # Loan cost information
    'total_loan_costs_analysis_value',
    'total_points_and_fees_analysis_value',
    'origination_charges_analysis_value',
    'discount_points_analysis_value',
    'lender_credits_analysis_value',

    # Property characteristics
    'derived_dwelling_category',
    'occupancy_type',
    'construction_method',
    'total_units_clean',

    # Borrower characteristics
    'income_analysis_value',
    'applicant_age_analysis_category',
    'co_applicant_age_analysis_category',
    'derived_ethnicity',
    'derived_race',
    'derived_sex',

    # Loan outcome
    'action_taken',

    # Quality / anomaly flags
    'negative_income_flag',
    'zero_income_flag',
    'extreme_income_flag',
    'property_value_anomaly_flag',
    'extreme_ltv_flag',
    'ltv_consistency_flag',
    'high_interest_rate_flag',
    'extreme_rate_spread_flag',
    'rate_spread_anomaly_flag',
    'extreme_loan_amount_flag'
]

df_analysis = df[analysis_columns].copy()

print("=" * 80)
print("ANALYSIS DATASET CREATED")
print("=" * 80)

print("\nRows:", f"{df_analysis.shape[0]:,}")
print("Columns:", df_analysis.shape[1])

print("\nDuplicate rows:", df_analysis.duplicated().sum())

print("\nColumns:")
for i, column in enumerate(df_analysis.columns, start=1):
    print(f"{i:02d}. {column}")

================================================================================
ANALYSIS DATASET CREATED
================================================================================

Rows: 709,119
Columns: 46

Duplicate rows: 294

Columns:
01. activity_year
02. lei
03. state_code
04. county_code
05. census_tract
06. derived_loan_product_type
07. loan_type
08. loan_purpose
09. lien_status
10. purchaser_type
11. preapproval
12. reverse_mortgage
13. business_or_commercial_purpose
14. loan_amount_analysis_value
15. property_value_analysis_value
16. ltv_analysis_value
17. debt_to_income_ratio_numeric
18. interest_rate_analysis_value
19. rate_spread_analysis_value
20. loan_term_analysis_value
21. total_loan_costs_analysis_value
22. total_points_and_fees_analysis_value
23. origination_charges_analysis_value
24. discount_points_analysis_value
25. lender_credits_analysis_value
26. derived_dwelling_category
27. occupancy_type
28. construction_method
29. total_units_clean
30. income_analysis_value
31. applicant_age_analysis_category
32. co_applicant_age_analysis_category
33. derived_ethnicity
34. derived_race
35. derived_sex
36. action_taken
37. negative_income_flag
38. zero_income_flag
39. extreme_income_flag
40. property_value_anomaly_flag
41. extreme_ltv_flag
42. ltv_consistency_flag
43. high_interest_rate_flag
44. extreme_rate_spread_flag
45. rate_spread_anomaly_flag
46. extreme_loan_amount_flag

In [85]:
# ================================================================
# CREATE HUMAN-READABLE LOAN OUTCOME
# ================================================================

outcome_mapping = {
    1: 'Originated',
    2: 'Approved but Not Accepted',
    3: 'Denied'
}

df_analysis['loan_outcome'] = df_analysis['action_taken'].map(outcome_mapping)

print(df_analysis['loan_outcome'].value_counts())

loan_outcome
Originated                   494053
Denied                       184047
Approved but Not Accepted     31019
Name: count, dtype: int64

In [86]:
# ================================================================
# FINAL ANALYSIS DATASET CHECK
# ================================================================

print("=" * 80)
print("FINAL ANALYSIS DATASET CHECK")
print("=" * 80)

print("\nShape:")
print(f"Rows    : {df_analysis.shape[0]:,}")
print(f"Columns : {df_analysis.shape[1]}")

print("\nLoan Outcomes:")
print(df_analysis['loan_outcome'].value_counts())

print("\nMissing Values:")
print(f"Total missing cells: {df_analysis.isna().sum().sum():,}")

print("\nDuplicate rows in selected analytical columns:")
print(df_analysis.duplicated().sum())

print("\nData types:")
print(df_analysis.dtypes.value_counts())

================================================================================
FINAL ANALYSIS DATASET CHECK
================================================================================

Shape:
Rows    : 709,119
Columns : 47

Loan Outcomes:
loan_outcome
Originated                   494053
Denied                       184047
Approved but Not Accepted     31019
Name: count, dtype: int64

Missing Values:
Total missing cells: 3,843,987

Duplicate rows in selected analytical columns:
294

Data types:
float64    15
int64      11
str        11
bool       10
Name: count, dtype: int64

In [87]:
# ================================================================
# FINAL ANALYSIS DATASET CHECK
# ================================================================

print("=" * 80)
print("FINAL ANALYSIS DATASET CHECK")
print("=" * 80)

print("\nShape:")
print(f"Rows    : {df_analysis.shape[0]:,}")
print(f"Columns : {df_analysis.shape[1]}")

print("\nLoan Outcomes:")
print(df_analysis['loan_outcome'].value_counts())

print("\nMissing Values:")
print(f"Total missing cells: {df_analysis.isna().sum().sum():,}")

print("\nDuplicate rows in selected analytical columns:")
print(df_analysis.duplicated().sum())

print("\nData types:")
print(df_analysis.dtypes.value_counts())

================================================================================
FINAL ANALYSIS DATASET CHECK
================================================================================

Shape:
Rows    : 709,119
Columns : 47

Loan Outcomes:
loan_outcome
Originated                   494053
Denied                       184047
Approved but Not Accepted     31019
Name: count, dtype: int64

Missing Values:
Total missing cells: 3,843,987

Duplicate rows in selected analytical columns:
294

Data types:
float64    15
int64      11
str        11
bool       10
Name: count, dtype: int64

In [88]:
# ================================================================
# FINAL ANALYSIS DATASET CHECK
# ================================================================

print("=" * 80)
print("FINAL ANALYSIS DATASET CHECK")
print("=" * 80)

print("\nShape:")
print(f"Rows    : {df_analysis.shape[0]:,}")
print(f"Columns : {df_analysis.shape[1]}")

print("\nLoan Outcomes:")
print(df_analysis['loan_outcome'].value_counts())

print("\nMissing Values:")
print(f"Total missing cells: {df_analysis.isna().sum().sum():,}")

print("\nDuplicate rows in selected analytical columns:")
print(df_analysis.duplicated().sum())

print("\nData types:")
print(df_analysis.dtypes.value_counts())

================================================================================
FINAL ANALYSIS DATASET CHECK
================================================================================

Shape:
Rows    : 709,119
Columns : 47

Loan Outcomes:
loan_outcome
Originated                   494053
Denied                       184047
Approved but Not Accepted     31019
Name: count, dtype: int64

Missing Values:
Total missing cells: 3,843,987

Duplicate rows in selected analytical columns:
294

Data types:
float64    15
int64      11
str        11
bool       10
Name: count, dtype: int64

In [91]:
# ================================================================
# EXPORT FINAL ANALYSIS DATASET FOR MYSQL
# ================================================================

output_file = "bank_lending_analysis.csv"

df_analysis.to_csv(
    output_file,
    index=False
)

print("=" * 80)
print("EXPORT COMPLETED")
print("=" * 80)

print(f"\nFile name : {output_file}")
print(f"Rows      : {df_analysis.shape[0]:,}")
print(f"Columns   : {df_analysis.shape[1]}")
print(f"File size : {__import__('os').path.getsize(output_file) / (1024**2):.2f} MB")

================================================================================
EXPORT COMPLETED
================================================================================

File name : bank_lending_analysis.csv
Rows      : 709,119
Columns   : 47
File size : 211.19 MB

In [1]:
import os

print(os.path.abspath("bank_lending_analysis.csv"))

C:\Users\LENOVO GAMING\Desktop\DA-1\bank_lending_analysis.csv